### ISSUE TITLE
Does not enable

### ISSUE THREAD

**Issue by Sprax2013** [bergerhealer/TrainCarts#116]
##### Spigot version: git-Spigot-9ba269b-c19c293 (MC: 1.11.2) (Implementing API version 1.11.2-R0.1-SNAPSHOT)

<hr>

#### Problem or bug: Does not enable

[01:49:45] [Server thread/WARN]: Plugin `Train_Carts v1.75-SNAPSHOT' uses the space-character (0x20) in its name `Train Carts' - this will not work in Minecraft 1.12

[01:49:46] [Server thread/ERROR]: Could not load 'plugins/TrainCarts.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.IncompatibleClassChangeError: Implementing class
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:133) ~[spigot.jar:git-Spigot-9ba269b-c19c293]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329) ~[spigot.jar:git-Spigot-9ba269b-c19c293]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) [spigot.jar:git-Spigot-9ba269b-c19c293]
	at org.bukkit.craftbukkit.v1_11_R1.CraftServer.loadPlugins(CraftServer.java:301) [spigot.jar:git-Spigot-9ba269b-c19c293]
	at net.minecraft.server.v1_11_R1.DedicatedServer.init(DedicatedServer.java:204) [spigot.jar:git-Spigot-9ba269b-c19c293]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:544) [spigot.jar:git-Spigot-9ba269b-c19c293]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
Caused by: java.lang.IncompatibleClassChangeError: Implementing class
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_121]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763) ~[?:1.8.0_121]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_121]
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467) ~[?:1.8.0_121]
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73) ~[?:1.8.0_121]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368) ~[?:1.8.0_121]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362) ~[?:1.8.0_121]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_121]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361) ~[?:1.8.0_121]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot.jar:git-Spigot-9ba269b-c19c293]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot.jar:git-Spigot-9ba269b-c19c293]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_121]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_121]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_121]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_121]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[spigot.jar:git-Spigot-9ba269b-c19c293]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129) ~[spigot.jar:git-Spigot-9ba269b-c19c293]
	... 6 more

**Comment by Bart-0110** [comment]
You are using BKCommonLib for 1.11.2 but TrainCarts for 1.8.8. You can download the 1.11.2 version [here](https://www.spigotmc.org/resources/traincarts.39592/)

**Comment by Sprax2013** [comment]
I got it working already but thanks :)
