### ISSUE TITLE
Teleports doesn't work on 1.11.2

### ISSUE THREAD

**Issue by AlexxNB** [bergerhealer/TrainCarts#120]
##### Spigot version: 1.11.2
<hr>

Hello!

#### Problem or bug:
I tried to make teleporter for traincarts in clean Spigot server (only vault, BkCommonLib, TrainCarts, SignLink and MyWorlds). But it doesn't work. I've made portal signs, but traincarts are disapeared on portal t1 and never go back from portal t2. 

#### Video of the bug:
Please check the video for more information: https://www.youtube.com/watch?v=uSiAmrFBko0&feature=youtu.be

#### Error log1:
[11:13:52] [Server thread/ERROR]: [SignLink] An error occured while updating the signs:
[11:13:52] [Server thread/ERROR]: [SignLink] Field is missing from a dependency of this plugin
[11:13:52] [Server thread/ERROR]: [SignLink] Please, check for an updated version of SignLink and BKCommonLib before reporting this bug!
[11:13:52] [Server thread/ERROR]: [BKCommonLib] java.lang.NoSuchFieldError: removeQueue
[11:13:52] [Server thread/ERROR]: [BKCommonLib]   at com.bergerkiller.bukkit.common.internal.CommonPlayerMeta.<init>(CommonPlayerMeta.java:28)
[11:13:52] [Server thread/ERROR]: [BKCommonLib]   at com.bergerkiller.bukkit.common.internal.CommonPlugin.getPlayerMeta(CommonPlugin.java:156)
[11:13:52] [Server thread/ERROR]: [BKCommonLib]   at com.bergerkiller.bukkit.common.utils.PlayerUtil.isChunkVisible(PlayerUtil.java:206)
[11:13:52] [Server thread/ERROR]: [BKCommonLib]   at com.bergerkiller.bukkit.sl.VirtualSign.isInRange(VirtualSign.java:264)
[11:13:52] [Server thread/ERROR]: [BKCommonLib]   at com.bergerkiller.bukkit.sl.VirtualSign.update(VirtualSign.java:334)
[11:13:52] [Server thread/ERROR]: [BKCommonLib]   at com.bergerkiller.bukkit.sl.VirtualSignStore.updateAll(VirtualSignStore.java:129)
[11:13:52] [Server thread/ERROR]: [BKCommonLib]   at com.bergerkiller.bukkit.sl.SignLink$2.run(SignLink.java:135)
[11:13:52] [Server thread/ERROR]: [BKCommonLib]   at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftTask.run(CraftTask.java:58)
[11:13:52] [Server thread/ERROR]: [BKCommonLib]   at org.bukkit.craftbukkit.v1_11_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:356)
[11:13:52] [Server thread/ERROR]: [BKCommonLib]   at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:820)
[11:13:52] [Server thread/ERROR]: [BKCommonLib]   at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:403)
[11:13:52] [Server thread/ERROR]: [BKCommonLib]   at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:754)
[11:13:52] [Server thread/ERROR]: [BKCommonLib]   at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:652)
[11:13:52] [Server thread/ERROR]: [BKCommonLib]   at java.lang.Thread.run(Unknown Source)

#### Error log2:
[11:13:39] [Server thread/ERROR]: [Train_Carts] Failed to execute GROUP_ENTER for SignActionTeleport:
java.lang.NoSuchFieldError: removeQueue
	at com.bergerkiller.bukkit.common.server.CraftBukkitServer.getEntityRemoveQueue(CraftBukkitServer.java:96) ~[?:?]
	at com.bergerkiller.bukkit.common.entity.type.CommonPlayer.getEntityRemoveQueue(CommonPlayer.java:121) ~[?:?]
	at com.bergerkiller.bukkit.common.entity.type.CommonPlayer.flushEntityRemoveQueue(CommonPlayer.java:98) ~[?:?]
	at com.bergerkiller.bukkit.common.entity.CommonEntity.teleport(CommonEntity.java:533) ~[?:?]
	at com.bergerkiller.bukkit.common.bases.ExtendedEntity.teleport(ExtendedEntity.java:939) ~[?:?]
	at com.bergerkiller.bukkit.tc.controller.MinecartGroup.teleportMember(MinecartGroup.java:474) ~[?:?]
	at com.bergerkiller.bukkit.tc.controller.MinecartGroup.teleport(MinecartGroup.java:458) ~[?:?]
	at com.bergerkiller.bukkit.tc.controller.MinecartGroup.teleport(MinecartGroup.java:441) ~[?:?]
	at com.bergerkiller.bukkit.tc.controller.MinecartGroup.teleport(MinecartGroup.java:437) ~[?:?]
	at com.bergerkiller.bukkit.tc.controller.MinecartGroup.teleportAndGo(MinecartGroup.java:428) ~[?:?]
	at com.bergerkiller.bukkit.tc.signactions.SignActionTeleport.execute(SignActionTeleport.java:58) ~[?:?]
	at com.bergerkiller.bukkit.tc.signactions.SignAction.executeAll(SignAction.java:183) ~[?:?]

#### Expected behaviour:
traincarts should be appears at portal t2

#### Steps to reproduce:
Make a simple teleport for trains as decribed in wiki.

**Comment by Bart-0110** [comment]
Are you using PaperSpigot? If so please try the normal Spigot because PaperSpigot made some modifications to the NMS code in which the method `removeQueue` doesn't exist.

**Comment by AlexxNB** [comment]
Yuup! It works only on Spigot-1.11.2-R0.1-SNAPSHOT

**Comment by AlexxNB** [comment]
I can't work with MyWorlds. Maybe you can make teleportation sign inside world without that plugin? MyWorlds a little bit buggy now....

**Comment by Bart-0110** [comment]
MyWorlds is needed for teleport signs to work. You can try to create an issue on the [MyWorlds GitHub page](https://github.com/bergerhealer/MyWorlds).

**Comment by mg-1999** [comment]
Paperspigot support has recently been added, you can test with the most recent dev builds from the  [buildserver](https://ci.mg-dev.eu).

**Comment by AlexxNB** [comment]
Good news! Thank you! I'll try.
