### ISSUE TITLE
Crafter sign not work

### ISSUE THREAD

**Issue by david50407** [bergerhealer/TrainCarts#135]
##### Spigot version: 1.11.2-R0.1-SNAPSHOT (git-Spigot-283de8b)

<hr>

#### Steps to reproduce:

1. Place Crafter sign on a crafting table as below: (and get successed message)

```
[!train]
craft
iron_block

````

2. Place a Spawner sign as below: (and get successed message)

```
[!train]
spawn
s

```

3. After the train spawned, place some iron ingots (64 iron ingots in my case) into the storage cart.

4. Push the cart passthrough the Crafter sign.

Like this screenshot below:

![image](https://user-images.githubusercontent.com/841969/27129818-3f533b26-5136-11e7-9334-30a1d9a9c5b3.png)

**Comment by bergerkiller** [comment]
These bugs may very well be in BKCommonLib since there were some Recipe changes in minecraft server, but I will look into it.

**Comment by bergerkiller** [comment]
Can you verify this is fixed with this new build of BKCommonLib?

https://ci.mg-dev.eu/job/BKCommonLib/65/

**Comment by david50407** [comment]
@bergerkiller no, the problem's still there.

**Comment by bergerkiller** [comment]
Two more bugfixes. Crafter sign now works locally, I had no time to test last time.
https://github.com/bergerhealer/Mountiplex/commit/11c28042e553b89f946d0d46a82b8a10057332d3
https://github.com/bergerhealer/BKCommonLib/commit/4afc3f21a67dd60bd8bc7bf76e40e38984147cef

It should work with this new version of BKCommonLib:
https://ci.mg-dev.eu/job/BKCommonLib/67/

Also interesting, I added a config option in TC to also allow the crafter sign to work without a crafting table around.
https://ci.mg-dev.eu/job/TrainCarts/42/

Let me know how that goes.

**Comment by david50407** [comment]
Oops, it throws a exception to console:

```
[00:14:03 ERROR]: [Train_Carts] Failed to execute GROUP_ENTER for SignActionCraft:
java.lang.ClassCastException: com.bergerkiller.generated.net.minecraft.server.CraftingManagerHandle cannot be cast to net.minecraft.server.v1_11_R1.CraftingManager
        at com.bergerkiller.mountiplex.reflection.util.fast.GeneratedInvoker$mplgen474b613b.invoke(Unknown Source) ~[?:?]
        at com.bergerkiller.mountiplex.reflection.util.FastMethod.invoke(FastMethod.java:74) ~[?:?]
        at com.bergerkiller.mountiplex.reflection.declarations.Template$Method.invoke(Template.java:807) ~[?:?]
        at com.bergerkiller.mountiplex.reflection.declarations.Template$Method$Converted.invoke(Template.java:923) ~[?:?]
        at com.bergerkiller.generated.net.minecraft.server.CraftingManagerHandle.getRecipes(CraftingManagerHandle.java:35) ~[?:?]
        at com.bergerkiller.bukkit.common.utils.RecipeUtil.getCraftRecipes(RecipeUtil.java:154) ~[?:?]
        at com.bergerkiller.bukkit.common.utils.RecipeUtil.getCraftingRequirements(RecipeUtil.java:109) ~[?:?]
        at com.bergerkiller.bukkit.common.utils.RecipeUtil.craftItems(RecipeUtil.java:148) ~[?:?]
        at com.bergerkiller.bukkit.common.utils.RecipeUtil.craftItems(RecipeUtil.java:135) ~[?:?]
        at com.bergerkiller.bukkit.tc.signactions.SignActionCraft.execute(SignActionCraft.java:72) ~[?:?]
        at com.bergerkiller.bukkit.tc.signactions.SignAction.executeAll(SignAction.java:183) ~[?:?]
```

**Comment by bergerkiller** [comment]
Whoops, missed that because I'm testing on 1.12. Fixed that bug.
https://github.com/bergerhealer/BKCommonLib/commit/27186978d68b5ab77d4c9624842f851898eefb78

https://ci.mg-dev.eu/job/BKCommonLib/69/

**Comment by david50407** [comment]
No exception anymore, but still not crafting. (tried both `craftingRequireWorkbench` true and false)

**Comment by bergerkiller** [comment]
can confirm on 1.11.2. It works on 1.12 though. Weird, but itll be fixed.

**Comment by bergerkiller** [comment]
A real pain to fix, because there was a nasty bug converting ItemStack[] into List<CraftInputSlot> in Mountiplex itself, as well a bug involving requiring 9x the amount of ingots to do the crafting. I could verify on 1.11.2, that it works for me now.

https://ci.mg-dev.eu/job/BKCommonLib/72/

Let me know if this is now OK.

**Comment by david50407** [comment]
Worked, thanks 😄 

BTW, log/log2 wont crafted into planks, is this a bug?

**Comment by bergerkiller** [comment]
The recipe name is 'wood', not 'planks'. This works for me:

```
[+train]
craft
wood
```

**Comment by david50407** [comment]
Thanks!

btw, is there any name<->id mapping sheet in BKC? cause `planks` is minecraft item name `minecraft:planks`. wood is different from minecraft naming

**Comment by bergerkiller** [comment]
The reason for that is, well, Bukkit. The material by name parsing function is ages old, way before materials had names in minecraft. It depends on the Bukkit Material enumeration. Checking by minecraft material names instead of Bukkit materials might be an option, but at the moment I don't yet see much gain.

https://gist.github.com/bergerkiller/9fc0277ee5b9a65e38f9e6475dd87871

Here is the Bukkit Material enum, whose names are matched together with the aliases Ive provided.

**Comment by david50407** [comment]
Got it, thanks :heart:
