### ISSUE TITLE
Hopper cart wont suck items

### ISSUE THREAD

**Issue by david50407** [bergerhealer/TrainCarts#136]
##### Spigot version: 1.11.2-R0.1-SNAPSHOT (git-Spigot-283de8b)

<hr>

#### Steps to reproduce: 

1. Place any hopper cart

2. Try these actions:
    * Drop items on it
    * Place a chest/hopper/(any storage block) above cart and put items inside the box.

3. Check hopper cart, there isn't any items inside the cart.

**Comment by bergerkiller** [comment]
Fixes:
https://github.com/bergerhealer/BKCommonLib/commit/c1badddaee6dc431095e0b292dd0ee568ef2bef2
https://github.com/bergerhealer/TrainCarts/commit/76651536578c424aa1b4a91ce573f5a1246fec34

Builds:
https://ci.mg-dev.eu/job/BKCommonLib/68/
https://ci.mg-dev.eu/job/TrainCarts/43/

Can you verify the bugs are fixed? Hoppers correctly suck dropped items on my server, activator rail now correctly turns this sucking off when powered, and back on when unpowered. I verified this logic in minecraft singleplayer. It now also collects items dropped nearby, something that was previously not working.

**Comment by david50407** [comment]
Exception below:

```
[02:25:39 ERROR]: [Train_Carts] Failed to perform physics on train 'train2' at world_58_68_291:
[02:25:39 ERROR]: [BKCommonLib] java.lang.UnsupportedOperationException: Method is not available
[02:25:39 ERROR]: [BKCommonLib]   at com.bergerkiller.mountiplex.reflection.util.FastMethod.checkInit(FastMethod.java:30)
[02:25:39 ERROR]: [BKCommonLib]   at com.bergerkiller.mountiplex.reflection.util.FastMethod.init(FastMethod.java:60)
[02:25:39 ERROR]: [BKCommonLib]   at com.bergerkiller.mountiplex.reflection.util.FastMethod.invoke(FastMethod.java:74)
[02:25:39 ERROR]: [BKCommonLib]   at com.bergerkiller.mountiplex.reflection.declarations.Template$Method.invoke(Template.java:807)
[02:25:39 ERROR]: [BKCommonLib]   at com.bergerkiller.bukkit.common.entity.type.CommonMinecartHopper.suckItems(CommonMinecartHopper.java:38)
[02:25:39 ERROR]: [BKCommonLib]   at com.bergerkiller.bukkit.tc.controller.type.MinecartMemberHopper.onPhysicsPostMove(MinecartMemberHopper.java:34)
[02:25:39 ERROR]: [BKCommonLib]   at com.bergerkiller.bukkit.tc.controller.MinecartGroup.doPhysics_step(MinecartGroup.java:971)
[02:25:39 ERROR]: [BKCommonLib]   at com.bergerkiller.bukkit.tc.controller.MinecartGroup.doPhysics(MinecartGroup.java:885)
[02:25:39 ERROR]: [BKCommonLib]   at com.bergerkiller.bukkit.tc.controller.MinecartMember.onTick(MinecartMember.java:1183)
[02:25:39 ERROR]: [BKCommonLib]   at com.bergerkiller.bukkit.common.internal.hooks.EntityHook.onTick(EntityHook.java:72)
[02:25:39 ERROR]: [BKCommonLib]   at com.bergerkiller.mountiplex.reflection.util.fast.GeneratedInvoker$mplgen102c8e14.invoke(Unknown Source)
[02:25:39 ERROR]: [BKCommonLib]   at com.bergerkiller.mountiplex.reflection.util.fast.GeneratedInvoker$mplgen102c8e14.invokeVA(Unknown Source)
[02:25:39 ERROR]: [BKCommonLib]   at com.bergerkiller.mountiplex.reflection.util.FastMethod.invokeVA(FastMethod.java:69)
[02:25:39 ERROR]: [BKCommonLib]   at com.bergerkiller.mountiplex.reflection.ClassInterceptor$CallbackMethodInterceptor.intercept(ClassInterceptor.java:580)
[02:25:39 ERROR]: [BKCommonLib]   at net.minecraft.server.v1_11_R1.EntityMinecartHopper$$EnhancerByCGLIB$$84fdc06c.A_(<generated>)
[02:25:39 ERROR]: [BKCommonLib]   at net.minecraft.server.v1_11_R1.World.entityJoinedWorld(World.java:1629)
[02:25:39 ERROR]: [BKCommonLib]   at net.minecraft.server.v1_11_R1.World.h(World.java:1604)
[02:25:39 ERROR]: [BKCommonLib]   at net.minecraft.server.v1_11_R1.World.tickEntities(World.java:1430)
[02:25:39 ERROR]: [BKCommonLib]   at net.minecraft.server.v1_11_R1.WorldServer.tickEntities(WorldServer.java:618)
[02:25:39 ERROR]: [BKCommonLib]   at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:814)
[02:25:39 ERROR]: [BKCommonLib]   at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399)
[02:25:39 ERROR]: [BKCommonLib]   at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678)
[02:25:39 ERROR]: [BKCommonLib]   at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576)
[02:25:39 ERROR]: [BKCommonLib]   at java.lang.Thread.run(Thread.java:745)
```

**Comment by david50407** [comment]
Got this while enabling BKC:

```
[02:30:48 INFO]: [BKCommonLib] Loading BKCommonLib v1.12-v2-SNAPSHOT
[02:30:49 WARN]: A class member of net.minecraft.server.v1_11_R1.EntityMinecartHopper was not found!
[02:30:49 WARN]: Failed to find method public boolean suckItems:H(); - Alternatives:
[02:30:49 WARN]:   - public boolean I();
[02:30:49 WARN]:   - public boolean J();
[02:30:49 WARN]:   - public double F();
[02:30:49 WARN]:   - public double E();
[02:30:49 WARN]:   - public v1_11_R1.EntityMinecartAbstract.EnumMinecartType v();
[02:30:49 WARN]:   - public double G();
[02:30:49 WARN]:   - public int z();
[02:30:49 WARN]:   - public v1_11_R1.IBlockData x();
```

**Comment by bergerkiller** [comment]
Another one of those functions that got renamed between 1.11.2 and 1.12..ugh. Here.
https://github.com/bergerhealer/BKCommonLib/commit/0ebe8c542dc0c37997c8896efcde91730c0cfd89

https://ci.mg-dev.eu/job/BKCommonLib/70/

**Comment by david50407** [comment]
worked! thanks
