### ISSUE TITLE
Failed to perform physics on train

### ISSUE THREAD

**Issue by zelestcarlyone** [bergerhealer/TrainCarts#151]
##### Spigot version: CraftBukkit version git-Spigot-596221b-b1b9ab0 (MC: 1.12) (Implementing API version 1.12-R0.1-SNAPSHOT)

<hr>

#### Problem or bug: I just finished installing a brand new SpigotMC on my Linux server and everything works fine apart from the fact that my console fills with tons and tons of messages every second about Train_Carts failing:

> [07:52:06 ERROR]: [Train_Carts] Failed to perform physics on train 'train2' at Tionia_-368_17_18:
> [07:52:06 ERROR]: [BKCommonLib] java.lang.ClassCastException
> [07:52:06 ERROR]: [Train_Carts] Failed to perform physics on train 'train1' at Tionia_-399_23_47:
> [07:52:06 ERROR]: [BKCommonLib] java.lang.ClassCastException
> [07:52:06 ERROR]: [Train_Carts] Failed to perform physics on train 'train2' at Tionia_-368_17_18:
> [07:52:06 ERROR]: [BKCommonLib] java.lang.ClassCastException
> [07:52:06 ERROR]: [Train_Carts] Failed to perform physics on train 'train1' at Tionia_-399_23_47:
> [07:52:06 ERROR]: [BKCommonLib] java.lang.ClassCastException
> [07:52:06 ERROR]: [Train_Carts] Failed to perform physics on train 'train2' at Tionia_-368_17_18:
> [07:52:06 ERROR]: [BKCommonLib] java.lang.ClassCastException
> [07:52:06 ERROR]: [Train_Carts] Failed to perform physics on train 'train1' at Tionia_-399_23_47:
> [07:52:06 ERROR]: [BKCommonLib] java.lang.ClassCastException
> [07:52:06 ERROR]: [Train_Carts] Failed to perform physics on train 'train2' at Tionia_-368_17_18:
> [07:52:06 ERROR]: [BKCommonLib] java.lang.ClassCastException
> [07:52:06 ERROR]: [Train_Carts] Failed to perform physics on train 'train1' at Tionia_-399_23_47:
> [07:52:06 ERROR]: [BKCommonLib] java.lang.ClassCastExceptio

Every now and again I also get these messages:

> [07:52:06 ERROR]: Could not pass event ChunkUnloadEvent to Train_Carts v1.12-v2
> org.bukkit.event.EventException: null
>         at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-596221b-b1b9ab0]
>         at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-596221b-b1b9ab0]
>         at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499) [spigot.jar:git-Spigot-596221b-b1b9ab0]
>         at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [spigot.jar:git-Spigot-596221b-b1b9ab0]
>         at net.minecraft.server.v1_12_R1.ChunkProviderServer.unloadChunk(ChunkProviderServer.java:293) [spigot.jar:git-Spigot-596221b-b1b9ab0]
>         at net.minecraft.server.v1_12_R1.ChunkProviderServer.unloadChunks(ChunkProviderServer.java:268) [spigot.jar:git-Spigot-596221b-b1b9ab0]
>         at net.minecraft.server.v1_12_R1.WorldServer.doTick(WorldServer.java:293) [spigot.jar:git-Spigot-596221b-b1b9ab0]
>         at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:798) [spigot.jar:git-Spigot-596221b-b1b9ab0]
>         at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405) [spigot.jar:git-Spigot-596221b-b1b9ab0]
>         at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot.jar:git-Spigot-596221b-b1b9ab0]
>         at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot.jar:git-Spigot-596221b-b1b9ab0]
>         at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
> Caused by: java.lang.ClassCastException

And also

> [08:02:49 ERROR]: [Train_Carts] Failed to perform physics on train 'train5' at Tionia_-368_17_18:
> [08:02:49 ERROR]: [BKCommonLib] java.lang.ClassCastException: com.bergerkiller.generated.org.bukkit.craftbukkit.util.LongObjectHashMapHandle cannot be cast to org.bukkit.craftbukkit.v1_12_R1.util.LongObjectHashMap
> [08:02:49 ERROR]: [BKCommonLib]   at com.bergerkiller.mountiplex.reflection.util.fast.GeneratedInvoker$mplgen251f518c.invoke(Unknown Source)
> [08:02:49 ERROR]: [BKCommonLib]   at com.bergerkiller.mountiplex.reflection.declarations.Template$Method.invoke(Template.java:1100)
> [08:02:49 ERROR]: [BKCommonLib]   at com.bergerkiller.generated.org.bukkit.craftbukkit.util.LongObjectHashMapHandle.get(LongObjectHashMapHandle.java:42)
> [08:02:49 ERROR]: [BKCommonLib]   at com.bergerkiller.bukkit.common.wrappers.LongHashMap.get(LongHashMap.java:77)
> [08:02:49 ERROR]: [BKCommonLib]   at com.bergerkiller.bukkit.tc.storage.OfflineGroupMap.getOrCreate(OfflineGroupMap.java:118)
> [08:02:49 ERROR]: [BKCommonLib]   at com.bergerkiller.bukkit.tc.storage.OfflineGroupMap.add(OfflineGroupMap.java:33)
> [08:02:49 ERROR]: [BKCommonLib]   at com.bergerkiller.bukkit.tc.storage.OfflineGroupManager.storeGroup(OfflineGroupManager.java:346)
> [08:02:49 ERROR]: [BKCommonLib]   at com.bergerkiller.bukkit.tc.controller.MinecartGroup.unload(MinecartGroup.java:383)
> [08:02:49 ERROR]: [BKCommonLib]   at com.bergerkiller.bukkit.tc.controller.MinecartGroup.doPhysics_step(MinecartGroup.java:1097)
> [08:02:49 ERROR]: [BKCommonLib]   at com.bergerkiller.bukkit.tc.controller.MinecartGroup.doPhysics(MinecartGroup.java:928)
> [08:02:49 ERROR]: [BKCommonLib]   at com.bergerkiller.bukkit.tc.controller.MinecartGroupStore.doFixedTick(MinecartGroupStore.java:34)
> [08:02:49 ERROR]: [BKCommonLib]   at com.bergerkiller.bukkit.tc.TrainCarts$TrainUpdateTask.run(TrainCarts.java:716)
> [08:02:49 ERROR]: [BKCommonLib]   at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71)
> [08:02:49 ERROR]: [BKCommonLib]   at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353)
> [08:02:49 ERROR]: [BKCommonLib]   at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:738)
> [08:02:49 ERROR]: [BKCommonLib]   at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405)
> [08:02:49 ERROR]: [BKCommonLib]   at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678)
> [08:02:49 ERROR]: [BKCommonLib]   at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576)
> [08:02:49 ERROR]: [BKCommonLib]   at java.lang.Thread.run(Thread.java:748)

Loading the plugin seems to work without a hitch:

> [08:07:39 INFO]: [Train_Carts] Enabling Train_Carts v1.12-v2
> [08:07:41 INFO]: [Train_Carts] Restoring trains and loading nearby chunks...
> [08:07:41 INFO]: [Train_Carts] Train_Carts version 1.12-v2 enabled! (2.034s)

This is a freshly started server where no player even have logged in yet. Interesting thing to note is that in the plugin settings folder there is a generated TrainProperties.yml with 3 carts in it already. Problem persists and new carts with new numbers is generated if I clean out this file.

We have since started playing on the server but not gotten as far as setting up mine carts yet.

#### Expected behaviour:

Expecting no error messages on a fresh server that drains CPU usage upon load.

#### Steps to reproduce:

1) Set up a fresh server
2) Install BKCommonLib
3) Install Train_Carts
4) Start server for first time
5) Get error messages
6) ?!?!?!?!
7) Profit!

**Comment by zelestcarlyone** [comment]
Ah, oops! Did the deleteall command and some 300+ world-generated carts were despawned and it fixed the error. Also lowered the CPU-usage with some 110% when idle.
