### ISSUE TITLE
TrainCarts failed when server started

### ISSUE THREAD

**Issue by mjl1010** [bergerhealer/TrainCarts#154]
##### Spigot version: This server is running CraftBukkit version git-Spigot-edd0396-2a927e8 (MC: 1.12.1) (Implementing API version 1.12.1-R0.1-SNAPSHOT)

<hr>

#### Problem or bug: In Enabled plugins, i catch an error, and when started server, traincarts enter to loop of errors (and crash server):
[Train_Carts] Enabling Train_Carts v1.12-v2
[13:16:46] [Server thread/ERROR]: [BKCommonLib] [Configuration] An error occured while loading file 'plugins/Train_Carts/trains.groupdata':
[13:16:46] [Server thread/WARN]: java.lang.ClassCastException: com.bergerkiller.generated.org.bukkit.craftbukkit.util.LongObjectHashMapHandle cannot be cast to org.bukkit.craftbukkit.v1_12_R1.util.LongObjectHashMap
[13:16:46] [Server thread/WARN]: 	at com.bergerkiller.mountiplex.reflection.util.fast.GeneratedInvoker$mplgen1cef2464.invoke(Unknown Source)
[13:16:46] [Server thread/WARN]: 	at com.bergerkiller.mountiplex.reflection.util.FastMethod.invoke(FastMethod.java:122)
[13:16:46] [Server thread/WARN]: 	at com.bergerkiller.mountiplex.reflection.declarations.Template$Method.invoke(Template.java:1100)
[13:16:46] [Server thread/WARN]: 	at com.bergerkiller.generated.org.bukkit.craftbukkit.util.LongObjectHashMapHandle.get(LongObjectHashMapHandle.java:42)
[13:16:46] [Server thread/WARN]: 	at com.bergerkiller.bukkit.common.wrappers.LongHashMap.get(LongHashMap.java:77)
[13:16:46] [Server thread/WARN]: 	at com.bergerkiller.bukkit.tc.storage.OfflineGroupMap.getOrCreate(OfflineGroupMap.java:118)
[13:16:46] [Server thread/WARN]: 	at com.bergerkiller.bukkit.tc.storage.OfflineGroupMap.add(OfflineGroupMap.java:33)
[13:16:46] [Server thread/WARN]: 	at com.bergerkiller.bukkit.tc.storage.OfflineGroupManager$1.read(OfflineGroupManager.java:277)
[13:16:46] [Server thread/WARN]: 	at com.bergerkiller.bukkit.common.config.DataReader.read(DataReader.java:80)
[13:16:46] [Server thread/WARN]: 	at com.bergerkiller.bukkit.tc.storage.OfflineGroupManager.init(OfflineGroupManager.java:293)
[13:16:46] [Server thread/WARN]: 	at com.bergerkiller.bukkit.tc.TrainCarts.enable(TrainCarts.java:549)
[13:16:46] [Server thread/WARN]: 	at com.bergerkiller.bukkit.common.PluginBase.onEnable(PluginBase.java:779)
[13:16:46] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[13:16:46] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
[13:16:46] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402)
[13:16:46] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:374)
[13:16:46] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:323)
[13:16:46] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422)
[13:16:46] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383)
[13:16:46] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338)
[13:16:46] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272)
[13:16:46] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545)
[13:16:46] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[13:16:46] [Server thread/INFO]: [Train_Carts] 0 detector rail regions loaded covering 0 blocks
[13:16:46] [Server thread/INFO]: [Train_Carts] Restoring trains and loading nearby chunks...
[13:16:46] [Server thread/WARN]: java.lang.ClassCastException: com.bergerkiller.generated.org.bukkit.craftbukkit.util.LongObjectHashMapHandle cannot be cast to org.bukkit.craftbukkit.v1_12_R1.util.LongObjectHashMap
[13:16:46] [Server thread/WARN]: 	at com.bergerkiller.mountiplex.reflection.util.fast.GeneratedInvoker$mplgen1cef2464.invoke(Unknown Source)
[13:16:46] [Server thread/WARN]: 	at com.bergerkiller.mountiplex.reflection.declarations.Template$Method.invoke(Template.java:1100)
[13:16:46] [Server thread/WARN]: 	at com.bergerkiller.generated.org.bukkit.craftbukkit.util.LongObjectHashMapHandle.get(LongObjectHashMapHandle.java:42)
[13:16:46] [Server thread/WARN]: 	at com.bergerkiller.bukkit.common.wrappers.LongHashMap.get(LongHashMap.java:77)
[13:16:46] [Server thread/WARN]: 	at com.bergerkiller.bukkit.tc.storage.OfflineGroupMap.get(OfflineGroupMap.java:114)
[13:16:46] [Server thread/WARN]: 	at com.bergerkiller.bukkit.tc.storage.OfflineGroupMap.remove(OfflineGroupMap.java:77)
[13:16:46] [Server thread/WARN]: 	at com.bergerkiller.bukkit.tc.storage.OfflineGroupManager.restoreGroup(OfflineGroupManager.java:464)
[13:16:46] [Server thread/WARN]: 	at com.bergerkiller.bukkit.tc.storage.OfflineGroupManager.refreshGroups(OfflineGroupManager.java:452)
[13:16:46] [Server thread/WARN]: 	at com.bergerkiller.bukkit.tc.storage.OfflineGroupManager.refresh(OfflineGroupManager.java:108)
[13:16:46] [Server thread/WARN]: 	at com.bergerkiller.bukkit.tc.storage.OfflineGroupManager.refresh(OfflineGroupManager.java:97)
[13:16:46] [Server thread/WARN]: 	at com.bergerkiller.bukkit.tc.TrainCarts.enable(TrainCarts.java:571)
[13:16:46] [Server thread/WARN]: 	at com.bergerkiller.bukkit.common.PluginBase.onEnable(PluginBase.java:779)
[13:16:46] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[13:16:46] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
[13:16:46] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402)
[13:16:46] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:374)
[13:16:46] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:323)
[13:16:46] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422)
[13:16:46] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383)
[13:16:46] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338)
[13:16:46] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272)
[13:16:46] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545)
[13:16:46] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[13:16:46] [Server thread/INFO]: [Train_Carts] SignLink detected, support for arrival signs added!
[13:16:46] [Server thread/INFO]: [Train_Carts] Train_Carts version 1.12-v2 enabled! (1.257s)

#################################################################

[13:17:06] [Server thread/ERROR]: Could not pass event ChunkUnloadEvent to Train_Carts v1.12-v2
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-edd0396-2a927e8]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-edd0396-2a927e8]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499) [spigot.jar:git-Spigot-edd0396-2a927e8]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [spigot.jar:git-Spigot-edd0396-2a927e8]
	at net.minecraft.server.v1_12_R1.ChunkProviderServer.unloadChunk(ChunkProviderServer.java:293) [spigot.jar:git-Spigot-edd0396-2a927e8]
	at net.minecraft.server.v1_12_R1.ChunkProviderServer.unloadChunks(ChunkProviderServer.java:268) [spigot.jar:git-Spigot-edd0396-2a927e8]
	at net.minecraft.server.v1_12_R1.WorldServer.doTick(WorldServer.java:293) [spigot.jar:git-Spigot-edd0396-2a927e8]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:801) [spigot.jar:git-Spigot-edd0396-2a927e8]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [spigot.jar:git-Spigot-edd0396-2a927e8]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot.jar:git-Spigot-edd0396-2a927e8]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot.jar:git-Spigot-edd0396-2a927e8]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: java.lang.ClassCastException: com.bergerkiller.generated.org.bukkit.craftbukkit.util.LongObjectHashMapHandle cannot be cast to org.bukkit.craftbukkit.v1_12_R1.util.LongObjectHashMap
	at com.bergerkiller.mountiplex.reflection.util.fast.GeneratedInvoker$mplgen1cef2464.invoke(Unknown Source) ~[?:?]
	at com.bergerkiller.mountiplex.reflection.declarations.Template$Method.invoke(Template.java:1100) ~[?:?]
	at com.bergerkiller.generated.org.bukkit.craftbukkit.util.LongObjectHashMapHandle.get(LongObjectHashMapHandle.java:42) ~[?:?]
	at com.bergerkiller.bukkit.common.wrappers.LongHashMap.get(LongHashMap.java:77) ~[?:?]
	at com.bergerkiller.bukkit.tc.storage.OfflineGroupMap.getOrCreate(OfflineGroupMap.java:118) ~[?:?]
	at com.bergerkiller.bukkit.tc.storage.OfflineGroupMap.add(OfflineGroupMap.java:33) ~[?:?]
	at com.bergerkiller.bukkit.tc.storage.OfflineGroupManager.storeGroup(OfflineGroupManager.java:346) ~[?:?]
	at com.bergerkiller.bukkit.tc.controller.MinecartGroup.unload(MinecartGroup.java:383) ~[?:?]
	at com.bergerkiller.bukkit.tc.TCListener.onChunkUnload(TCListener.java:151) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor27.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot.jar:git-Spigot-edd0396-2a927e8]
	... 11 more

#### Steps to reproduce: Use BKcommonLib, ProtocolLib and TrainCarts in Spigot 1.12, init the server, and after update to Spigot 1.12.1, it crashes.

Thanks.

**Comment by ApocalypsjeNL** [comment]
TrainCarts isn't updated yet to Spigot 1.12.1

**Comment by bergerkiller** [comment]
I have pushed a new version of BKCommonLib that adds 1.12.1 support. There was also a bug in PermissionDefaults.yml that caused all permissions for using TrainCarts were revoked by default. Delete the PermissionDefaults.yml file (in the Train_Carts folder) after updating so it can be regenerated and this bug will be fixed.

https://www.spigotmc.org/resources/bkcommonlib.39590/update?update=180187
