### ISSUE TITLE
No Commands or Signs are Working

### ISSUE THREAD

**Issue by MartianMH** [bergerhealer/TrainCarts#168]
##### Spigot version: 1.12-R0.1-SNAPSHOT

<hr>

#### Steps to reproduce: I started up the server, placed a sign under rails, typed "[train]"
then next line: "spawner" next line: "mm" and when I activated the sign with redstone, nothing happened.

Here is what the server console displayed when I first pressed "Done" with the sign:

-------------------------------------------------------------------------------------------------------------

[23:45:24] [Server thread/ERROR]: Could not pass event ChunkUnloadEvent to Train_Carts v1.12-v1
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:298) ~[craftbukkit.jar:git-Bukkit-9a1fc1e]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[craftbukkit.jar:git-Bukkit-9a1fc1e]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:498) [craftbukkit.jar:git-Bukkit-9a1fc1e]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:483) [craftbukkit.jar:git-Bukkit-9a1fc1e]
	at net.minecraft.server.v1_12_R1.ChunkProviderServer.unloadChunk(ChunkProviderServer.java:276) [craftbukkit.jar:git-Bukkit-9a1fc1e]
	at net.minecraft.server.v1_12_R1.ChunkProviderServer.unloadChunks(ChunkProviderServer.java:257) [craftbukkit.jar:git-Bukkit-9a1fc1e]
	at net.minecraft.server.v1_12_R1.WorldServer.doTick(WorldServer.java:290) [craftbukkit.jar:git-Bukkit-9a1fc1e]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739) [craftbukkit.jar:git-Bukkit-9a1fc1e]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:370) [craftbukkit.jar:git-Bukkit-9a1fc1e]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:650) [craftbukkit.jar:git-Bukkit-9a1fc1e]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:554) [craftbukkit.jar:git-Bukkit-9a1fc1e]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_60]
Caused by: java.lang.UnsupportedOperationException: Field !!UNKNOWN!! is not available
	at com.bergerkiller.mountiplex.reflection.declarations.Template$AbstractField$1.fail(Template.java:491) ~[?:?]
	at com.bergerkiller.mountiplex.reflection.declarations.Template$AbstractField$1.get(Template.java:494) ~[?:?]
	at com.bergerkiller.bukkit.common.utils.ChunkUtil.getEntities(ChunkUtil.java:175) ~[?:?]
	at com.bergerkiller.bukkit.tc.TCListener.onChunkUnloadLow(TCListener.java:109) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor29.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_60]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_60]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:296) ~[craftbukkit.jar:git-Bukkit-9a1fc1e]
	... 11 more

-------------------------------------------------------------------------------------------------------------

Could you please help me with this problem? Thanks so much!

**Comment by bergerkiller** [comment]
Have you tried the latest official release of BKCommonLib? (1.12.2-v1 on Spigot) The error leads to a fairly old bugfix for CraftBukkit servers in BKC. If that does not fix it, what server are you running on?

BKCommonLib is back-version compatible.

**Comment by MartianMH** [comment]
That fixed it! Thanks so much. Quick question though, when I use the train spawning sign with the velocity, train immediately goes a specific direction. How do I get it to travel the opposite way?

**Comment by bergerkiller** [comment]
You can orient the sign in a certain way (sign posts), or put it on the first line like this:

```
[train:left]
spawn 0.3
mmm
```
However now you mention it, I need to look into if this still worked. When I tried this with the new upside-down rails Im working on it didnt work. If it doesnt work for you with normal rails you can let me know.
