### ISSUE TITLE
Plugin not loading (MC 1.7.10)

### ISSUE THREAD

**Issue by Hugoland** [bergerhealer/TrainCarts#182]
Hello, my 1.7.10 Minecraft server isn't able to start the plugin.
##### Spigot version: cauldron-1.7.10-1.1207.01.198-server

<hr>

#### Problem or bug:
`[12:42:19] [Server thread/INFO]: [Train_Carts] Enabling Train_Carts v1.73.0
[12:42:19] [Server thread/ERROR]: Error occurred while enabling Train_Carts v1.73.0 (Is it up to date?)
java.lang.NullPointerException
	at com.bergerkiller.bukkit.common.PluginBase.getPermission(PluginBase.java:150) ~[?:?]
	at com.bergerkiller.bukkit.common.PluginBase.loadPermission(PluginBase.java:321) ~[?:?]
	at com.bergerkiller.bukkit.common.PluginBase.loadPermission(PluginBase.java:309) ~[?:?]
	at com.bergerkiller.bukkit.common.PluginBase.loadPermission(PluginBase.java:277) ~[?:?]
	at com.bergerkiller.bukkit.common.PluginBase.loadPermissions(PluginBase.java:266) ~[?:?]
	at com.bergerkiller.bukkit.tc.TrainCarts.permissions(TrainCarts.java:573) ~[?:?]
	at com.bergerkiller.bukkit.common.PluginBase.onEnable(PluginBase.java:726) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) ~[JavaPlugin.class:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:368) [JavaPluginLoader.class:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410) [SimplePluginManager.class:?]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:415) [CraftServer.class:?]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:349) [CraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71243_i(MinecraftServer.java:500) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:474) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:434) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:329) [lt.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:620) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]`

Thanks in advance for your help.

**Comment by bergerkiller** [comment]
I cant really provide support for such an old build of traincarts. I'll try and see if 1.7.10 support in BKCommonLib is feasible though, I have time atm.

**Comment by bergerkiller** [comment]
I got bad news. I can't even find a place where the source code is available for MC 1.7.10, it only goes as far back as 1.8. I could maybe figure something out by decompiling the 1.7.10 craftbukkit jar, but I worry this isnt going to be easily solved.

**Comment by bergerkiller** [comment]
I did a diff between 1.8.8 and 1.8 and it doesnt look too bad. I'll attempt to add support for versions down to 1.8 first, then look into 1.7.10. This will minimize the problems downdating.

**Comment by ApocalypsjeNL** [comment]
1.7.10 source is fully gone because of the DCMA takedown. It was supposed to be here https://github.com/Bukkit/Craftbukkit, https://github.com/SpigotMC/Spigot

**Comment by bergerkiller** [comment]
Youre right, I was aware of it, just hoped that the Spigot repo would have the pre-1.8 builds too. I was wrong. What Ill probably end up doing is compare the 1.8 and 1.7.10 CraftBukkit jar decompiled source and attempt to make it compatible that way.

**Comment by Hugoland** [comment]
Thank you, I appreciate your help 👍

**Comment by bergerkiller** [comment]
The answer is unfortunately a simple no. [Besides the very large amount of field and method changes](https://pastebin.com/gDnaNGuY) between 1.7.10 and 1.8, which I could actually deal with, there is a major roadblock that I can not fix. BlockData.

Since 1.8 Minecraft uses IBlockData to represent blocks internally. In 1.7.10, this feature is completely absent, and as a result a very large swath of API functionality ends up breaking. IBlockData is needed for pretty much every method that interacts with blocks, and for TrainCarts that means nothing works anymore on 1.7.10.

I considered 'faking' IBlockData by creating a proxy behaving similarly, but a cursory glance shows that would require re-implementing a lot of block state logic from scratch. 1.8 added a lot of important API's for blocks that I find missing now. An even bigger problem is that methods, like doSomething(IBlockData data) changed signature entirely, to something like doSomething(int typeId, int data).

An even bigger reason to not support 1.7.10 is simply that, with the upcoming 1.13 update, type Id and block data values are going out the door entirely. By supporting 1.7.10 I'd be keeping around a legacy that is incredibly hard to maintain in future versions.

Sorry for the disappointing news, I really do recommend updating the plugins you need to at least 1.8, which I've added support for yesterday and today.

**Comment by bergerkiller** [comment]
As a compromise, I can attempt to fix at least the very old release of BKCommonLib and TrainCarts so the plugin enables. The error posted was fixed a very long time ago, it shouldn't be hard to re-apply that fix if I can find the source.

Of course, none of the newest fixes and features can be implemented then.

**Comment by bergerkiller** [comment]
Can you verify whether these jars work for MC 1.7.10? A quick test on the server with 1.7.10 shows that it seems to work fine.

https://www.dropbox.com/s/4kdjuwnsx352nkb/BKCommonLib-1.59-SNAPSHOT.jar?dl=0
https://www.dropbox.com/s/c30fyd03nscyocy/TrainCarts-1.73.1-SNAPSHOT.jar?dl=0

**Comment by Hugoland** [comment]
Thanks for the files.

I have the same logs even though the /pl command shows all plugins in green like if they loaded correctly.


[22:08:30] [Server thread/INFO]: [Train_Carts] Enabling Train_Carts v1.73.1-SNAPSHOT
[22:08:31] [Server thread/ERROR]: Error occurred while enabling Train_Carts v1.73.1-SNAPSHOT (Is it up to date?)
java.lang.NullPointerException
	at com.bergerkiller.bukkit.common.PluginBase.getPermission(PluginBase.java:150) ~[?:?]
	at com.bergerkiller.bukkit.common.PluginBase.loadPermission(PluginBase.java:321) ~[?:?]
	at com.bergerkiller.bukkit.common.PluginBase.loadPermission(PluginBase.java:309) ~[?:?]
	at com.bergerkiller.bukkit.common.PluginBase.loadPermission(PluginBase.java:277) ~[?:?]
	at com.bergerkiller.bukkit.common.PluginBase.loadPermissions(PluginBase.java:266) ~[?:?]
	at com.bergerkiller.bukkit.tc.TrainCarts.permissions(TrainCarts.java:573) ~[?:?]
	at com.bergerkiller.bukkit.common.PluginBase.onEnable(PluginBase.java:726) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) ~[JavaPlugin.class:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:368) [JavaPluginLoader.class:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410) [SimplePluginManager.class:?]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:415) [CraftServer.class:?]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:349) [CraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71243_i(MinecraftServer.java:500) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:474) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:434) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:329) [lt.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:620) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]

**Comment by bergerkiller** [comment]
I suspected so, because I couldnt reproduce the error. Is this on CraftBukkit or Spigot 1.7.10? Ill try to fix this ina bit

**Comment by bergerkiller** [comment]
Do you see anything in the logs at startup for BKCommonLib? This error seems to indicate that BKCommonLib failed to enable.

**Comment by Hugoland** [comment]
Like I wrote in the initial issue, I'm using cauldronbukkit-1.7.10-1.1207.01.198
My ProtocolLib is ProtocolLib-3.4.0
Yep you're right, I did not notice that BKCommonLib didn't load : 
```
[22:08:14] [Server thread/INFO]: [BKCommonLib] Loading BKCommonLib v1.59-SNAPSHOT
[22:08:14] [Server thread/WARN]: java.lang.Exception: Method 'getVersion()' does not exist in class file net.minecraft.server.dedicated.DedicatedServer
[22:08:14] [Server thread/WARN]: 	at com.bergerkiller.bukkit.common.internal.CommonPlugin.handleReflectionMissing(CommonPlugin.java:102)
[22:08:14] [Server thread/WARN]: 	at com.bergerkiller.bukkit.common.reflection.SafeMethod.load(SafeMethod.java:87)
[22:08:14] [Server thread/WARN]: 	at com.bergerkiller.bukkit.common.reflection.SafeMethod.<init>(SafeMethod.java:54)
[22:08:14] [Server thread/WARN]: 	at com.bergerkiller.bukkit.common.server.CraftBukkitServer.postInit(CraftBukkitServer.java:65)
[22:08:14] [Server thread/WARN]: 	at com.bergerkiller.bukkit.common.Common.<clinit>(Common.java:87)
[22:08:14] [Server thread/WARN]: 	at com.bergerkiller.bukkit.common.internal.CommonPlugin.onLoad(CommonPlugin.java:309)
[22:08:14] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugins(CraftServer.java:325)
[22:08:14] [Server thread/WARN]: 	at net.minecraft.world.storage.SaveHandler.initBukkitData(SaveHandler.java:458)
[22:08:14] [Server thread/WARN]: 	at net.minecraft.world.storage.SaveHandler.func_75757_d(SaveHandler.java:136)
[22:08:14] [Server thread/WARN]: 	at net.minecraft.world.World.<init>(World.java:350)
[22:08:14] [Server thread/WARN]: 	at net.minecraft.world.WorldServer.<init>(WorldServer.java:153)
[22:08:14] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:356)
[22:08:14] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:329)
[22:08:14] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:620)
[22:08:14] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[22:08:14] [Server thread/ERROR]: An error occurred trying to initialize class 'com.bergerkiller.bukkit.common.conversion.type.ObjectArrayConverter': initializing BKCommonLib v1.59-SNAPSHOT (Is it up to date?)
java.lang.RuntimeException: An error occurred trying to initialize class 'com.bergerkiller.bukkit.common.conversion.type.ObjectArrayConverter':
	at com.bergerkiller.bukkit.common.Common.loadClasses(Common.java:113) ~[?:?]
	at com.bergerkiller.bukkit.common.internal.CommonClasses.loadCommon(CommonClasses.java:59) ~[?:?]
	at com.bergerkiller.bukkit.common.internal.CommonClasses.loadConverter(CommonClasses.java:38) ~[?:?]
	at com.bergerkiller.bukkit.common.internal.CommonClasses.init(CommonClasses.java:13) ~[?:?]
	at com.bergerkiller.bukkit.common.internal.CommonPlugin.onLoad(CommonPlugin.java:313) ~[?:?]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugins(CraftServer.java:325) [CraftServer.class:?]
	at net.minecraft.world.storage.SaveHandler.initBukkitData(SaveHandler.java:458) [ayq.class:?]
	at net.minecraft.world.storage.SaveHandler.func_75757_d(SaveHandler.java:136) [ayq.class:?]
	at net.minecraft.world.World.<init>(World.java:350) [ahb.class:?]
	at net.minecraft.world.WorldServer.<init>(WorldServer.java:153) [mt.class:?]
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:356) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:329) [lt.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:620) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
Caused by: java.lang.ExceptionInInitializerError
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_144]
	at java.lang.Class.forName(Class.java:264) ~[?:1.8.0_144]
	at com.bergerkiller.bukkit.common.Common.loadClasses(Common.java:111) ~[?:?]
	... 13 more
Caused by: java.lang.NullPointerException
	at com.bergerkiller.bukkit.common.utils.LogicUtil.getArrayType(LogicUtil.java:293) ~[?:?]
	at com.bergerkiller.bukkit.common.conversion.type.ObjectArrayConverter.<init>(ObjectArrayConverter.java:26) ~[?:?]
	at com.bergerkiller.bukkit.common.conversion.type.ObjectArrayConverter.<clinit>(ObjectArrayConverter.java:22) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_144]
	at java.lang.Class.forName(Class.java:264) ~[?:1.8.0_144]
	at com.bergerkiller.bukkit.common.Common.loadClasses(Common.java:111) ~[?:?]
	... 13 more
[22:08:15] [Server thread/INFO]: [BKCommonLib] Enabling BKCommonLib v1.59-SNAPSHOT
[22:08:15] [Server thread/ERROR]: Error occurred while enabling BKCommonLib v1.59-SNAPSHOT (Is it up to date?)
java.lang.NoClassDefFoundError: Could not initialize class com.bergerkiller.bukkit.common.conversion.type.ObjectArrayConverter
	at com.bergerkiller.bukkit.common.conversion.type.ConversionTypes.<clinit>(ConversionTypes.java:51) ~[?:?]
	at com.bergerkiller.bukkit.common.utils.ParseUtil.convert(ParseUtil.java:538) ~[?:?]
	at com.bergerkiller.bukkit.common.config.ConfigurationNode.get(ConfigurationNode.java:525) ~[?:?]
	at com.bergerkiller.bukkit.common.config.ConfigurationNode.get(ConfigurationNode.java:495) ~[?:?]
	at com.bergerkiller.bukkit.common.PluginBase.setPermissions(PluginBase.java:601) ~[?:?]
	at com.bergerkiller.bukkit.common.PluginBase.onEnable(PluginBase.java:728) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) ~[JavaPlugin.class:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:368) [JavaPluginLoader.class:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410) [SimplePluginManager.class:?]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:415) [CraftServer.class:?]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:349) [CraftServer.class:?]
	at net.minecraft.world.storage.SaveHandler.initBukkitData(SaveHandler.java:459) [ayq.class:?]
	at net.minecraft.world.storage.SaveHandler.func_75757_d(SaveHandler.java:136) [ayq.class:?]
	at net.minecraft.world.World.<init>(World.java:350) [ahb.class:?]
	at net.minecraft.world.WorldServer.<init>(WorldServer.java:153) [mt.class:?]
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:356) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:329) [lt.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:620) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
```
By the way, happy new year !

**Comment by bergerkiller** [comment]
Oh Im sorry, I missed that you put it in the initial issue ticket, my bad. Thank you for the error, a quick inspection seems to indicate its tripping over some server differences. I'll be downloading cauldronbukkit and see what I can do about it tomorrow.

Happy new year back at you :)

**Comment by bergerkiller** [comment]
Well this is awkward. Looks like I just cant seem to get the server launched. I had issues before but that was because I was on java 8, but on JRE java 7 it doesnt work either. This is what the log gives:
```
[04:30:32] [main/ERROR]: Unable to launch
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_80]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_80]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_80]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_80]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:134) [launchwrapper-1.9.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.9.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_80]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_80]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_80]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_80]
	at cpw.mods.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:43) [cauldron-1.7.10-1.1207.01.198-server.jar:git-Cauldron-MCPC-Plus-1.7.10-1.1207.01.198]
	at cpw.mods.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:12) [cauldron-1.7.10-1.1207.01.198-server.jar:git-Cauldron-MCPC-Plus-1.7.10-1.1207.01.198]
Caused by: java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/v1_7_R4/potion/CraftPotionEffectType
	at net.minecraft.potion.Potion.<init>(Potion.java:87) ~[rv.class:?]
	at net.minecraft.potion.Potion.<clinit>(Potion.java:30) ~[rv.class:?]
	at net.minecraft.potion.PotionHelper.<clinit>(SourceFile:82) ~[aen.class:?]
	at net.minecraft.item.Item.func_150900_l(Item.java:128) ~[adb.class:?]
	at net.minecraft.init.Bootstrap.func_151354_b(Bootstrap.java:716) ~[kl.class:?]
	at net.minecraft.server.MinecraftServer.main(MinecraftServer.java:1579) ~[MinecraftServer.class:?]
	... 12 more
Caused by: java.lang.ClassNotFoundException: org.bukkit.craftbukkit.v1_7_R4.potion.CraftPotionEffectType
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:188) ~[launchwrapper-1.9.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_80]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_80]
	at net.minecraft.potion.Potion.<init>(Potion.java:87) ~[rv.class:?]
	at net.minecraft.potion.Potion.<clinit>(Potion.java:30) ~[rv.class:?]
	at net.minecraft.potion.PotionHelper.<clinit>(SourceFile:82) ~[aen.class:?]
	at net.minecraft.item.Item.func_150900_l(Item.java:128) ~[adb.class:?]
	at net.minecraft.init.Bootstrap.func_151354_b(Bootstrap.java:716) ~[kl.class:?]
	at net.minecraft.server.MinecraftServer.main(MinecraftServer.java:1579) ~[MinecraftServer.class:?]
	... 12 more
Caused by: java.lang.NullPointerException
	at org.objectweb.asm.ClassReader.<init>(Unknown Source) ~[asm-all-4.1.jar:4.1]
	at cpw.mods.fml.common.asm.transformers.TerminalTransformer.transform(TerminalTransformer.java:14) ~[cauldron-1.7.10-1.1207.01.198-server.jar:git-Cauldron-MCPC-Plus-1.7.10-1.1207.01.198]
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:276) ~[launchwrapper-1.9.jar:?]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:174) ~[launchwrapper-1.9.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_80]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_80]
	at net.minecraft.potion.Potion.<init>(Potion.java:87) ~[rv.class:?]
	at net.minecraft.potion.Potion.<clinit>(Potion.java:30) ~[rv.class:?]
	at net.minecraft.potion.PotionHelper.<clinit>(SourceFile:82) ~[aen.class:?]
	at net.minecraft.item.Item.func_150900_l(Item.java:128) ~[adb.class:?]
	at net.minecraft.init.Bootstrap.func_151354_b(Bootstrap.java:716) ~[kl.class:?]
	at net.minecraft.server.MinecraftServer.main(MinecraftServer.java:1579) ~[MinecraftServer.class:?]
	... 12 more
```
I can probably figure it out tomorrow with some online searching. If you have any hints as to what may be wrong though, it would help me a lot.

**Comment by bergerkiller** [comment]
Got it! cauldronbukkit jar was missing :)

**Comment by bergerkiller** [comment]
Ive fixed a whole lot of stuff and TrainCarts works now on MCPC-Plus 1.7.10. Some stuff was broken/unsupported. The server wasn't even detected because Bukkit.getServer().getVersion() returned null for some reason. I've added some workaround.

All download links are available here, and I will keep them updated:
https://github.com/bergerkiller/TrainCarts

**Comment by Hugoland** [comment]
So I installed both updated files BKCommonLib & TrainCarts from your link, and it seems to work!
Thank you for everything you’ve done! Your plugin is very useful.
