### ISSUE TITLE
problem after updating plugins

### ISSUE THREAD

**Issue by djbenbe** [bergerhealer/TrainCarts#195]
##### Spigot version:1.12.2

<hr>

#### Problem or bug: problem

hello,

I have this problem after updating the plugins.

thank you in advance.

[15:01:09] [Server thread/ERROR]: [Train_Carts] Failed to perform physics on train 'train37' at worldbak_123_202_-943:
[15:01:09] [Server thread/ERROR]: [Train_Carts] Encountered a critical error
[15:01:09] [Server thread/ERROR]: [Train_Carts] Please, check for an updated version of Train_Carts before reporting this bug!
[15:01:09] [Server thread/ERROR]: [BKCommonLib] java.lang.AbstractMethodError
[15:01:09] [Server thread/ERROR]: [BKCommonLib]   at com.bergerkiller.bukkit.tc.controller.components.RailTrackerMember.getRailLogic(RailTrackerMember.java:120)
[15:01:09] [Server thread/ERROR]: [BKCommonLib]   at com.bergerkiller.bukkit.tc.controller.MinecartMember.getRailLogic(MinecartMember.java:653)
[15:01:09] [Server thread/ERROR]: [BKCommonLib]   at com.bergerkiller.bukkit.tc.controller.MinecartMember.updateDirection(MinecartMember.java:808)
[15:01:09] [Server thread/ERROR]: [BKCommonLib]   at com.bergerkiller.bukkit.tc.controller.MinecartGroup.updateDirection(MinecartGroup.java:609)
[15:01:09] [Server thread/ERROR]: [BKCommonLib]   at com.bergerkiller.bukkit.tc.controller.MinecartGroup.doPhysics_step(MinecartGroup.java:1207)
[15:01:09] [Server thread/ERROR]: [BKCommonLib]   at com.bergerkiller.bukkit.tc.controller.MinecartGroup.doPhysics(MinecartGroup.java:1148)
[15:01:09] [Server thread/ERROR]: [BKCommonLib]   at com.bergerkiller.bukkit.tc.controller.MinecartMember.onTick(MinecartMember.java:1575)
[15:01:09] [Server thread/ERROR]: [BKCommonLib]   at com.bergerkiller.bukkit.common.internal.hooks.EntityHook.onTick(EntityHook.java:114)
[15:01:09] [Server thread/ERROR]: [BKCommonLib]   at com.bergerkiller.mountiplex.reflection.util.fast.GeneratedInvoker$mplgen29d29de9.invokeVA(Unknown Source)
[15:01:09] [Server thread/ERROR]: [BKCommonLib]   at com.bergerkiller.mountiplex.reflection.util.FastMethod.invokeVA(FastMethod.java:112)
[15:01:09] [Server thread/ERROR]: [BKCommonLib]   at com.bergerkiller.mountiplex.reflection.ClassInterceptor$CallbackMethodInterceptor.intercept(ClassInterceptor.java:637)
[15:01:09] [Server thread/ERROR]: [BKCommonLib]   at net.minecraft.server.v1_12_R1.EntityMinecartRideable$$EnhancerByCGLIB$$b951acc8.B_(<generated>)
[15:01:09] [Server thread/ERROR]: [BKCommonLib]   at net.minecraft.server.v1_12_R1.World.entityJoinedWorld(World.java:1631)
[15:01:09] [Server thread/ERROR]: [BKCommonLib]   at net.minecraft.server.v1_12_R1.World.h(World.java:1601)
[15:01:09] [Server thread/ERROR]: [BKCommonLib]   at net.minecraft.server.v1_12_R1.World.tickEntities(World.java:1435)
[15:01:09] [Server thread/ERROR]: [BKCommonLib]   at net.minecraft.server.v1_12_R1.WorldServer.tickEntities(WorldServer.java:665)
[15:01:09] [Server thread/ERROR]: [BKCommonLib]   at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:817)
[15:01:09] [Server thread/ERROR]: [BKCommonLib]   at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
[15:01:09] [Server thread/ERROR]: [BKCommonLib]   at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
[15:01:09] [Server thread/ERROR]: [BKCommonLib]   at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
[15:01:09] [Server thread/ERROR]: [BKCommonLib]   at java.lang.Thread.run(Unknown Source)

**Comment by bergerkiller** [comment]
Remove TCFloatRail, its not currently supported anymore. That it errors out like this without handling it gracefully is a bug, though. It should detect it and disable the rail type instead.

**Comment by djbenbe** [comment]
badger because I use this rather than rails but is there something that it replaces?

**Comment by ApocalypsjeNL** [comment]
`TCHangrail can support all the things float rail did in the past.`

Looks like TCHangrail does? 😜

**Comment by djbenbe** [comment]
TC HangRail no longer works with me

**Comment by bergerkiller** [comment]
The latest version doesnt work? https://www.spigotmc.org/resources/tc-hangrail.39627/update?update=208084

**Comment by djbenbe** [comment]
tc actionblock also works no more than?

**Comment by bergerkiller** [comment]
I havent updated action blocks in forever, so I dont know for sure. It doesnt use custom rails though so it might be fine? I havent tested it myself.

**Comment by djbenbe** [comment]
I now have another problem
I have a part of my log file here



[21:23:12] [Server thread/INFO]: [Train_Carts] Enabling Train_Carts v1.12.2-v2
[21:23:14] [Server thread/ERROR]: [Train_Carts] An error occurred while enabling, the plugin will be disabled:
[21:23:14] [Server thread/ERROR]: [BKCommonLib] java.lang.NullPointerException
[21:23:14] [Server thread/ERROR]: [BKCommonLib]   at com.bergerkiller.bukkit.common.map.archive.MapResourcePackDownloadedArchive.load(MapResourcePackDownloadedArchive.java:76)
[21:23:14] [Server thread/ERROR]: [BKCommonLib]   at com.bergerkiller.bukkit.common.map.archive.MapResourcePackAutoArchive.load(MapResourcePackAutoArchive.java:42)
[21:23:14] [Server thread/ERROR]: [BKCommonLib]   at com.bergerkiller.bukkit.common.map.MapResourcePack.handleLoad(MapResourcePack.java:193)
[21:23:14] [Server thread/ERROR]: [BKCommonLib]   at com.bergerkiller.bukkit.common.map.MapResourcePack.load(MapResourcePack.java:179)
[21:23:14] [Server thread/ERROR]: [BKCommonLib]   at com.bergerkiller.bukkit.tc.TrainCarts.enable(TrainCarts.java:273)
[21:23:14] [Server thread/ERROR]: [BKCommonLib]   at com.bergerkiller.bukkit.common.PluginBase.onEnable(PluginBase.java:795)
[21:23:14] [Server thread/ERROR]: [BKCommonLib]   at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[21:23:14] [Server thread/ERROR]: [BKCommonLib]   at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
[21:23:14] [Server thread/ERROR]: [BKCommonLib]   at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403)
[21:23:14] [Server thread/ERROR]: [BKCommonLib]   at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:381)
[21:23:14] [Server thread/ERROR]: [BKCommonLib]   at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:330)
[21:23:14] [Server thread/ERROR]: [BKCommonLib]   at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422)
[21:23:14] [Server thread/ERROR]: [BKCommonLib]   at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383)
[21:23:14] [Server thread/ERROR]: [BKCommonLib]   at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338)
[21:23:14] [Server thread/ERROR]: [BKCommonLib]   at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272)
[21:23:14] [Server thread/ERROR]: [BKCommonLib]   at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545)
[21:23:14] [Server thread/ERROR]: [BKCommonLib]   at java.lang.Thread.run(Unknown Source)
[21:23:14] [Server thread/INFO]: [Train_Carts] Disabling Train_Carts v1.12.2-v2
[21:23:14] [Server thread/INFO]: [BKCommonLib] Train_Carts disabled!
[21:23:15] [Server thread/INFO]: [TCActionBlocks] Enabling TCActionBlocks v1.3
[21:23:15] [Server thread/ERROR]: [TCActionBlocks] Plugin TCActionBlocks v1.3 has failed to register events for class net.timstans.actionblocks.ActionBlocksListener because com/bergerkiller/bukkit/tc/events/MemberBlockChangeEvent does not exist.
[21:23:15] [Server thread/INFO]: [TCHangRail] Enabling TCHangRail v1.12.2-v3
[21:23:15] [Server thread/ERROR]: Error occurred while enabling TCHangRail v1.12.2-v3 (Is it up to date?)
java.lang.NoClassDefFoundError: com/bergerkiller/bukkit/tc/rails/logic/RailLogic
	at com.bergerkiller.bukkit.hangrail.TCHangRail.onEnable(TCHangRail.java:51) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-1.12.2.jar:git-Spigot-4bd94dc-dac2a4a]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot-1.12.2.jar:git-Spigot-4bd94dc-dac2a4a]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot-1.12.2.jar:git-Spigot-4bd94dc-dac2a4a]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:381) [spigot-1.12.2.jar:git-Spigot-4bd94dc-dac2a4a]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:330) [spigot-1.12.2.jar:git-Spigot-4bd94dc-dac2a4a]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422) [spigot-1.12.2.jar:git-Spigot-4bd94dc-dac2a4a]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383) [spigot-1.12.2.jar:git-Spigot-4bd94dc-dac2a4a]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338) [spigot-1.12.2.jar:git-Spigot-4bd94dc-dac2a4a]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot-1.12.2.jar:git-Spigot-4bd94dc-dac2a4a]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [spigot-1.12.2.jar:git-Spigot-4bd94dc-dac2a4a]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]
Caused by: java.lang.ClassNotFoundException: com.bergerkiller.bukkit.tc.rails.logic.RailLogic
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_161]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:152) ~[spigot-1.12.2.jar:git-Spigot-4bd94dc-dac2a4a]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[spigot-1.12.2.jar:git-Spigot-4bd94dc-dac2a4a]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_161]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_161]
	... 12 more
[21:23:15] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
[21:23:15] [Server thread/INFO]: Done (27.576s)! For help, type "help" or "?"
[21:23:17] [Craft Scheduler Thread - 6/INFO]: [PlugMan] No update was found.

**Comment by bergerkiller** [comment]
Dont know what happened, but its unable to create and/or read the resource pack index.json. Try deleting the BKCommonLib config directory from /plugins and starting again.

**Comment by djbenbe** [comment]
yesterday I solved this problem and removed everything from traincart + BKCommonLib because only BKCommonLib removal did not work.

**Comment by bergerkiller** [comment]
Im happy for you it got solved, though I'll leave this issue ticket up in case it pops up again in the future.

**Comment by jimmietjuh** [comment]
I have this: [18:29:21 ERROR]: [BKCommonLib] [Debug] Failed to convert net.minecraft.server.v1_9_R1.TileEntitySign to CraftBlockState  -  com.bergerkiller.bukkit.common.conversion.type.BlockStateConversion.tileEntityToBlockState(BlockStateConversion.java:199). what can i do? because the launch signs dont work they send them to random directions

**Comment by bergerkiller** [comment]
Id first try and see if the new dev build of BKCommonLib fixes it. Might be related to an incompatibility with paperspigot or a past version of MC. https://ci.mg-dev.eu/job/BKCommonLib/386/
