### ISSUE TITLE
It can't work @TrainCarts-1.12.2-v2 & BKCommonLib-1.12.2-v4

### ISSUE THREAD

**Issue by Slender2018** [bergerhealer/TrainCarts#197]
```
[21:07:31] [Server thread/INFO]: Starting minecraft server version 1.12.2
[21:07:31] [Server thread/INFO]: Loading properties
[21:07:31] [Server thread/INFO]: Default game type: SURVIVAL
[21:07:32] [Server thread/INFO]: This server is running Paper version git-Paper-1275 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
[21:07:32] [Server thread/INFO]: Debug logging is disabled
[21:07:32] [Server thread/INFO]: Using 4 threads for Netty based IO
[21:07:32] [Server thread/INFO]: Server Ping Player Sample Count: 12
[21:07:32] [Server thread/INFO]: Generating keypair
[21:07:32] [Server thread/INFO]: Starting Minecraft server on *:25560
[21:07:32] [Server thread/INFO]: Using default channel type
[21:07:32] [Server thread/INFO]: Set PluginClassLoader as parallel capable
[21:07:32] [Server thread/INFO]: [AsyncWorldEditInjector] Loading AsyncWorldEditInjector v3.4.9
[21:07:32] [Server thread/INFO]: [AsyncWorldEdit] Loading AsyncWorldEdit v3.4.9
[21:07:32] [Server thread/INFO]: [VoxelSniper] Loading VoxelSniper v5.171.0-SNAPSHOT
[21:07:32] [Server thread/INFO]: [BKCommonLib] Loading BKCommonLib v1.12.2-v4
[21:07:34] [Server thread/INFO]: [WorldEdit] Loading WorldEdit v6.1.8-SNAPSHOT;cd4729f
[21:07:34] [Server thread/INFO]: [Train_Carts] Loading Train_Carts v1.12.2-v2
[21:07:34] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
[21:07:34] [Server thread/INFO]: [AsyncWorldEditInjector] Enabling AsyncWorldEditInjector v3.4.9
[21:07:34] [Server thread/INFO]: [AsyncWorldEditInjector] Injector platform set to: InjectorBukkit
[21:07:34] [Server thread/INFO]: [AsyncWorldEditInjector] Injecting WorldEdit classes...
[21:07:34] [Server thread/INFO]: [AsyncWorldEditInjector] Class com.sk89q.worldedit.EditSession injected.
[21:07:34] [Server thread/INFO]: [AsyncWorldEditInjector] Class com.sk89q.worldedit.function.operation.Operations injected.
[21:07:34] [Server thread/INFO]: [AsyncWorldEditInjector] Class com.sk89q.worldedit.function.operation.ForwardExtentCopy injected.
[21:07:34] [Server thread/INFO]: [AsyncWorldEditInjector] Class com.sk89q.worldedit.extent.clipboard.BlockArrayClipboard injected.
[21:07:34] [Server thread/INFO]: [AsyncWorldEditInjector] Class com.sk89q.worldedit.command.FlattenedClipboardTransform injected.
[21:07:34] [Server thread/INFO]: [AsyncWorldEditInjector] Class com.sk89q.worldedit.extent.clipboard.io.ClipboardFormat injected.
[21:07:34] [Server thread/INFO]: [AsyncWorldEditInjector] Enabled
[21:07:34] [Server thread/INFO]: [AsyncWorldEdit] Enabling AsyncWorldEdit v3.4.9
[21:07:34] [Server thread/INFO]: [AsyncWorldEdit] Plugin installed
[21:07:35] [Server thread/INFO]: [AsyncWorldEdit] Platform set to Bukkit API
[21:07:35] [Server thread/INFO]: [AsyncWorldEdit] No matching adapter found for Bukkit.v1_12_R1, DirectChunkAPI disabled
[21:07:35] [Server thread/INFO]: [AsyncWorldEdit] PlotMeFix set to class org.primesoft.asyncworldedit.plotme.NullFix.
[21:07:35] [Server thread/INFO]: [AsyncWorldEditInjector] New class factory set to: org.primesoft.asyncworldedit.injector.async.AsyncClassFactory
[21:07:35] [Server thread/INFO]: [AsyncWorldEdit] Enabled
[21:07:35] [Server thread/INFO]: [BKCommonLib] Enabling BKCommonLib v1.12.2-v4
[21:07:35] [Server thread/INFO]: [BKCommonLib.Configuration] [BKCommonLib] [Configuration] File 'plugins\BKCommonLib\Localization.yml' has been generated
[21:07:35] [Server thread/INFO]: [BKCommonLib] BKCommonLib is running on Paper(Spigot) (git-Paper-1275) : v1_12_R1 (Minecraft 1.12.2)
[21:07:35] [Server thread/INFO]: [BKCommonLib.Network] [BKCommonLib] [Network] Now using a PlayerConnection hook to provide Packet Listener and Monitor support
[21:07:35] [Thread-5/INFO]: [AsyncWorldEdit] You have an old version of the plugin. Your version: 3.4.9, available version: 3.4.11
[21:07:36] [Server thread/INFO]: [BKCommonLib] v1_1_R1 1+1+1 = 3, Half life 3 confirmed?
[21:07:36] [Server thread/INFO]: [BKCommonLib] BKCommonLib version 1.12.2-v4 (build: 349) enabled! (0.828s)
[21:07:36] [Server thread/INFO]: **** Beginning UUID conversion, this may take A LONG time ****
[21:07:36] [Server thread/INFO]: Preparing level "world"
[21:07:36] [Server thread/INFO]: -------- World Settings For [world] --------
[21:07:36] [Server thread/INFO]: View Distance: 5
[21:07:36] [Server thread/INFO]: Arrow Despawn Rate: 1200
[21:07:36] [Server thread/INFO]: Item Merge Radius: 3.5
[21:07:36] [Server thread/INFO]: Item Despawn Rate: 6000
[21:07:36] [Server thread/INFO]: Experience Merge Radius: 6.0
[21:07:36] [Server thread/INFO]: Zombie Aggressive Towards Villager: true
[21:07:36] [Server thread/INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[21:07:36] [Server thread/INFO]: Nerfing mobs spawned from spawners: false
[21:07:36] [Server thread/INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[21:07:36] [Server thread/INFO]: Random Lighting Updates: false
[21:07:36] [Server thread/INFO]: Entity Activation Range: An 6 / Mo 6 / Mi 2
[21:07:36] [Server thread/INFO]: Hopper Transfer: 24 Hopper Check: 24 Hopper Amount: 3
[21:07:36] [Server thread/INFO]: Cactus Growth Modifier: 100%
[21:07:36] [Server thread/INFO]: Cane Growth Modifier: 100%
[21:07:36] [Server thread/INFO]: Melon Growth Modifier: 100%
[21:07:36] [Server thread/INFO]: Mushroom Growth Modifier: 100%
[21:07:36] [Server thread/INFO]: Pumpkin Growth Modifier: 100%
[21:07:36] [Server thread/INFO]: Sapling Growth Modifier: 100%
[21:07:36] [Server thread/INFO]: Wheat Growth Modifier: 100%
[21:07:36] [Server thread/INFO]: NetherWart Growth Modifier: 100%
[21:07:36] [Server thread/INFO]: Vine Growth Modifier: 100%
[21:07:36] [Server thread/INFO]: Cocoa Growth Modifier: 100%
[21:07:36] [Server thread/INFO]: Mob Spawn Range: 3
[21:07:36] [Server thread/INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[21:07:36] [Server thread/INFO]: Structure Info Saving: true
[21:07:36] [Server thread/INFO]: Max TNT Explosions: 100
[21:07:36] [Server thread/INFO]: Custom Map Seeds:  Village: 10387312 Feature: 14357617 Monument: 10387313 Slime: 987234911
[21:07:36] [Server thread/INFO]: -------- World Settings For [world_nether] --------
[21:07:36] [Server thread/INFO]: View Distance: 5
[21:07:36] [Server thread/INFO]: Arrow Despawn Rate: 1200
[21:07:36] [Server thread/INFO]: Item Merge Radius: 3.5
[21:07:36] [Server thread/INFO]: Item Despawn Rate: 6000
[21:07:36] [Server thread/INFO]: Experience Merge Radius: 6.0
[21:07:36] [Server thread/INFO]: Zombie Aggressive Towards Villager: true
[21:07:36] [Server thread/INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[21:07:36] [Server thread/INFO]: Nerfing mobs spawned from spawners: false
[21:07:36] [Server thread/INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[21:07:36] [Server thread/INFO]: Random Lighting Updates: false
[21:07:36] [Server thread/INFO]: Entity Activation Range: An 6 / Mo 6 / Mi 2
[21:07:36] [Server thread/INFO]: Hopper Transfer: 24 Hopper Check: 24 Hopper Amount: 3
[21:07:36] [Server thread/INFO]: Cactus Growth Modifier: 100%
[21:07:36] [Server thread/INFO]: Cane Growth Modifier: 100%
[21:07:36] [Server thread/INFO]: Melon Growth Modifier: 100%
[21:07:36] [Server thread/INFO]: Mushroom Growth Modifier: 100%
[21:07:36] [Server thread/INFO]: Pumpkin Growth Modifier: 100%
[21:07:36] [Server thread/INFO]: Sapling Growth Modifier: 100%
[21:07:36] [Server thread/INFO]: Wheat Growth Modifier: 100%
[21:07:36] [Server thread/INFO]: NetherWart Growth Modifier: 100%
[21:07:36] [Server thread/INFO]: Vine Growth Modifier: 100%
[21:07:36] [Server thread/INFO]: Cocoa Growth Modifier: 100%
[21:07:36] [Server thread/INFO]: Mob Spawn Range: 3
[21:07:36] [Server thread/INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[21:07:36] [Server thread/INFO]: Structure Info Saving: true
[21:07:36] [Server thread/INFO]: Max TNT Explosions: 100
[21:07:36] [Server thread/INFO]: Custom Map Seeds:  Village: 10387312 Feature: 14357617 Monument: 10387313 Slime: 987234911
[21:07:36] [Server thread/INFO]: -------- World Settings For [world_the_end] --------
[21:07:36] [Server thread/INFO]: View Distance: 5
[21:07:36] [Server thread/INFO]: Arrow Despawn Rate: 1200
[21:07:36] [Server thread/INFO]: Item Merge Radius: 3.5
[21:07:36] [Server thread/INFO]: Item Despawn Rate: 6000
[21:07:36] [Server thread/INFO]: Experience Merge Radius: 6.0
[21:07:36] [Server thread/INFO]: Zombie Aggressive Towards Villager: true
[21:07:36] [Server thread/INFO]: Allow Zombie Pigmen to spawn from portal blocks: true
[21:07:36] [Server thread/INFO]: Nerfing mobs spawned from spawners: false
[21:07:36] [Server thread/INFO]: Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
[21:07:36] [Server thread/INFO]: Random Lighting Updates: false
[21:07:36] [Server thread/INFO]: Entity Activation Range: An 6 / Mo 6 / Mi 2
[21:07:36] [Server thread/INFO]: Hopper Transfer: 24 Hopper Check: 24 Hopper Amount: 3
[21:07:36] [Server thread/INFO]: Cactus Growth Modifier: 100%
[21:07:36] [Server thread/INFO]: Cane Growth Modifier: 100%
[21:07:36] [Server thread/INFO]: Melon Growth Modifier: 100%
[21:07:36] [Server thread/INFO]: Mushroom Growth Modifier: 100%
[21:07:36] [Server thread/INFO]: Pumpkin Growth Modifier: 100%
[21:07:36] [Server thread/INFO]: Sapling Growth Modifier: 100%
[21:07:36] [Server thread/INFO]: Wheat Growth Modifier: 100%
[21:07:36] [Server thread/INFO]: NetherWart Growth Modifier: 100%
[21:07:36] [Server thread/INFO]: Vine Growth Modifier: 100%
[21:07:36] [Server thread/INFO]: Cocoa Growth Modifier: 100%
[21:07:36] [Server thread/INFO]: Mob Spawn Range: 3
[21:07:36] [Server thread/INFO]: Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
[21:07:36] [Server thread/INFO]: Structure Info Saving: true
[21:07:36] [Server thread/INFO]: Max TNT Explosions: 100
[21:07:36] [Server thread/INFO]: Custom Map Seeds:  Village: 10387312 Feature: 14357617 Monument: 10387313 Slime: 987234911
[21:07:36] [Server thread/INFO]: Preparing start region for level 0 (Seed: 3299655016676628966)
[21:07:37] [Server thread/INFO]: Preparing start region for level 1 (Seed: 3299655016676628966)
[21:07:37] [Server thread/INFO]: Preparing start region for level 2 (Seed: 3299655016676628966)
[21:07:37] [Server thread/INFO]: [VoxelSniper] Enabling VoxelSniper v5.171.0-SNAPSHOT
[21:07:37] [Server thread/INFO]: [VoxelSniper] Registered 75 Sniper Brushes with 149 handles.
[21:07:37] [Server thread/INFO]: [VoxelSniper] Registered Sniper Listener.
[21:07:37] [Server thread/INFO]: [WorldEdit] Enabling WorldEdit v6.1.8-SNAPSHOT;cd4729f
[21:07:38] [Server thread/INFO]: WEPIF: Using the Bukkit Permissions API.
[21:07:38] [Server thread/INFO]: [WorldEdit] Using com.sk89q.worldedit.bukkit.adapter.impl.Spigot_v1_12_R2 as the Bukkit adapter
[21:07:38] [Server thread/INFO]: [AsyncWorldEdit] Initializing WorldEdit.
[21:07:38] [Server thread/INFO]: [AsyncWorldEdit] Direct chunk commands...disabled
[21:07:38] [Server thread/INFO]: [Train_Carts] Enabling Train_Carts v1.12.2-v2
[21:07:38] [Server thread/WARN]: [BKCommonLib] [BKCommonLib] To display Minecraft assets (models, textures) on maps, the Minecraft client jar is required
[21:07:38] [Server thread/WARN]: [BKCommonLib] [BKCommonLib] BKCommonLib will now download Minecraft 1.12.2 client jar from Mojang's servers
[21:07:38] [Server thread/WARN]: [BKCommonLib] [BKCommonLib] The file will be installed in: plugins\BKCommonLib\minecraft\1.12.2.jar
[21:07:38] [Server thread/WARN]: [BKCommonLib] [BKCommonLib] By installing this Minecraft client you further indicate agreement to Mojang's EULA.
[21:07:38] [Server thread/WARN]: [BKCommonLib] [BKCommonLib] The EULA can be read here: https://account.mojang.com/documents/minecraft_eula
[21:07:38] [Server thread/WARN]: [BKCommonLib] [BKCommonLib] > Fetching JSON from Mojang servers: https://launchermeta.mojang.com/mc/game/version_manifest.json
[21:07:38] [Server thread/WARN]: [BKCommonLib] [BKCommonLib] > Fetching JSON from Mojang servers: https://launchermeta.mojang.com/mc/game/cf72a57ff499d6d9ade870b2143ee54958bd33ef/1.12.2.json
[21:07:38] [Server thread/WARN]: [BKCommonLib] [BKCommonLib] > Fetching Minecraft Client 1.12.2 from Mojang servers: https://launcher.mojang.com/mc/game/1.12.2/client/0f275bc1547d01fa5f56ba34bdc87d981ee12daf/client.jar
[21:07:39] [Server thread/WARN]: [BKCommonLib] [BKCommonLib] > Downloading Minecraft Client 1.12.2.jar: 10%
[21:07:39] [Server thread/WARN]: [BKCommonLib] [BKCommonLib] > Downloading Minecraft Client 1.12.2.jar: 20%
[21:07:39] [Server thread/WARN]: [BKCommonLib] [BKCommonLib] > Downloading Minecraft Client 1.12.2.jar: 30%
[21:07:39] [Server thread/WARN]: [BKCommonLib] [BKCommonLib] > Downloading Minecraft Client 1.12.2.jar: 40%
[21:07:40] [Server thread/WARN]: [BKCommonLib] [BKCommonLib] > Downloading Minecraft Client 1.12.2.jar: 50%
[21:07:40] [Server thread/WARN]: [BKCommonLib] [BKCommonLib] > Downloading Minecraft Client 1.12.2.jar: 60%
[21:07:40] [Server thread/WARN]: [BKCommonLib] [BKCommonLib] > Downloading Minecraft Client 1.12.2.jar: 70%
[21:07:40] [Server thread/WARN]: [BKCommonLib] [BKCommonLib] > Downloading Minecraft Client 1.12.2.jar: 80%
[21:07:41] [Server thread/WARN]: [BKCommonLib] [BKCommonLib] > Downloading Minecraft Client 1.12.2.jar: 90%
[21:07:41] [Server thread/WARN]: [BKCommonLib] [BKCommonLib] > Downloading Minecraft Client 1.12.2.jar: 100%
[21:07:41] [Server thread/INFO]: [Train_Carts] 0 Trains have been loaded in 0 worlds. (0 Minecarts)
[21:07:41] [Server thread/INFO]: [Train_Carts] 0 detector rail regions loaded covering 0 blocks
[21:07:41] [Server thread/INFO]: [Train_Carts] Restoring trains and loading nearby chunks...
[21:07:41] [Server thread/ERROR]: [BKCommonLib.Debug] [BKCommonLib] [Debug] Failed to convert net.minecraft.server.v1_12_R1.TileEntityChest to CraftBlockState  -  com.bergerkiller.bukkit.common.conversion.type.BlockStateConversion.tileEntityToBlockState(BlockStateConversion.java:229)
java.lang.UnsupportedOperationException: Method not instrumented by the CraftBlock proxy
	at com.bergerkiller.bukkit.common.conversion.type.BlockStateConversion$1.invoke(BlockStateConversion.java:44) ~[?:?]
	at com.bergerkiller.mountiplex.reflection.ClassInterceptor$CallbackMethodInterceptor.intercept(ClassInterceptor.java:641) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.block.CraftBlock$$EnhancerByCGLIB$$543ff3e8.getState0(<generated>) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.block.CraftBlock.getState(CraftBlock.java:272) ~[patched_1.12.2.jar:git-Paper-1275]
	at org.bukkit.craftbukkit.v1_12_R1.block.CraftBlock.getState(CraftBlock.java:266) ~[patched_1.12.2.jar:git-Paper-1275]
	at com.bergerkiller.bukkit.common.conversion.type.BlockStateConversion.tileEntityToBlockState(BlockStateConversion.java:215) [BKCommonLib-1.12.2-v4.jar:?]
	at com.bergerkiller.bukkit.common.conversion.type.BlockStateConversion.tileEntityToBlockState(BlockStateConversion.java:205) [BKCommonLib-1.12.2-v4.jar:?]
	at com.bergerkiller.bukkit.common.conversion.type.WrapperConversion.toBlockState(WrapperConversion.java:160) [BKCommonLib-1.12.2-v4.jar:?]
	at com.bergerkiller.mountiplex.reflection.util.fast.GeneratedInvoker$mplgen56c8c595.invoke(Unknown Source) [?:?]
	at com.bergerkiller.mountiplex.reflection.util.FastMethod$FastMethodInitProxy.invoke(FastMethod.java:191) [BKCommonLib-1.12.2-v4.jar:?]
	at com.bergerkiller.mountiplex.reflection.util.FastMethod.invoke(FastMethod.java:122) [BKCommonLib-1.12.2-v4.jar:?]
	at com.bergerkiller.mountiplex.conversion.type.AnnotatedConverter.convertInput(AnnotatedConverter.java:41) [BKCommonLib-1.12.2-v4.jar:?]
	at com.bergerkiller.mountiplex.conversion.type.InputConverter.convertInput(InputConverter.java:96) [BKCommonLib-1.12.2-v4.jar:?]
	at com.bergerkiller.mountiplex.conversion.type.DuplexConverter$DuplexAdapter.convertInput(DuplexConverter.java:208) [BKCommonLib-1.12.2-v4.jar:?]
	at com.bergerkiller.mountiplex.conversion.Converter.convert(Converter.java:58) [BKCommonLib-1.12.2-v4.jar:?]
	at com.bergerkiller.mountiplex.conversion.Converter.convert(Converter.java:37) [BKCommonLib-1.12.2-v4.jar:?]
	at com.bergerkiller.mountiplex.conversion.util.ConvertingIterator.next(ConvertingIterator.java:30) [BKCommonLib-1.12.2-v4.jar:?]
	at com.bergerkiller.bukkit.tc.RedstoneTracker.loadSigns(RedstoneTracker.java:99) [TrainCarts-1.12.2-v2.jar:?]
	at com.bergerkiller.bukkit.tc.RedstoneTracker.initPowerLevels(RedstoneTracker.java:91) [TrainCarts-1.12.2-v2.jar:?]
	at com.bergerkiller.bukkit.tc.RedstoneTracker.<init>(RedstoneTracker.java:73) [TrainCarts-1.12.2-v2.jar:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_77]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) [?:1.8.0_77]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) [?:1.8.0_77]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) [?:1.8.0_77]
	at java.lang.Class.newInstance(Unknown Source) [?:1.8.0_77]
	at com.bergerkiller.bukkit.common.PluginBase.register(PluginBase.java:249) [BKCommonLib-1.12.2-v4.jar:?]
	at com.bergerkiller.bukkit.tc.TrainCarts.enable(TrainCarts.java:368) [TrainCarts-1.12.2-v2.jar:?]
	at com.bergerkiller.bukkit.common.PluginBase.onEnable(PluginBase.java:795) [BKCommonLib-1.12.2-v4.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) [patched_1.12.2.jar:git-Paper-1275]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) [patched_1.12.2.jar:git-Paper-1275]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [patched_1.12.2.jar:git-Paper-1275]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:384) [patched_1.12.2.jar:git-Paper-1275]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:333) [patched_1.12.2.jar:git-Paper-1275]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442) [patched_1.12.2.jar:git-Paper-1275]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403) [patched_1.12.2.jar:git-Paper-1275]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341) [patched_1.12.2.jar:git-Paper-1275]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:292) [patched_1.12.2.jar:git-Paper-1275]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) [patched_1.12.2.jar:git-Paper-1275]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_77]
[21:07:41] [Server thread/ERROR]: [BKCommonLib.Debug] [BKCommonLib] [Debug] Failed to convert net.minecraft.server.v1_12_R1.TileEntityMobSpawner to CraftBlockState  -  com.bergerkiller.bukkit.common.conversion.type.BlockStateConversion.tileEntityToBlockState(BlockStateConversion.java:229)
java.lang.UnsupportedOperationException: Method not instrumented by the CraftBlock proxy
	at com.bergerkiller.bukkit.common.conversion.type.BlockStateConversion$1.invoke(BlockStateConversion.java:44) ~[?:?]
	at com.bergerkiller.mountiplex.reflection.ClassInterceptor$CallbackMethodInterceptor.intercept(ClassInterceptor.java:641) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.block.CraftBlock$$EnhancerByCGLIB$$543ff3e8.getState0(<generated>) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.block.CraftBlock.getState(CraftBlock.java:272) ~[patched_1.12.2.jar:git-Paper-1275]
	at org.bukkit.craftbukkit.v1_12_R1.block.CraftBlock.getState(CraftBlock.java:266) ~[patched_1.12.2.jar:git-Paper-1275]
	at com.bergerkiller.bukkit.common.conversion.type.BlockStateConversion.tileEntityToBlockState(BlockStateConversion.java:215) [BKCommonLib-1.12.2-v4.jar:?]
	at com.bergerkiller.bukkit.common.conversion.type.BlockStateConversion.tileEntityToBlockState(BlockStateConversion.java:205) [BKCommonLib-1.12.2-v4.jar:?]
	at com.bergerkiller.bukkit.common.conversion.type.WrapperConversion.toBlockState(WrapperConversion.java:160) [BKCommonLib-1.12.2-v4.jar:?]
	at com.bergerkiller.mountiplex.reflection.util.fast.GeneratedInvoker$mplgen56c8c595.invoke(Unknown Source) [?:?]
	at com.bergerkiller.mountiplex.reflection.util.FastMethod.invoke(FastMethod.java:122) [BKCommonLib-1.12.2-v4.jar:?]
	at com.bergerkiller.mountiplex.conversion.type.AnnotatedConverter.convertInput(AnnotatedConverter.java:41) [BKCommonLib-1.12.2-v4.jar:?]
	at com.bergerkiller.mountiplex.conversion.type.InputConverter.convertInput(InputConverter.java:96) [BKCommonLib-1.12.2-v4.jar:?]
	at com.bergerkiller.mountiplex.conversion.type.DuplexConverter$DuplexAdapter.convertInput(DuplexConverter.java:208) [BKCommonLib-1.12.2-v4.jar:?]
	at com.bergerkiller.mountiplex.conversion.Converter.convert(Converter.java:58) [BKCommonLib-1.12.2-v4.jar:?]
	at com.bergerkiller.mountiplex.conversion.Converter.convert(Converter.java:37) [BKCommonLib-1.12.2-v4.jar:?]
	at com.bergerkiller.mountiplex.conversion.util.ConvertingIterator.next(ConvertingIterator.java:30) [BKCommonLib-1.12.2-v4.jar:?]
	at com.bergerkiller.bukkit.tc.RedstoneTracker.loadSigns(RedstoneTracker.java:99) [TrainCarts-1.12.2-v2.jar:?]
	at com.bergerkiller.bukkit.tc.RedstoneTracker.initPowerLevels(RedstoneTracker.java:91) [TrainCarts-1.12.2-v2.jar:?]
	at com.bergerkiller.bukkit.tc.RedstoneTracker.<init>(RedstoneTracker.java:73) [TrainCarts-1.12.2-v2.jar:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_77]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) [?:1.8.0_77]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) [?:1.8.0_77]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) [?:1.8.0_77]
	at java.lang.Class.newInstance(Unknown Source) [?:1.8.0_77]
	at com.bergerkiller.bukkit.common.PluginBase.register(PluginBase.java:249) [BKCommonLib-1.12.2-v4.jar:?]
	at com.bergerkiller.bukkit.tc.TrainCarts.enable(TrainCarts.java:368) [TrainCarts-1.12.2-v2.jar:?]
	at com.bergerkiller.bukkit.common.PluginBase.onEnable(PluginBase.java:795) [BKCommonLib-1.12.2-v4.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) [patched_1.12.2.jar:git-Paper-1275]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) [patched_1.12.2.jar:git-Paper-1275]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [patched_1.12.2.jar:git-Paper-1275]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:384) [patched_1.12.2.jar:git-Paper-1275]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:333) [patched_1.12.2.jar:git-Paper-1275]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442) [patched_1.12.2.jar:git-Paper-1275]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403) [patched_1.12.2.jar:git-Paper-1275]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341) [patched_1.12.2.jar:git-Paper-1275]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:292) [patched_1.12.2.jar:git-Paper-1275]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) [patched_1.12.2.jar:git-Paper-1275]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_77]
[21:07:41] [Server thread/INFO]: [Train_Carts] Train_Carts version 1.12.2-v2 (build: 246) enabled! (3.413s)
[21:07:41] [Server thread/INFO]: Done (5.585s)! For help, type "help" or "?"
[21:07:41] [Server thread/INFO]: Timings Reset
[21:07:41] [Server thread/INFO]: [AsyncWorldEdit] Loading plugins...

```

**Comment by bergerkiller** [comment]
Looks like a paperspigot incompatibility. They must have changed some things in the Chest block state constructor, causing it to use a function not handled by the proxy block. I'll look into it in a few hours and will provide a BKCommonlib update to patch it.

**Comment by bergerkiller** [comment]
https://ci.mg-dev.eu/job/BKCommonLib/350/

Try and see if this fixes this bug on paperspigot.
