### ISSUE TITLE
Unloading / loading into/from chests throws exception

### ISSUE THREAD

**Issue by zzorn** [bergerhealer/TrainCarts#21]
I placed a sign as follows:
> [train]
> deposit chest

as soon as a redstone torch is placed under the sign the following stack trace shows up in the server log:

[23:52:11 ERROR]: [Train_Carts] Failed to execute GROUP_ENTER for SignActionTransfer:
java.lang.ClassCastException: java.util.ArrayList cannot be cast to java.util.Set
	at com.bergerkiller.bukkit.common.utils.BlockUtil.getBlockStates(BlockUtil.java:473) ~[?:?]
	at com.bergerkiller.bukkit.common.utils.BlockUtil.getBlockStates(BlockUtil.java:454) ~[?:?]
	at com.bergerkiller.bukkit.tc.utils.TransferSignUtil.getBlockStates(TransferSignUtil.java:194) ~[?:?]
	at com.bergerkiller.bukkit.tc.utils.TransferSignUtil.getBlockStates(TransferSignUtil.java:177) ~[?:?]
	at com.bergerkiller.bukkit.tc.utils.TransferSignUtil.findBlocks(TransferSignUtil.java:258) ~[?:?]
	at com.bergerkiller.bukkit.tc.signactions.SignActionTransfer.execute(SignActionTransfer.java:82) ~[?:?]
	at com.bergerkiller.bukkit.tc.signactions.SignAction.executeAll(SignAction.java:187) ~[?:?]

Also got this when the sign was not immediately on the block under the rail, but one block lower:

[23:50:42 ERROR]: [Train_Carts] Failed to execute REDSTONE_ON for SignActionTransfer:
java.lang.ClassCastException: java.util.ArrayList cannot be cast to java.util.Set
	at com.bergerkiller.bukkit.common.utils.BlockUtil.getBlockStates(BlockUtil.java:473) ~[?:?]
	at com.bergerkiller.bukkit.common.utils.BlockUtil.getBlockStates(BlockUtil.java:454) ~[?:?]
	at com.bergerkiller.bukkit.tc.utils.TransferSignUtil.getBlockStates(TransferSignUtil.java:194) ~[?:?]
	at com.bergerkiller.bukkit.tc.utils.TransferSignUtil.getBlockStates(TransferSignUtil.java:177) ~[?:?]
	at com.bergerkiller.bukkit.tc.utils.TransferSignUtil.findBlocks(TransferSignUtil.java:258) ~[?:?]
	at com.bergerkiller.bukkit.tc.signactions.SignActionTransfer.execute(SignActionTransfer.java:82) ~[?:?]

I see [another commenter on the spigot page](https://www.spigotmc.org/resources/traincarts.8557/reviews#review-34535-32047) is also having problems with loading and unloading chests.

I'm using the latest version of TrainCharts, version 1.66-SNAPSHOT of BKCommonLib, and a spigot version from august 2015
(server log says: [00:32:25 INFO]: This server is running CraftBukkit version git-Spigot-fdc1440-53fac9f (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT).

It seems the problem happens in BKCommonLib at https://github.com/bergerhealer/BKCommonLib/blob/master/src/main/java/com/bergerkiller/bukkit/common/utils/BlockUtil.java#L473 although I don't quite see any cast to a Set on that line.

**Comment by mg-1999** [comment]
Just fixed it! Download the latest version of BKC and test it :dancers:

**Comment by zzorn** [comment]
It works now!  Thanks for the quick fix! :)
