### ISSUE TITLE
minecarts wont move

### ISSUE THREAD

**Issue by wolfnation2** [bergerhealer/TrainCarts#233]
##### Spigot version:1.12.2

<hr>

#### Problem or bug:
minecarts wont move when placed or spawned

**Comment by bergerkiller** [comment]
Any errors in the log? If theres no errors, only thing I can think of is that perhaps slowdown is set to false in DefaultTrainProperties.yml and collision with players is disabled.

**Comment by jacon500** [comment]
I'm having this issue as well. My setup is the same, but Spigot version is 1.13.1. I am getting errors in the log stating that the plugin failed to perform physics.

`[00:47:16 ERROR]: [Train_Carts] Failed to perform physics on train 'train1' at Park_25_5_106:
[00:47:16 ERROR]: [Train_Carts] Encountered a critical error
[00:47:16 ERROR]: [Train_Carts] Please, check for an updated version of Train_Carts before reporting this bug!
[00:47:16 ERROR]: [BKCommonLib] java.lang.IncompatibleClassChangeError: Method java.util.stream.Stream.of(Ljava/lang/Object;)Ljava/util/stream/Stream; must be InterfaceMethodref constant
[00:47:16 ERROR]: [BKCommonLib]   at com.bergerkiller.bukkit.common.internal.logic.EntityMoveHandler_1_13.world_getEntityCollisionShapes(EntityMoveHandler_1_13.java:188)
[00:47:16 ERROR]: [BKCommonLib]   at com.bergerkiller.bukkit.common.internal.logic.EntityMoveHandler_1_13.world_getCollisionShapes(EntityMoveHandler_1_13.java:77)
[00:47:16 ERROR]: [BKCommonLib]   at com.bergerkiller.bukkit.common.internal.logic.EntityMoveHandler.move(EntityMoveHandler.java:271)
[00:47:16 ERROR]: [BKCommonLib]   at com.bergerkiller.bukkit.common.controller.EntityController.onMove(EntityController.java:153)
[00:47:16 ERROR]: [BKCommonLib]   at com.bergerkiller.bukkit.tc.controller.MinecartMember.onPhysicsPostMove(MinecartMember.java:1741)
[00:47:16 ERROR]: [BKCommonLib]   at com.bergerkiller.bukkit.tc.controller.type.MinecartMemberRideable.onPhysicsPostMove(MinecartMemberRideable.java:55)
[00:47:16 ERROR]: [BKCommonLib]   at com.bergerkiller.bukkit.tc.controller.MinecartGroup.doPhysics_step(MinecartGroup.java:1475)
[00:47:16 ERROR]: [BKCommonLib]   at com.bergerkiller.bukkit.tc.controller.MinecartGroup.doPhysics(MinecartGroup.java:1301)
[00:47:16 ERROR]: [BKCommonLib]   at com.bergerkiller.bukkit.tc.controller.MinecartMember.onTick(MinecartMember.java:1874)
[00:47:16 ERROR]: [BKCommonLib]   at com.bergerkiller.bukkit.common.internal.hooks.EntityHook.onTick(EntityHook.java:118)
[00:47:16 ERROR]: [BKCommonLib]   at com.bergerkiller.mountiplex.reflection.util.fast.GeneratedInvoker$mplgen50b2c3ef.invokeVA(Unknown Source)
[00:47:16 ERROR]: [BKCommonLib]   at com.bergerkiller.mountiplex.reflection.util.FastMethod.invokeVA(FastMethod.java:112)
[00:47:16 ERROR]: [BKCommonLib]   at com.bergerkiller.mountiplex.reflection.ClassInterceptor$CallbackMethodInterceptor.intercept(ClassInterceptor.java:654)
[00:47:16 ERROR]: [BKCommonLib]   at net.minecraft.server.v1_13_R2.EntityMinecartRideable$$EnhancerByCGLIB$$16b6bbfc.tick(<generated>)
[00:47:16 ERROR]: [BKCommonLib]   at net.minecraft.server.v1_13_R2.World.entityJoinedWorld(World.java:1246)
[00:47:16 ERROR]: [BKCommonLib]   at net.minecraft.server.v1_13_R2.World.g(World.java:1218)
[00:47:16 ERROR]: [BKCommonLib]   at net.minecraft.server.v1_13_R2.World.tickEntities(World.java:1080)
[00:47:16 ERROR]: [BKCommonLib]   at net.minecraft.server.v1_13_R2.WorldServer.tickEntities(WorldServer.java:582)
[00:47:16 ERROR]: [BKCommonLib]   at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:894)
[00:47:16 ERROR]: [BKCommonLib]   at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:376)
[00:47:16 ERROR]: [BKCommonLib]   at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:792)
[00:47:16 ERROR]: [BKCommonLib]   at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:695)
[00:47:16 ERROR]: [BKCommonLib]   at java.base/java.lang.Thread.run(Unknown Source)`

**Comment by bergerkiller** [comment]
What is the version of Java you are running the server on? I test with Java 8, this might be some error introduced on java 9 or 10.

**Comment by bbayu123** [comment]
Is this issue resolved yet?
