### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by Vlader97** [bergerhealer/TrainCarts#249]
##### Paper version: 1.13.2 b505

<hr>

#### Problem or bug:
I made automatic furnace for burning ores but I got this problem:
```
[22:19:25] [Server thread/WARN]: java.lang.NullPointerException: The validated object is null
[22:19:25] [Server thread/WARN]: 	at org.apache.commons.lang3.Validate.notNull(Validate.java:225)
[22:19:25] [Server thread/WARN]: 	at org.apache.commons.lang3.Validate.notNull(Validate.java:206)
[22:19:25] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.NonNullList.set(SourceFile:51)
[22:19:25] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.EntityMinecartContainer.setItem(EntityMinecartContainer.java:118)
[22:19:25] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.EntityMinecartChest$$EnhancerByCGLIB$$f87dfc2.CGLIB$setItem$30(<generated>)
[22:19:25] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.EntityMinecartChest$$EnhancerByCGLIB$$f87dfc2$$FastClassByCGLIB$$d483b77f.invoke(<generated>)
[22:19:25] [Server thread/WARN]: 	at com.bergerkiller.mountiplex.dep.net.sf.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
[22:19:25] [Server thread/WARN]: 	at com.bergerkiller.mountiplex.reflection.ClassHook$HookMethodList$1$1.invoke(ClassHook.java:149)
[22:19:25] [Server thread/WARN]: 	at com.bergerkiller.mountiplex.reflection.ClassInterceptor$CallbackMethodInterceptor.intercept(ClassInterceptor.java:659)
[22:19:25] [Server thread/WARN]: 	at com.bergerkiller.bukkit.common.internal.hooks.EntityHook$$EnhancerByCGLIB$$d1d65432.setInventoryItem(<generated>)
[22:19:25] [Server thread/WARN]: 	at com.bergerkiller.bukkit.common.controller.EntityController.onItemSet(EntityController.java:168)
[22:19:25] [Server thread/WARN]: 	at com.bergerkiller.bukkit.tc.controller.type.MinecartMemberChest.onItemSet(MinecartMemberChest.java:106)
[22:19:25] [Server thread/WARN]: 	at com.bergerkiller.bukkit.common.internal.hooks.EntityHook.setInventoryItem(EntityHook.java:302)
[22:19:25] [Server thread/WARN]: 	at com.bergerkiller.mountiplex.reflection.util.fast.GeneratedInvoker$mplgene336b2b.invokeVA(Unknown Source)
[22:19:25] [Server thread/WARN]: 	at com.bergerkiller.mountiplex.reflection.util.FastMethod.invokeVA(FastMethod.java:112)
[22:19:25] [Server thread/WARN]: 	at com.bergerkiller.mountiplex.reflection.ClassInterceptor$CallbackMethodInterceptor.intercept(ClassInterceptor.java:655)
[22:19:25] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.EntityMinecartChest$$EnhancerByCGLIB$$f87dfc2.setItem(<generated>)
[22:19:25] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.TileEntityHopper.hopperPull(TileEntityHopper.java:262)
[22:19:25] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.TileEntityHopper.a(TileEntityHopper.java:503)
[22:19:25] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.TileEntityHopper.a(TileEntityHopper.java:479)
[22:19:25] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.TileEntityHopper.lambda$tick$0(TileEntityHopper.java:119)
[22:19:25] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.TileEntityHopper.a(TileEntityHopper.java:140)
[22:19:25] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.TileEntityHopper.tick(TileEntityHopper.java:118)
[22:19:25] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.World.tickEntities(World.java:1407)
[22:19:25] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.WorldServer.tickEntities(WorldServer.java:598)
[22:19:25] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1099)
[22:19:25] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439)
[22:19:25] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:938)
[22:19:25] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:836)
[22:19:25] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
```
#### Expected behaviour:
Work without problems.

#### Steps to reproduce:
I prepared the world with automatic furnace. Fill iron ore in the minecarts with chest and wait. 
world: https://www.dropbox.com/s/ybcmqf8u1tg0i0i/BugTrain.zip?dl=0

**Comment by bergerkiller** [comment]
Ah yeah, I fixed that the other day. Should be fixed here. https://ci.mg-dev.eu/job/BKCommonLib/508/

**Comment by Vlader97** [comment]
Yes it is fixed :)
Thank you.
