### ISSUE TITLE
Exception 

### ISSUE THREAD

**Issue by DefinitlyEvil** [bergerhealer/TrainCarts#257]
##### Spigot version: `1.13.2`

<hr>

#### Problem or bug:
```
[19:47:10 INFO]: [Train_Carts] Enabling Train_Carts v1.13.2-v1
[19:47:12 INFO]: [Train_Carts] 1 Train has been loaded in 1 world. (4 Minecarts)
[19:47:12 ERROR]: Failed to compile method body ([source error] no such class: BlockPosition$b):
[19:47:12 ERROR]: public Object invoke(Object instance_raw, Object handler_raw, Object voxelshape_raw, Object voxelshape1_raw, Object flag_raw, Object flag1_raw) {net.minecraft.server.v1_13_R2.World instance = (net.minecraft.server.v1_13_R2.World) instance_raw;com.bergerkiller.bukkit.common.internal.logic.EntityMoveHandler_1_13 handler=(com.bergerkiller.bukkit.common.internal.logic.EntityMoveHandler_1_13) handler_raw;net.minecraft.server.v1_13_R2.VoxelShape voxelshape=(net.minecraft.server.v1_13_R2.VoxelShape) voxelshape_raw;net.minecraft.server.v1_13_R2.VoxelShape voxelshape1=(net.minecraft.server.v1_13_R2.VoxelShape) voxelshape1_raw;boolean flag=((Boolean) flag_raw).booleanValue();boolean flag1=((Boolean) flag1_raw).booleanValue();{
int i = MathHelper.floor(voxelshape.b(EnumDirection.EnumAxis.X)) - 1;
int j = MathHelper.f(voxelshape.c(EnumDirection.EnumAxis.X)) + 1;
int k = MathHelper.floor(voxelshape.b(EnumDirection.EnumAxis.Y)) - 1;
int l = MathHelper.f(voxelshape.c(EnumDirection.EnumAxis.Y)) + 1;
int i1 = MathHelper.floor(voxelshape.b(EnumDirection.EnumAxis.Z)) - 1;
int j1 = MathHelper.f(voxelshape.c(EnumDirection.EnumAxis.Z)) + 1;
WorldBorder worldborder = instance.getWorldBorder();
VoxelShape voxelshape2 = VoxelShapes.a();
VoxelShapeBitSet voxelshapebitset = new VoxelShapeBitSet(j - i, l - k, j1 - i1);
BlockPosition$b blockposition_b = BlockPosition$b.r();
Throwable throwable = null;
try {
for (int k1 = i; k1 < j; ++k1) {
VoxelShape voxelshape3 = VoxelShapes.a();
for (int l1 = i1; l1 < j1; ++l1) {
boolean flag2 = k1 == i || k1 == j - 1;
boolean flag3 = l1 == i1 || l1 == j1 - 1;
if (flag2 && flag3) {
continue;
}
blockposition_b.c(k1, 64, l1);
if (instance.isLoaded(blockposition_b)) {
VoxelShape voxelshape4 = VoxelShapes.a();
for (int i2 = k; i2 < l; ++i2) {
if (!flag2 && !flag3 || i2 != l - 1) {
blockposition_b.c(k1, i2, l1);
VoxelShape voxelshape5;
if (flag1 && !worldborder.a((BlockPosition) blockposition_b)) {
voxelshape5 = VoxelShapes.b();
} else {
voxelshape5 = instance.getType(blockposition_b).getCollisionShape(instance, blockposition_b);
}
if (!voxelshape5.isEmpty()) {
VoxelShape voxelshape6;
VoxelShape voxelshape7;
voxelshape6 = voxelshape5.a((double) k1, (double) i2, (double) l1);
if (!VoxelShapes.c(voxelshape, voxelshape6, OperatorBoolean.AND)) {
continue;
}
org.bukkit.craftbukkit.block.CraftBlock cb_block = new org.bukkit.craftbukkit.block.CraftBlock(instance, blockposition_b.h());
if (!handler.onBlockCollided(cb_block)) {
continue;
}
if (voxelshape5 == VoxelShapes.b()) {
if (flag) {
if (!VoxelShapes.c(voxelshape1, voxelshape6, OperatorBoolean.AND) && VoxelShapes.c(voxelshape, voxelshape6, OperatorBoolean.AND)) {
voxelshape7 = VoxelShapes.b();
return voxelshape7;
}
} else {
voxelshapebitset.a(k1 - i, i2 - k, l1 - i1, true, true);
}
} else {
if (!VoxelShapes.c(voxelshape1, voxelshape6, OperatorBoolean.AND) && VoxelShapes.c(voxelshape, voxelshape6, OperatorBoolean.AND)) {
if (flag) {
voxelshape7 = VoxelShapes.b();
return voxelshape7;
}
voxelshape4 = VoxelShapes.b(voxelshape4, voxelshape6, OperatorBoolean.OR);
}
}
}
}
}
voxelshape3 = VoxelShapes.b(voxelshape3, voxelshape4, OperatorBoolean.OR);
}
}
voxelshape2 = VoxelShapes.b(voxelshape2, voxelshape3, OperatorBoolean.OR);
}
} catch (Throwable throwable1) {
throwable = throwable1;
throw throwable1;
} finally {
if (blockposition_b != null) {
if (throwable != null) {
try {
blockposition_b.close();
} catch (Throwable throwable2) {
throwable.addSuppressed(throwable2);
}
} else {
blockposition_b.close();
}
}
}
if (flag) {
return java.util.stream.Stream.empty();
} else {
voxelshape2 = voxelshape2.c();
VoxelShapeWorldRegion voxelshapeworldregion = new VoxelShapeWorldRegion(voxelshapebitset, i, k, i1);
voxelshape2 = VoxelShapes.b(voxelshape2, voxelshapeworldregion, OperatorBoolean.OR);
return com.bergerkiller.mountiplex.MountiplexUtil.toStream(voxelshape2);
}
}
return null;}
[19:47:12 WARN]: java.lang.RuntimeException: An exception occurred
[19:47:12 WARN]: Caused by: compile error: no such class: BlockPosition$b
[19:47:12 WARN]: at com.bergerkiller.mountiplex.dep.javassist.compiler.MemberResolver.searchImports(MemberResolver.java:479)
[19:47:12 WARN]: at com.bergerkiller.mountiplex.dep.javassist.compiler.MemberResolver.lookupClass(MemberResolver.java:422)
[19:47:12 WARN]: at com.bergerkiller.mountiplex.dep.javassist.compiler.MemberResolver.lookupClassByJvmName(MemberResolver.java:329)
[19:47:12 WARN]: at com.bergerkiller.mountiplex.dep.javassist.compiler.MemberResolver.resolveJvmClassName(MemberResolver.java:519)
[19:47:12 WARN]: at com.bergerkiller.mountiplex.dep.javassist.compiler.MemberCodeGen.resolveClassName(MemberCodeGen.java:1190)
[19:47:12 WARN]: at com.bergerkiller.mountiplex.dep.javassist.compiler.CodeGen.atDeclarator(CodeGen.java:757)
[19:47:12 WARN]: at com.bergerkiller.mountiplex.dep.javassist.compiler.ast.Declarator.accept(Declarator.java:103)
[19:47:12 WARN]: at com.bergerkiller.mountiplex.dep.javassist.compiler.CodeGen.atStmnt(CodeGen.java:381)
[19:47:12 WARN]: at com.bergerkiller.mountiplex.dep.javassist.compiler.ast.Stmnt.accept(Stmnt.java:53)
[19:47:12 WARN]: at com.bergerkiller.mountiplex.dep.javassist.compiler.CodeGen.atStmnt(CodeGen.java:381)
[19:47:12 WARN]: at com.bergerkiller.mountiplex.dep.javassist.compiler.ast.Stmnt.accept(Stmnt.java:53)
[19:47:12 WARN]: at com.bergerkiller.mountiplex.dep.javassist.compiler.CodeGen.atStmnt(CodeGen.java:381)
[19:47:12 WARN]: at com.bergerkiller.mountiplex.dep.javassist.compiler.ast.Stmnt.accept(Stmnt.java:53)
[19:47:12 WARN]: at com.bergerkiller.mountiplex.dep.javassist.compiler.CodeGen.atMethodBody(CodeGen.java:321)
[19:47:12 WARN]: at com.bergerkiller.mountiplex.dep.javassist.compiler.CodeGen.atMethodDecl(CodeGen.java:303)
[19:47:12 WARN]: at com.bergerkiller.mountiplex.dep.javassist.compiler.ast.MethodDecl.accept(MethodDecl.java:47)
[19:47:12 WARN]: at com.bergerkiller.mountiplex.dep.javassist.compiler.Javac.compileMethod(Javac.java:175)
[19:47:12 WARN]: at com.bergerkiller.mountiplex.dep.javassist.compiler.Javac.compile(Javac.java:102)
[19:47:12 WARN]: at com.bergerkiller.mountiplex.dep.javassist.CtNewMethod.make(CtNewMethod.java:79)
[19:47:12 WARN]: at com.bergerkiller.mountiplex.dep.javassist.CtNewMethod.make(CtNewMethod.java:50)
[19:47:12 WARN]: at com.bergerkiller.mountiplex.reflection.util.fast.GeneratedCodeInvoker.makeMethodAndLog(GeneratedCodeInvoker.java:84)
[19:47:12 WARN]: at com.bergerkiller.mountiplex.reflection.util.fast.GeneratedCodeInvoker.create(GeneratedCodeInvoker.java:244)
[19:47:12 WARN]: at com.bergerkiller.mountiplex.reflection.util.FastMethod$FastMethodInitProxy.init(FastMethod.java:168)
[19:47:12 WARN]: at com.bergerkiller.mountiplex.reflection.util.FastMethod$FastMethodInitProxy.access$100(FastMethod.java:146)
[19:47:12 WARN]: at com.bergerkiller.mountiplex.reflection.util.FastMethod.forceInitialization(FastMethod.java:106)
[19:47:12 WARN]: at com.bergerkiller.bukkit.common.internal.logic.EntityMoveHandler_1_13.<clinit>(EntityMoveHandler_1_13.java:59)
[19:47:12 WARN]: at com.bergerkiller.bukkit.common.internal.logic.EntityMoveHandler.create(EntityMoveHandler.java:59)
[19:47:12 WARN]: at com.bergerkiller.bukkit.common.controller.EntityController.<init>(EntityController.java:20)
[19:47:12 WARN]: at com.bergerkiller.bukkit.common.controller.DefaultEntityController.<init>(DefaultEntityController.java:9)
[19:47:12 WARN]: at com.bergerkiller.bukkit.common.entity.CommonEntity.getController(CommonEntity.java:249)
[19:47:12 WARN]: at com.bergerkiller.bukkit.tc.controller.MinecartMemberStore.canConvert(MinecartMemberStore.java:120)
[19:47:12 WARN]: at com.bergerkiller.bukkit.tc.controller.MinecartMemberStore.canConvertAutomatically(MinecartMemberStore.java:86)
[19:47:12 WARN]: at com.bergerkiller.bukkit.tc.controller.MinecartMemberStore.convertAllAutomatically(MinecartMemberStore.java:62)
[19:47:12 WARN]: at com.bergerkiller.bukkit.tc.TrainCarts.enable(TrainCarts.java:329)
[19:47:12 WARN]: at com.bergerkiller.bukkit.common.PluginBase.onEnable(PluginBase.java:797)
[19:47:12 WARN]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265)
[19:47:12 WARN]: at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:347)
[19:47:12 WARN]: at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410)
[19:47:12 WARN]: at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:436)
[19:47:12 WARN]: at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:350)
[19:47:12 WARN]: at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:580)
[19:47:12 WARN]: at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:542)
[19:47:12 WARN]: at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:420)
[19:47:12 WARN]: at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:294)
[19:47:12 WARN]: at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:698)
[19:47:12 WARN]: at java.lang.Thread.run(Thread.java:748)
[19:47:14 INFO]: [Train_Carts] 0 detector rail regions loaded covering 0 blocks
[19:47:14 INFO]: [Train_Carts] Restoring trains and loading nearby chunks...
[19:47:14 INFO]: [Train_Carts] Train_Carts version 1.13.2-v1 (build: 431) enabled! (4.535s)
```

#### Expected behaviour:
no exceptions I assume. ;) 

#### Steps to reproduce:
I just remembered I used WorldEdit with PlotSquared and the server kept running for 20+ hours.

**Comment by DefinitlyEvil** [comment]
PS: All carts stopped working! :(

**Comment by weeryan17** [comment]
try this version of bkcommonlib https://ci.mg-dev.eu/job/BKCommonLib/524/artifact/target/BKCommonLib-1.13.2-v3-SNAPSHOT.jar
Spigot recently changed some stuff around so bkcommonlib broke

**Comment by DefinitlyEvil** [comment]
@weeryan17 ok thanks! I'll give it a shot!

**Comment by bergerkiller** [comment]
I fixed this in BKCommonLib recently, so the latest dev build of bkcommonlib should fix it up yeah

**Comment by DefinitlyEvil** [comment]
ok cool! thanks! ;)
