### ISSUE TITLE
Sign error

### ISSUE THREAD

**Issue by Vlader97** [bergerhealer/TrainCarts#267]
##### Paper version: 1.14.2-B105

<hr>

#### Problem or bug:
When I using automatic trains in world from 1.13.2 I receiving randomly this error:

```[19:18:15] [Server thread/WARN]: Skipping BlockEntity with id minecraft:sign
[19:18:15] [Server thread/ERROR]: Failed to load data for block entity minecraft:sign
java.lang.NullPointerException: null
	at net.minecraft.server.v1_14_R1.ChatComponentUtils.filterForDisplay(SourceFile:38) ~[patched_1.14.2.jar:git-Paper-105]
	at net.minecraft.server.v1_14_R1.TileEntitySign.load(TileEntitySign.java:103) ~[patched_1.14.2.jar:git-Paper-105]
	at net.minecraft.server.v1_14_R1.TileEntity.lambda$create$1(TileEntity.java:135) ~[patched_1.14.2.jar:git-Paper-105]
	at java.util.Optional.map(Optional.java:215) ~[?:1.8.0_151]
	at net.minecraft.server.v1_14_R1.TileEntity.create(TileEntity.java:132) ~[patched_1.14.2.jar:git-Paper-105]
	at org.bukkit.craftbukkit.v1_14_R1.block.CraftBlockEntityState.createSnapshot(CraftBlockEntityState.java:82) ~[patched_1.14.2.jar:git-Paper-105]
	at org.bukkit.craftbukkit.v1_14_R1.block.CraftBlockEntityState.<init>(CraftBlockEntityState.java:37) ~[patched_1.14.2.jar:git-Paper-105]
	at org.bukkit.craftbukkit.v1_14_R1.block.CraftSign.<init>(CraftSign.java:19) ~[patched_1.14.2.jar:git-Paper-105]
	at org.bukkit.craftbukkit.v1_14_R1.block.CraftBlock.getState0(CraftBlock.java:344) ~[patched_1.14.2.jar:git-Paper-105]
	at org.bukkit.craftbukkit.v1_14_R1.block.CraftBlock.getState(CraftBlock.java:322) ~[patched_1.14.2.jar:git-Paper-105]
	at org.bukkit.craftbukkit.v1_14_R1.block.CraftBlock.getState(CraftBlock.java:316) ~[patched_1.14.2.jar:git-Paper-105]
	at com.bergerkiller.bukkit.common.conversion.blockstate.BlockStateConversion_1_13.tileEntityToBlockState(BlockStateConversion_1_13.java:357) ~[?:?]
	at com.bergerkiller.bukkit.common.conversion.blockstate.BlockStateConversion_1_13.tileEntityToBlockState(BlockStateConversion_1_13.java:346) ~[?:?]
	at com.bergerkiller.bukkit.common.conversion.blockstate.ChunkBlockStateConverter.convertInput(ChunkBlockStateConverter.java:20) ~[?:?]
	at com.bergerkiller.bukkit.common.conversion.blockstate.ChunkBlockStateConverter.convertInput(ChunkBlockStateConverter.java:10) ~[?:?]
	at com.bergerkiller.mountiplex.conversion.Converter.convert(Converter.java:58) ~[?:?]
	at com.bergerkiller.mountiplex.conversion.Converter.convert(Converter.java:37) ~[?:?]
	at com.bergerkiller.mountiplex.conversion.util.ConvertingIterator.next(ConvertingIterator.java:30) ~[?:?]
	at com.bergerkiller.bukkit.tc.RedstoneTracker.loadSigns(RedstoneTracker.java:110) ~[?:?]
	at com.bergerkiller.bukkit.tc.RedstoneTracker$2.run(RedstoneTracker.java:144) ~[?:?]
	at com.bergerkiller.bukkit.common.internal.CommonPlugin$NextTickHandler.run(CommonPlugin.java:712) ~[?:?]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.2.jar:git-Paper-105]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[patched_1.14.2.jar:git-Paper-105]
	at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1129) ~[patched_1.14.2.jar:git-Paper-105]
	at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:418) ~[patched_1.14.2.jar:git-Paper-105]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1061) ~[patched_1.14.2.jar:git-Paper-105]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:905) ~[patched_1.14.2.jar:git-Paper-105]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
```

**Comment by bbayu123** [comment]
Should work with latest dev builds, can you take a look?

**Comment by Vlader97** [comment]
I confirm. It is fixed.
