### ISSUE TITLE
Shift slapping inconsistent, console spammed with errors

### ISSUE THREAD

**Issue by ErenTD** [bergerhealer/TrainCarts#274]
##### Spigot version: 1.13.2

<hr>

#### Problem or bug: When I spawn any train and get it moving, the console gets flooded with error messages. And also shift slapping inconsistent. Works for some trains, breaks the train for some. The following error message gets printed around 20 times per second.

```
[17:44:56 ERROR]: [Train_Carts] Failed to perform physics on train 'CRA01M1' at world_568_51_-133:
[17:44:56 ERROR]: [Train_Carts] Encountered a critical error
[17:44:56 ERROR]: [Train_Carts] Please, check for an updated version of Train_Carts before reporting this bug!
[17:44:56 ERROR]: [BKCommonLib] java.lang.AbstractMethodError: com.bergerkiller.generated.net.minecraft.server.EntityHandle.isLoaded()Z
[17:44:56 ERROR]: [BKCommonLib]   at com.bergerkiller.bukkit.common.bases.ExtendedEntity.isInLoadedChunk(ExtendedEntity.java:451)
[17:44:56 ERROR]: [BKCommonLib]   at com.bergerkiller.bukkit.tc.controller.MinecartGroup.doPhysics(MinecartGroup.java:1403)
[17:44:56 ERROR]: [BKCommonLib]   at com.bergerkiller.bukkit.tc.controller.MinecartMember.onTick(MinecartMember.java:1906)
[17:44:56 ERROR]: [BKCommonLib]   at com.bergerkiller.bukkit.common.internal.hooks.EntityHook.onTick(EntityHook.java:118)
[17:44:56 ERROR]: [BKCommonLib]   at com.bergerkiller.mountiplex.reflection.util.fast.GeneratedInvoker$mplgen63d75313.invokeVA(Unknown Source)
[17:44:56 ERROR]: [BKCommonLib]   at com.bergerkiller.mountiplex.reflection.util.FastMethod.invokeVA(FastMethod.java:112)
[17:44:56 ERROR]: [BKCommonLib]   at com.bergerkiller.mountiplex.reflection.ClassInterceptor$CallbackMethodInterceptor.intercept(ClassInterceptor.java:655)
[17:44:56 ERROR]: [BKCommonLib]   at net.minecraft.server.v1_13_R2.EntityMinecartRideable$$EnhancerByCGLIB$$2b1c6f57.tick(<generated>)
[17:44:56 ERROR]: [BKCommonLib]   at net.minecraft.server.v1_13_R2.World.entityJoinedWorld(World.java:1331)
[17:44:56 ERROR]: [BKCommonLib]   at net.minecraft.server.v1_13_R2.World.g(World.java:1298)
[17:44:56 ERROR]: [BKCommonLib]   at net.minecraft.server.v1_13_R2.World.tickEntities(World.java:1132)
[17:44:56 ERROR]: [BKCommonLib]   at net.minecraft.server.v1_13_R2.WorldServer.tickEntities(WorldServer.java:583)
[17:44:56 ERROR]: [BKCommonLib]   at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:968)
[17:44:56 ERROR]: [BKCommonLib]   at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417)
[17:44:56 ERROR]: [BKCommonLib]   at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831)
[17:44:56 ERROR]: [BKCommonLib]   at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729)
[17:44:56 ERROR]: [BKCommonLib]   at java.lang.Thread.run(Unknown Source)
```

#### Steps to reproduce:
-Make a fresh server
-Install BKC and TC
-Make an automated system using signs
-Spawn trains on your freshly made line
-Look at the console

**Comment by bergerkiller** [comment]
First Id have to suggest is trying out the latest development builds to see if this is fixed, though I'm not sure what went wrong here. You can check if theres anything else logged at server startup.

https://ci.mg-dev.eu/job/BKCommonLib/566/
https://ci.mg-dev.eu/job/TrainCarts/473/

**Comment by ErenTD** [comment]
I have tried them, it just prints out more errors. I am going to attach my entire log, so you could see if I have missed any error messages. 

[https://pastebin.com/HNyYSK3Z](url)

As far as I know, nothing funny is logged in the startup. Everything happens as soon as I spawn a train.

**Comment by bergerkiller** [comment]
Can you post the exact java command that is used to run the server? It may depend on what you're using to launch it. If it's a batch or bash script that you execute, it will be in there. Not sure where you can find it when you're using an online portal for it.

Knowing the java version that is installed will help too. To check it, open a terminal (on windows, 'cmd') and type:
`java -version`

I suspect that some internal logic is broken causing it to not find and/or generate the implementation for isLoaded. I can't reproduce it using the exact same builds of bkcommonlib and traincarts, so something must be up with the server environment itself.

**Comment by ErenTD** [comment]
###Java Version
```
Java(TM) SE Runtime Environment (build 1.8.0_192-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.192-b12, mixed mode)
```

###Server run script
```
@echo off
java -Xms2G -Xmx2G -XX:+UseConcMarkSweepGC -jar spigot.jar
pause
```

**Comment by bergerkiller** [comment]
Im still having trouble and need deeper logs. I've added some logging of every 'Handle' that is generated, and what methods are implemented doing so. It should help identify what is (or isn't) happening.

https://www.dropbox.com/s/hcm9zav5ikp4x4r/BKCommonLib-1.14.3-v1-SNAPSHOT_log_handle_gen.jar?dl=0

You do need the dev build of traincarts 1.14+. https://ci.mg-dev.eu/job/TrainCarts/473/

**Comment by ErenTD** [comment]
Here is the detailed log. I couldn't upload it to pastebin because it was larger than 512KB.
I used spigot version **1.14.3**, everything else is the same (java, run script etc.) I also used the same world. No other plugins other than the _TrainCarts Snapshot_ and _BKCommonLib Log Hanle Gen_ were installed.

https://www.dropbox.com/s/gyhek82uztfpd7q/latest.log?dl=0

**Comment by bergerkiller** [comment]
`Adding getter for [PUBLIC] public boolean isLoaded:inChunk; -> sLoaded`

Wow what?! Is it by any chance possible the server is run on a machine with arabic locale?

**Comment by ErenTD** [comment]
No, it's running on a machine with turkish locale. We use the latin alphabet.

**Comment by bergerkiller** [comment]
I was mistaken, it was turkish not arabic causing that. There's a rather infamous problem in Java when you use toLowerCase/toUpperCase without explicitly mentioning English locale: http://mattryall.net/blog/2009/02/the-infamous-turkish-locale-

Basically, the 'i' in 'IsLoaded' disappears and mismatches what is found in the pregenerated template files. I did indeed forget to put the english locale in some places. This should patch that: https://ci.mg-dev.eu/job/BKCommonLib/569/

**Comment by ErenTD** [comment]
Alright it worked for spigot 1.14, thank you.
And also, is there any chance you could apply the patch to the 1.13.2 build or would I be asking for too much :) Because my server is running on 1.13.2 and not all plugins are updated for 1.14 yet thus I can't update my server yet. And of course the 1.14 build doesn't go well with 1.13 so yeah.

Also I appreciate your help for 2 days. 💯

**Comment by bergerkiller** [comment]
The 1.14+ builds work just fine on 1.13 :)

**Comment by ErenTD** [comment]
Alright thanks.

**Comment by ErenTD** [comment]
Now I get this when I run 1.13 with the new BKC. There aren't even any trains running on the server. Now this gets spammed, doesn't happen in 1.14. I would REALLY appreciate it if you could patch 1.13.

```
[14:20:42 ERROR]: [BKCommonLib] [Network] Error occurred in onPacketSend handling PacketPlayOutTileEntityData:
java.lang.IllegalStateException: Asynchronous access is not permitted
        at com.bergerkiller.bukkit.common.conversion.blockstate.BlockStateConversion_1_13.blockToBlockState(BlockStateConversion_1_13.java:327) ~[?:?]
        at com.bergerkiller.bukkit.common.utils.BlockUtil.getState(BlockUtil.java:469) ~[?:?]
        at com.bergerkiller.bukkit.common.utils.BlockUtil.getState(BlockUtil.java:481) ~[?:?]
        at com.bergerkiller.bukkit.common.utils.BlockUtil.getSign(BlockUtil.java:489) ~[?:?]
        at com.bergerkiller.bukkit.sl.VirtualSign.loadSign(VirtualSign.java:316) ~[?:?]
        at com.bergerkiller.bukkit.sl.VirtualSign.update(VirtualSign.java:436) ~[?:?]
        at com.bergerkiller.bukkit.sl.SLListener.onPacketSend(SLListener.java:114) ~[?:?]
        at com.bergerkiller.bukkit.common.internal.network.PacketHandlerHooked.handlePacketSend(PacketHandlerHooked.java:304) ~[?:?]
        at com.bergerkiller.bukkit.common.internal.network.CommonPacketHandler$CommonChannelListener.write(CommonPacketHandler.java:127) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[spigot.jar:git-Spigot-1a3504a-84f3da3]
        at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801) ~[spigot.jar:git-Spigot-1a3504a-84f3da3]
        at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814) ~[spigot.jar:git-Spigot-1a3504a-84f3da3]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794) ~[spigot.jar:git-Spigot-1a3504a-84f3da3]
        at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831) ~[spigot.jar:git-Spigot-1a3504a-84f3da3]
        at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1071) ~[spigot.jar:git-Spigot-1a3504a-84f3da3]
        at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:300) ~[spigot.jar:git-Spigot-1a3504a-84f3da3]
        at net.minecraft.server.v1_13_R2.NetworkManager.lambda$4(NetworkManager.java:198) ~[spigot.jar:git-Spigot-1a3504a-84f3da3]
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) [spigot.jar:git-Spigot-1a3504a-84f3da3]
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404) [spigot.jar:git-Spigot-1a3504a-84f3da3]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:465) [spigot.jar:git-Spigot-1a3504a-84f3da3]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884) [spigot.jar:git-Spigot-1a3504a-84f3da3]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_192]
```

**Comment by 56738** [comment]
Try installing the latest build of SignLink: https://ci.mg-dev.eu/job/SignLink/

**Comment by ErenTD** [comment]
Oh, my bad. Totally forgot about signlink. Updated it and now everythin is fine. Sorry for the hassle.
