### ISSUE TITLE
Chest out/in

### ISSUE THREAD

**Issue by FireF0re** [bergerhealer/TrainCarts#29]
When the train drive over a chest in/out the train didn't do anything and the console: 

[10:58:04 ERROR]: [Train_Carts] Failed to execute GROUP_ENTER for SignActionTransfer:
java.lang.ClassCastException: java.util.ArrayList cannot be cast to java.util.Set
        at com.bergerkiller.bukkit.common.utils.BlockUtil.getBlockStates(BlockUtil.java:473) ~[?:?]
        at com.bergerkiller.bukkit.common.utils.BlockUtil.getBlockStates(BlockUtil.java:454) ~[?:?]
        at com.bergerkiller.bukkit.tc.utils.TransferSignUtil.getBlockStates(TransferSignUtil.java:194) ~[?:?]
        at com.bergerkiller.bukkit.tc.utils.TransferSignUtil.getBlockStates(TransferSignUtil.java:177) ~[?:?]
        at com.bergerkiller.bukkit.tc.utils.TransferSignUtil.findBlocks(TransferSignUtil.java:258) ~[?:?]
        at com.bergerkiller.bukkit.tc.signactions.SignActionTransfer.execute(SignActionTransfer.java:79) ~[?:?]
        at com.bergerkiller.bukkit.tc.signactions.SignAction.executeAll(SignAction.java:187) ~[?:?]

**Comment by mg-1999** [comment]
What version of TrainCarts and bkcommonlib are you running?

Op wo 21 okt. 2015 11:05 schreef FireF0re <notifications@github.com>:

**Comment by FireF0re** [comment]
Train_Carts v1.75-SNAPSHOT BKCommonLib v1.66-SNAPSHOT

**Comment by mg-1999** [comment]
Try the latest from the resource page and check if its fixed.

Op wo 21 okt. 2015 11:17 schreef FireF0re <notifications@github.com>:

**Comment by FireF0re** [comment]
Did you mean from Spigot or a other side?

**Comment by mg-1999** [comment]
From Spigot.

Op wo 21 okt. 2015 11:25 schreef FireF0re <notifications@github.com>:

**Comment by FireF0re** [comment]
The version 1.75 is the newest yet.

**Comment by mg-1999** [comment]
Just redownload the version, I update a lot and don't change version
numbers often so there is a change that you have an outdated version.

Op wo 21 okt. 2015 12:01 schreef FireF0re <notifications@github.com>:

**Comment by FireF0re** [comment]
I have redownloaded the version but the error is still there. I have also deleted the config.

[15:29:18 ERROR]: [Train_Carts] Failed to execute GROUP_ENTER for SignActionTransfer:
java.lang.ClassCastException: java.util.ArrayList cannot be cast to java.util.Set
        at com.bergerkiller.bukkit.common.utils.BlockUtil.getBlockStates(BlockUtil.java:473) ~[?:?]
        at com.bergerkiller.bukkit.common.utils.BlockUtil.getBlockStates(BlockUtil.java:454) ~[?:?]
        at com.bergerkiller.bukkit.tc.utils.TransferSignUtil.getBlockStates(TransferSignUtil.java:194) ~[?:?]
        at com.bergerkiller.bukkit.tc.utils.TransferSignUtil.getBlockStates(TransferSignUtil.java:177) ~[?:?]
        at com.bergerkiller.bukkit.tc.utils.TransferSignUtil.findBlocks(TransferSignUtil.java:258) ~[?:?]
        at com.bergerkiller.bukkit.tc.signactions.SignActionTransfer.execute(SignActionTransfer.java:82) ~[?:?]
        at com.bergerkiller.bukkit.tc.signactions.SignAction.executeAll(SignAction.java:187) ~[?:?]

**Comment by mg-1999** [comment]
Use spigot and not bukkit.

Op wo 21 okt. 2015 15:30 schreef FireF0re <notifications@github.com>:

**Comment by FireF0re** [comment]
I use Spigot.

**Comment by mg-1999** [comment]
You don't, give me the output of /version

Op wo 21 okt. 2015 21:55 schreef FireF0re <notifications@github.com>:

**Comment by FireF0re** [comment]
[10:20:45 INFO]: This server is running CraftBukkit version git-Spigot-5f38d38-18fbb24 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT)
[10:20:45 INFO]: You are running the latest version

**Comment by mg-1999** [comment]
See you are running Craftbukkit and not Spigot. Use the spigot.jar instead
of the craftbukkit.jar in buildtools

Op do 22 okt. 2015 10:20 schreef FireF0re <notifications@github.com>:

**Comment by FireF0re** [comment]
I use the spigot.jar from buildtools. When you do on your server (162.244.166.91:62515) /version it's the same.

**Comment by mg-1999** [comment]
I just looked into the source real quick and this bug has already been fixed, please download a new version of BKCommonLib please.

**Comment by FireF0re** [comment]
Okay, I have downloaded a new version of BKCommonLib and it works! Thanks!
