### ISSUE TITLE
Portal Sign problem

### ISSUE THREAD

**Issue by 24Emergency** [bergerhealer/TrainCarts#303]
##### Spigot version: latest 1.14.4

<hr>

#### Problem or bug:
TrainCarts Portal Sign problem(Both MyWorlds, Multiverse Portal)
teleport to Portal Sign or  Multiverse Portal in other world doesn't work.
teleport to Portal Sign or  Multiverse Portal in same world works fine.

**Comment by 24Emergency** [comment]
`[21:45:19] [Server thread/ERROR]: [Train_Carts] Failed to execute GROUP_ENTER for SignActionTeleport:
java.lang.IllegalStateException: Removing entity while ticking!
        at net.minecraft.server.v1_14_R1.WorldServer.removeEntity(WorldServer.java:1116) ~[spigot.jar:git-Spigot-a596182-3fc97f0]
        at com.bergerkiller.mountiplex.reflection.util.fast.GeneratedInvoker$mplgen2a7f601.invoke(Unknown Source) ~[?:?]
        at com.bergerkiller.mountiplex.reflection.util.FastMethod.invoke(FastMethod.java:122) ~[BKCommonLib.jar:?]
        at com.bergerkiller.mountiplex.reflection.declarations.Template$Method.invoke(Template.java:1506) ~[BKCommonLib.jar:?]
        at com.bergerkiller.mountiplex.reflection.declarations.Template$Method$Converted.invoke(Template.java:1627) ~[BKCommonLib.jar:?]
        at com.bergerkiller.generated.net.minecraft.server.WorldServerHandle$impl.removeEntity(Unknown Source) ~[?:?]
        at com.bergerkiller.bukkit.common.entity.CommonEntity.teleport(CommonEntity.java:574) ~[BKCommonLib.jar:?]
        at com.bergerkiller.bukkit.common.bases.ExtendedEntity.teleport(ExtendedEntity.java:1034) ~[BKCommonLib.jar:?]
        at com.bergerkiller.bukkit.tc.controller.MinecartGroup.teleportMember(MinecartGroup.java:619) ~[TrainCarts.jar:?]
        at com.bergerkiller.bukkit.tc.controller.MinecartGroup.teleport(MinecartGroup.java:602) ~[TrainCarts.jar:?]
        at com.bergerkiller.bukkit.tc.controller.MinecartGroup.teleport(MinecartGroup.java:585) ~[TrainCarts.jar:?]
        at com.bergerkiller.bukkit.tc.controller.MinecartGroup.teleportAndGo(MinecartGroup.java:559) ~[TrainCarts.jar:?]
        at com.bergerkiller.bukkit.tc.signactions.SignActionTeleport.execute(SignActionTeleport.java:129) ~[TrainCarts.jar:?]
        at com.bergerkiller.bukkit.tc.signactions.SignAction.executeAll(SignAction.java:279) ~[TrainCarts.jar:?]
[21:45:19] [Server thread/ERROR]: [Train_Carts] Failed to execute GROUP_ENTER for SignActionTeleport:
java.lang.IllegalStateException: Removing entity while ticking!
        at net.minecraft.server.v1_14_R1.WorldServer.removeEntity(WorldServer.java:1116) ~[spigot.jar:git-Spigot-a596182-3fc97f0]
        at com.bergerkiller.mountiplex.reflection.util.fast.GeneratedInvoker$mplgen2a7f601.invoke(Unknown Source) ~[?:?]
        at com.bergerkiller.mountiplex.reflection.util.FastMethod.invoke(FastMethod.java:122) ~[BKCommonLib.jar:?]
        at com.bergerkiller.mountiplex.reflection.declarations.Template$Method.invoke(Template.java:1506) ~[BKCommonLib.jar:?]
        at com.bergerkiller.mountiplex.reflection.declarations.Template$Method$Converted.invoke(Template.java:1627) ~[BKCommonLib.jar:?]
        at com.bergerkiller.generated.net.minecraft.server.WorldServerHandle$impl.removeEntity(Unknown Source) ~[?:?]
        at com.bergerkiller.bukkit.common.entity.CommonEntity.teleport(CommonEntity.java:574) ~[BKCommonLib.jar:?]
        at com.bergerkiller.bukkit.common.bases.ExtendedEntity.teleport(ExtendedEntity.java:1034) ~[BKCommonLib.jar:?]
        at com.bergerkiller.bukkit.tc.controller.MinecartGroup.teleportMember(MinecartGroup.java:619) ~[TrainCarts.jar:?]
        at com.bergerkiller.bukkit.tc.controller.MinecartGroup.teleport(MinecartGroup.java:602) ~[TrainCarts.jar:?]
        at com.bergerkiller.bukkit.tc.controller.MinecartGroup.teleport(MinecartGroup.java:585) ~[TrainCarts.jar:?]
        at com.bergerkiller.bukkit.tc.controller.MinecartGroup.teleportAndGo(MinecartGroup.java:559) ~[TrainCarts.jar:?]
        at com.bergerkiller.bukkit.tc.signactions.SignActionTeleport.execute(SignActionTeleport.java:129) ~[TrainCarts.jar:?]
        at com.bergerkiller.bukkit.tc.signactions.SignAction.executeAll(SignAction.java:279) ~[TrainCarts.jar:?]
[21:45:19] [Server thread/ERROR]: [Train_Carts] Failed to execute GROUP_ENTER for SignActionTeleport:
java.lang.IllegalStateException: Removing entity while ticking!
        at net.minecraft.server.v1_14_R1.WorldServer.removeEntity(WorldServer.java:1116) ~[spigot.jar:git-Spigot-a596182-3fc97f0]
        at com.bergerkiller.mountiplex.reflection.util.fast.GeneratedInvoker$mplgen2a7f601.invoke(Unknown Source) ~[?:?]
        at com.bergerkiller.mountiplex.reflection.util.FastMethod.invoke(FastMethod.java:122) ~[BKCommonLib.jar:?]
        at com.bergerkiller.mountiplex.reflection.declarations.Template$Method.invoke(Template.java:1506) ~[BKCommonLib.jar:?]
        at com.bergerkiller.mountiplex.reflection.declarations.Template$Method$Converted.invoke(Template.java:1627) ~[BKCommonLib.jar:?]
        at com.bergerkiller.generated.net.minecraft.server.WorldServerHandle$impl.removeEntity(Unknown Source) ~[?:?]
        at com.bergerkiller.bukkit.common.entity.CommonEntity.teleport(CommonEntity.java:574) ~[BKCommonLib.jar:?]
        at com.bergerkiller.bukkit.common.bases.ExtendedEntity.teleport(ExtendedEntity.java:1034) ~[BKCommonLib.jar:?]
        at com.bergerkiller.bukkit.tc.controller.MinecartGroup.teleportMember(MinecartGroup.java:619) ~[TrainCarts.jar:?]
        at com.bergerkiller.bukkit.tc.controller.MinecartGroup.teleport(MinecartGroup.java:602) ~[TrainCarts.jar:?]
        at com.bergerkiller.bukkit.tc.controller.MinecartGroup.teleport(MinecartGroup.java:585) ~[TrainCarts.jar:?]
        at com.bergerkiller.bukkit.tc.controller.MinecartGroup.teleportAndGo(MinecartGroup.java:559) ~[TrainCarts.jar:?]
        at com.bergerkiller.bukkit.tc.signactions.SignActionTeleport.execute(SignActionTeleport.java:129) ~[TrainCarts.jar:?]
        at com.bergerkiller.bukkit.tc.signactions.SignAction.executeAll(SignAction.java:279) ~[TrainCarts.jar:?]
[21:45:19] [Server thread/ERROR]: [Train_Carts] Failed to execute GROUP_ENTER for SignActionTeleport:
java.lang.IllegalStateException: Removing entity while ticking!
        at net.minecraft.server.v1_14_R1.WorldServer.removeEntity(WorldServer.java:1116) ~[spigot.jar:git-Spigot-a596182-3fc97f0]
        at com.bergerkiller.mountiplex.reflection.util.fast.GeneratedInvoker$mplgen2a7f601.invoke(Unknown Source) ~[?:?]
        at com.bergerkiller.mountiplex.reflection.util.FastMethod.invoke(FastMethod.java:122) ~[BKCommonLib.jar:?]
        at com.bergerkiller.mountiplex.reflection.declarations.Template$Method.invoke(Template.java:1506) ~[BKCommonLib.jar:?]
        at com.bergerkiller.mountiplex.reflection.declarations.Template$Method$Converted.invoke(Template.java:1627) ~[BKCommonLib.jar:?]
        at com.bergerkiller.generated.net.minecraft.server.WorldServerHandle$impl.removeEntity(Unknown Source) ~[?:?]
        at com.bergerkiller.bukkit.common.entity.CommonEntity.teleport(CommonEntity.java:574) ~[BKCommonLib.jar:?]
        at com.bergerkiller.bukkit.common.bases.ExtendedEntity.teleport(ExtendedEntity.java:1034) ~[BKCommonLib.jar:?]
        at com.bergerkiller.bukkit.tc.controller.MinecartGroup.teleportMember(MinecartGroup.java:619) ~[TrainCarts.jar:?]
        at com.bergerkiller.bukkit.tc.controller.MinecartGroup.teleport(MinecartGroup.java:602) ~[TrainCarts.jar:?]
        at com.bergerkiller.bukkit.tc.controller.MinecartGroup.teleport(MinecartGroup.java:585) ~[TrainCarts.jar:?]
        at com.bergerkiller.bukkit.tc.controller.MinecartGroup.teleportAndGo(MinecartGroup.java:559) ~[TrainCarts.jar:?]
        at com.bergerkiller.bukkit.tc.signactions.SignActionTeleport.execute(SignActionTeleport.java:129) ~[TrainCarts.jar:?]
        at com.bergerkiller.bukkit.tc.signactions.SignAction.executeAll(SignAction.java:279) ~[TrainCarts.jar:?]
[21:45:19] [Server thread/ERROR]: [Train_Carts] Failed to execute GROUP_ENTER for SignActionTeleport:
java.lang.IllegalStateException: Removing entity while ticking!
        at net.minecraft.server.v1_14_R1.WorldServer.removeEntity(WorldServer.java:1116) ~[spigot.jar:git-Spigot-a596182-3fc97f0]
        at com.bergerkiller.mountiplex.reflection.util.fast.GeneratedInvoker$mplgen2a7f601.invoke(Unknown Source) ~[?:?]
        at com.bergerkiller.mountiplex.reflection.util.FastMethod.invoke(FastMethod.java:122) ~[BKCommonLib.jar:?]
        at com.bergerkiller.mountiplex.reflection.declarations.Template$Method.invoke(Template.java:1506) ~[BKCommonLib.jar:?]
        at com.bergerkiller.mountiplex.reflection.declarations.Template$Method$Converted.invoke(Template.java:1627) ~[BKCommonLib.jar:?]
        at com.bergerkiller.generated.net.minecraft.server.WorldServerHandle$impl.removeEntity(Unknown Source) ~[?:?]
        at com.bergerkiller.bukkit.common.entity.CommonEntity.teleport(CommonEntity.java:574) ~[BKCommonLib.jar:?]
        at com.bergerkiller.bukkit.common.bases.ExtendedEntity.teleport(ExtendedEntity.java:1034) ~[BKCommonLib.jar:?]
        at com.bergerkiller.bukkit.tc.controller.MinecartGroup.teleportMember(MinecartGroup.java:619) ~[TrainCarts.jar:?]
        at com.bergerkiller.bukkit.tc.controller.MinecartGroup.teleport(MinecartGroup.java:602) ~[TrainCarts.jar:?]
        at com.bergerkiller.bukkit.tc.controller.MinecartGroup.teleport(MinecartGroup.java:585) ~[TrainCarts.jar:?]
        at com.bergerkiller.bukkit.tc.controller.MinecartGroup.teleportAndGo(MinecartGroup.java:559) ~[TrainCarts.jar:?]
        at com.bergerkiller.bukkit.tc.signactions.SignActionTeleport.execute(SignActionTeleport.java:129) ~[TrainCarts.jar:?]
        at com.bergerkiller.bukkit.tc.signactions.SignAction.executeAll(SignAction.java:279) ~[TrainCarts.jar:?]
[21:45:19] [Server thread/ERROR]: [Train_Carts] Failed to execute GROUP_ENTER for SignActionTeleport:
java.lang.IllegalStateException: Removing entity while ticking!
        at net.minecraft.server.v1_14_R1.WorldServer.removeEntity(WorldServer.java:1116) ~[spigot.jar:git-Spigot-a596182-3fc97f0]
        at com.bergerkiller.mountiplex.reflection.util.fast.GeneratedInvoker$mplgen2a7f601.invoke(Unknown Source) ~[?:?]
        at com.bergerkiller.mountiplex.reflection.util.FastMethod.invoke(FastMethod.java:122) ~[BKCommonLib.jar:?]
        at com.bergerkiller.mountiplex.reflection.declarations.Template$Method.invoke(Template.java:1506) ~[BKCommonLib.jar:?]
        at com.bergerkiller.mountiplex.reflection.declarations.Template$Method$Converted.invoke(Template.java:1627) ~[BKCommonLib.jar:?]
        at com.bergerkiller.generated.net.minecraft.server.WorldServerHandle$impl.removeEntity(Unknown Source) ~[?:?]
        at com.bergerkiller.bukkit.common.entity.CommonEntity.teleport(CommonEntity.java:574) ~[BKCommonLib.jar:?]
        at com.bergerkiller.bukkit.common.bases.ExtendedEntity.teleport(ExtendedEntity.java:1034) ~[BKCommonLib.jar:?]
        at com.bergerkiller.bukkit.tc.controller.MinecartGroup.teleportMember(MinecartGroup.java:619) ~[TrainCarts.jar:?]
        at com.bergerkiller.bukkit.tc.controller.MinecartGroup.teleport(MinecartGroup.java:602) ~[TrainCarts.jar:?]
        at com.bergerkiller.bukkit.tc.controller.MinecartGroup.teleport(MinecartGroup.java:585) ~[TrainCarts.jar:?]
        at com.bergerkiller.bukkit.tc.controller.MinecartGroup.teleportAndGo(MinecartGroup.java:559) ~[TrainCarts.jar:?]
        at com.bergerkiller.bukkit.tc.signactions.SignActionTeleport.execute(SignActionTeleport.java:129) ~[TrainCarts.jar:?]
        at com.bergerkiller.bukkit.tc.signactions.SignAction.executeAll(SignAction.java:279) ~[TrainCarts.jar:?]
[21:45:19] [Server thread/ERROR]: [Train_Carts] Failed to execute GROUP_ENTER for SignActionTeleport:
java.lang.IllegalStateException: Removing entity while ticking!
        at net.minecraft.server.v1_14_R1.WorldServer.removeEntity(WorldServer.java:1116) ~[spigot.jar:git-Spigot-a596182-3fc97f0]
        at com.bergerkiller.mountiplex.reflection.util.fast.GeneratedInvoker$mplgen2a7f601.invoke(Unknown Source) ~[?:?]
        at com.bergerkiller.mountiplex.reflection.util.FastMethod.invoke(FastMethod.java:122) ~[BKCommonLib.jar:?]
        at com.bergerkiller.mountiplex.reflection.declarations.Template$Method.invoke(Template.java:1506) ~[BKCommonLib.jar:?]
        at com.bergerkiller.mountiplex.reflection.declarations.Template$Method$Converted.invoke(Template.java:1627) ~[BKCommonLib.jar:?]
        at com.bergerkiller.generated.net.minecraft.server.WorldServerHandle$impl.removeEntity(Unknown Source) ~[?:?]
        at com.bergerkiller.bukkit.common.entity.CommonEntity.teleport(CommonEntity.java:574) ~[BKCommonLib.jar:?]
        at com.bergerkiller.bukkit.common.bases.ExtendedEntity.teleport(ExtendedEntity.java:1034) ~[BKCommonLib.jar:?]
        at com.bergerkiller.bukkit.tc.controller.MinecartGroup.teleportMember(MinecartGroup.java:619) ~[TrainCarts.jar:?]
        at com.bergerkiller.bukkit.tc.controller.MinecartGroup.teleport(MinecartGroup.java:602) ~[TrainCarts.jar:?]
        at com.bergerkiller.bukkit.tc.controller.MinecartGroup.teleport(MinecartGroup.java:585) ~[TrainCarts.jar:?]
        at com.bergerkiller.bukkit.tc.controller.MinecartGroup.teleportAndGo(MinecartGroup.java:559) ~[TrainCarts.jar:?]
        at com.bergerkiller.bukkit.tc.signactions.SignActionTeleport.execute(SignActionTeleport.java:129) ~[TrainCarts.jar:?]
        at com.bergerkiller.bukkit.tc.signactions.SignAction.executeAll(SignAction.java:279) ~[TrainCarts.jar:?]
[21:45:19] [Server thread/ERROR]: [Train_Carts] Failed to execute GROUP_ENTER for SignActionTeleport:
java.lang.IllegalStateException: Removing entity while ticking!
        at net.minecraft.server.v1_14_R1.WorldServer.removeEntity(WorldServer.java:1116) ~[spigot.jar:git-Spigot-a596182-3fc97f0]
        at com.bergerkiller.mountiplex.reflection.util.fast.GeneratedInvoker$mplgen2a7f601.invoke(Unknown Source) ~[?:?]
        at com.bergerkiller.mountiplex.reflection.util.FastMethod.invoke(FastMethod.java:122) ~[BKCommonLib.jar:?]
        at com.bergerkiller.mountiplex.reflection.declarations.Template$Method.invoke(Template.java:1506) ~[BKCommonLib.jar:?]
        at com.bergerkiller.mountiplex.reflection.declarations.Template$Method$Converted.invoke(Template.java:1627) ~[BKCommonLib.jar:?]
        at com.bergerkiller.generated.net.minecraft.server.WorldServerHandle$impl.removeEntity(Unknown Source) ~[?:?]
        at com.bergerkiller.bukkit.common.entity.CommonEntity.teleport(CommonEntity.java:574) ~[BKCommonLib.jar:?]
        at com.bergerkiller.bukkit.common.bases.ExtendedEntity.teleport(ExtendedEntity.java:1034) ~[BKCommonLib.jar:?]
        at com.bergerkiller.bukkit.tc.controller.MinecartGroup.teleportMember(MinecartGroup.java:619) ~[TrainCarts.jar:?]
        at com.bergerkiller.bukkit.tc.controller.MinecartGroup.teleport(MinecartGroup.java:602) ~[TrainCarts.jar:?]
        at com.bergerkiller.bukkit.tc.controller.MinecartGroup.teleport(MinecartGroup.java:585) ~[TrainCarts.jar:?]
        at com.bergerkiller.bukkit.tc.controller.MinecartGroup.teleportAndGo(MinecartGroup.java:559) ~[TrainCarts.jar:?]
        at com.bergerkiller.bukkit.tc.signactions.SignActionTeleport.execute(SignActionTeleport.java:129) ~[TrainCarts.jar:?]
        at com.bergerkiller.bukkit.tc.signactions.SignAction.executeAll(SignAction.java:279) ~[TrainCarts.jar:?]
[21:45:19] [Server thread/ERROR]: [Train_Carts] Failed to execute GROUP_ENTER for SignActionTeleport:
java.lang.IllegalStateException: Removing entity while ticking!
        at net.minecraft.server.v1_14_R1.WorldServer.removeEntity(WorldServer.java:1116) ~[spigot.jar:git-Spigot-a596182-3fc97f0]
        at com.bergerkiller.mountiplex.reflection.util.fast.GeneratedInvoker$mplgen2a7f601.invoke(Unknown Source) ~[?:?]
        at com.bergerkiller.mountiplex.reflection.util.FastMethod.invoke(FastMethod.java:122) ~[BKCommonLib.jar:?]
        at com.bergerkiller.mountiplex.reflection.declarations.Template$Method.invoke(Template.java:1506) ~[BKCommonLib.jar:?]
        at com.bergerkiller.mountiplex.reflection.declarations.Template$Method$Converted.invoke(Template.java:1627) ~[BKCommonLib.jar:?]
        at com.bergerkiller.generated.net.minecraft.server.WorldServerHandle$impl.removeEntity(Unknown Source) ~[?:?]
        at com.bergerkiller.bukkit.common.entity.CommonEntity.teleport(CommonEntity.java:574) ~[BKCommonLib.jar:?]
        at com.bergerkiller.bukkit.common.bases.ExtendedEntity.teleport(ExtendedEntity.java:1034) ~[BKCommonLib.jar:?]
        at com.bergerkiller.bukkit.tc.controller.MinecartGroup.teleportMember(MinecartGroup.java:619) ~[TrainCarts.jar:?]
        at com.bergerkiller.bukkit.tc.controller.MinecartGroup.teleport(MinecartGroup.java:602) ~[TrainCarts.jar:?]
        at com.bergerkiller.bukkit.tc.controller.MinecartGroup.teleport(MinecartGroup.java:585) ~[TrainCarts.jar:?]
        at com.bergerkiller.bukkit.tc.controller.MinecartGroup.teleportAndGo(MinecartGroup.java:559) ~[TrainCarts.jar:?]
        at com.bergerkiller.bukkit.tc.signactions.SignActionTeleport.execute(SignActionTeleport.java:129) ~[TrainCarts.jar:?]
        at com.bergerkiller.bukkit.tc.signactions.SignAction.executeAll(SignAction.java:279) ~[TrainCarts.jar:?]
[21:45:19] [Server thread/ERROR]: [Train_Carts] Failed to execute GROUP_ENTER for SignActionTeleport:
java.lang.IllegalStateException: Removing entity while ticking!
        at net.minecraft.server.v1_14_R1.WorldServer.removeEntity(WorldServer.java:1116) ~[spigot.jar:git-Spigot-a596182-3fc97f0]
        at com.bergerkiller.mountiplex.reflection.util.fast.GeneratedInvoker$mplgen2a7f601.invoke(Unknown Source) ~[?:?]
        at com.bergerkiller.mountiplex.reflection.util.FastMethod.invoke(FastMethod.java:122) ~[BKCommonLib.jar:?]
        at com.bergerkiller.mountiplex.reflection.declarations.Template$Method.invoke(Template.java:1506) ~[BKCommonLib.jar:?]
        at com.bergerkiller.mountiplex.reflection.declarations.Template$Method$Converted.invoke(Template.java:1627) ~[BKCommonLib.jar:?]
        at com.bergerkiller.generated.net.minecraft.server.WorldServerHandle$impl.removeEntity(Unknown Source) ~[?:?]
        at com.bergerkiller.bukkit.common.entity.CommonEntity.teleport(CommonEntity.java:574) ~[BKCommonLib.jar:?]
        at com.bergerkiller.bukkit.common.bases.ExtendedEntity.teleport(ExtendedEntity.java:1034) ~[BKCommonLib.jar:?]
        at com.bergerkiller.bukkit.tc.controller.MinecartGroup.teleportMember(MinecartGroup.java:619) ~[TrainCarts.jar:?]
        at com.bergerkiller.bukkit.tc.controller.MinecartGroup.teleport(MinecartGroup.java:602) ~[TrainCarts.jar:?]
        at com.bergerkiller.bukkit.tc.controller.MinecartGroup.teleport(MinecartGroup.java:585) ~[TrainCarts.jar:?]
        at com.bergerkiller.bukkit.tc.controller.MinecartGroup.teleportAndGo(MinecartGroup.java:559) ~[TrainCarts.jar:?]
        at com.bergerkiller.bukkit.tc.signactions.SignActionTeleport.execute(SignActionTeleport.java:129) ~[TrainCarts.jar:?]
        at com.bergerkiller.bukkit.tc.signactions.SignAction.executeAll(SignAction.java:279) ~[TrainCarts.jar:?]
[21:45:19] [Server thread/ERROR]: [Train_Carts] Failed to execute GROUP_ENTER for SignActionTeleport:
java.lang.IllegalStateException: Removing entity while ticking!
        at net.minecraft.server.v1_14_R1.WorldServer.removeEntity(WorldServer.java:1116) ~[spigot.jar:git-Spigot-a596182-3fc97f0]
        at com.bergerkiller.mountiplex.reflection.util.fast.GeneratedInvoker$mplgen2a7f601.invoke(Unknown Source) ~[?:?]
        at com.bergerkiller.mountiplex.reflection.util.FastMethod.invoke(FastMethod.java:122) ~[BKCommonLib.jar:?]
        at com.bergerkiller.mountiplex.reflection.declarations.Template$Method.invoke(Template.java:1506) ~[BKCommonLib.jar:?]
        at com.bergerkiller.mountiplex.reflection.declarations.Template$Method$Converted.invoke(Template.java:1627) ~[BKCommonLib.jar:?]
        at com.bergerkiller.generated.net.minecraft.server.WorldServerHandle$impl.removeEntity(Unknown Source) ~[?:?]
        at com.bergerkiller.bukkit.common.entity.CommonEntity.teleport(CommonEntity.java:574) ~[BKCommonLib.jar:?]
        at com.bergerkiller.bukkit.common.bases.ExtendedEntity.teleport(ExtendedEntity.java:1034) ~[BKCommonLib.jar:?]
        at com.bergerkiller.bukkit.tc.controller.MinecartGroup.teleportMember(MinecartGroup.java:619) ~[TrainCarts.jar:?]
        at com.bergerkiller.bukkit.tc.controller.MinecartGroup.teleport(MinecartGroup.java:602) ~[TrainCarts.jar:?]
        at com.bergerkiller.bukkit.tc.controller.MinecartGroup.teleport(MinecartGroup.java:585) ~[TrainCarts.jar:?]
        at com.bergerkiller.bukkit.tc.controller.MinecartGroup.teleportAndGo(MinecartGroup.java:559) ~[TrainCarts.jar:?]
        at com.bergerkiller.bukkit.tc.signactions.SignActionTeleport.execute(SignActionTeleport.java:129) ~[TrainCarts.jar:?]
        at com.bergerkiller.bukkit.tc.signactions.SignAction.executeAll(SignAction.java:279) ~[TrainCarts.jar:?]
[21:45:19] [Server thread/ERROR]: [Train_Carts] Failed to execute GROUP_ENTER for SignActionTeleport:
java.lang.IllegalStateException: Removing entity while ticking!
        at net.minecraft.server.v1_14_R1.WorldServer.removeEntity(WorldServer.java:1116) ~[spigot.jar:git-Spigot-a596182-3fc97f0]
        at com.bergerkiller.mountiplex.reflection.util.fast.GeneratedInvoker$mplgen2a7f601.invoke(Unknown Source) ~[?:?]
        at com.bergerkiller.mountiplex.reflection.util.FastMethod.invoke(FastMethod.java:122) ~[BKCommonLib.jar:?]
        at com.bergerkiller.mountiplex.reflection.declarations.Template$Method.invoke(Template.java:1506) ~[BKCommonLib.jar:?]
        at com.bergerkiller.mountiplex.reflection.declarations.Template$Method$Converted.invoke(Template.java:1627) ~[BKCommonLib.jar:?]
        at com.bergerkiller.generated.net.minecraft.server.WorldServerHandle$impl.removeEntity(Unknown Source) ~[?:?]
        at com.bergerkiller.bukkit.common.entity.CommonEntity.teleport(CommonEntity.java:574) ~[BKCommonLib.jar:?]
        at com.bergerkiller.bukkit.common.bases.ExtendedEntity.teleport(ExtendedEntity.java:1034) ~[BKCommonLib.jar:?]
        at com.bergerkiller.bukkit.tc.controller.MinecartGroup.teleportMember(MinecartGroup.java:619) ~[TrainCarts.jar:?]
        at com.bergerkiller.bukkit.tc.controller.MinecartGroup.teleport(MinecartGroup.java:602) ~[TrainCarts.jar:?]
        at com.bergerkiller.bukkit.tc.controller.MinecartGroup.teleport(MinecartGroup.java:585) ~[TrainCarts.jar:?]
        at com.bergerkiller.bukkit.tc.controller.MinecartGroup.teleportAndGo(MinecartGroup.java:559) ~[TrainCarts.jar:?]
        at com.bergerkiller.bukkit.tc.signactions.SignActionTeleport.execute(SignActionTeleport.java:129) ~[TrainCarts.jar:?]
        at com.bergerkiller.bukkit.tc.signactions.SignAction.executeAll(SignAction.java:279) ~[TrainCarts.jar:?]`

**Comment by bergerkiller** [comment]
Short update: I have been looking into it. Tick-delaying it when it is cross-world mitigates the errors but still causes the minecart to glitch out on the other end. This takes a little work to fix.

**Comment by bergerkiller** [comment]
Please check if these fixes restore teleport logic to former behavior. https://github.com/bergerhealer/TrainCarts/commit/c2cf5fa0a32aa9092185940093094b4a1d002f81 https://github.com/bergerhealer/BKCommonLib/commit/5586ae99f5863452971dbb0af66b40faee628769

https://ci.mg-dev.eu/job/BKCommonLib/602/
https://ci.mg-dev.eu/job/TrainCarts/510/

**Comment by flo210500** [comment]
Thanks now it works worlds internal and worlds cross with MyWorlds (MulitWorlds I haven't tested on yet)

**Comment by 24Emergency** [comment]
Great job, It works really fine. I've tried with both MyWorlds and MultiversePortal.
