### ISSUE TITLE
TrainCarts does not function using CatServer

### ISSUE THREAD

**Issue by wanou067** [bergerhealer/TrainCarts#312]
BkCommonLib version: Latest
 TrainCarts version: 1.12.2-v3
 Spigot version: Using Cat server

<hr>
Today, i'm contacting you because i can't use train-carts in my server.
I am using a catserver, an API that link forge and Spigot.
I am on 1.12.2
I don't use any mods/plugins that change minecarts
No plugins disabling chunk loading

This is the problem:
I installed the plugin and BkCommonLib,
When i run the command /cart, or /train it returns:
An internal error occured while attempting to perform this command

In the debug (logs with more details)
` [18:59:03] [Server thread/ERROR] [Minecraft]: Error occurred while enabling Train_Carts v1.12.2-v3 (Is it up to date?)
java.lang.NoClassDefFoundError: Could not initialize class com.bergerkiller.bukkit.common.Common
    at com.bergerkiller.bukkit.common.PluginBase.onEnable(PluginBase.java:687) ~[?:?]
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[JavaPlugin.class:git-Spigot-dcd1643-e60fc34]
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:327) [JavaPluginLoader.class:git-Spigot-dcd1643-e60fc34]
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [SimplePluginManager.class:git-Spigot-dcd1643-e60fc34]
    at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:434) [CraftServer.class:git-Spigot-dcd1643-e60fc34]
    at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:383) [CraftServer.class:git-Spigot-dcd1643-e60fc34]
    at net.minecraft.server.MinecraftServer.func_71243_i(MinecraftServer.java:476) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:431) [MinecraftServer.class:?]
    at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:388) [MinecraftServer.class:?]
    at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:327) [nz.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:600) [MinecraftServer.class:?]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72] 
`
I also tried with the latest version of train-carts but I got the same error.

Can someone help me please ? This mod seems to be very nice !

**Comment by bbayu123** [comment]
well first, report the issue using the latest version of traincarts (1.14.4-v1) instead of that, and paste the new error here

**Comment by bbayu123** [comment]
we don't guarantee that traincarts works on that, but we can take a look

**Comment by wanou067** [comment]
this is the error with the latest version of traincraft
`19:37:22] [Server thread/ERROR] [Minecraft]: Error occurred while enabling Train_Carts v1.14.4-v1 (Is it up to date?)
java.lang.NoClassDefFoundError: Could not initialize class com.bergerkiller.bukkit.common.Common
	at com.bergerkiller.bukkit.common.PluginBase.onEnable(PluginBase.java:687) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[JavaPlugin.class:git-Spigot-dcd1643-e60fc34]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:327) [JavaPluginLoader.class:git-Spigot-dcd1643-e60fc34]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [SimplePluginManager.class:git-Spigot-dcd1643-e60fc34]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:434) [CraftServer.class:git-Spigot-dcd1643-e60fc34]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:383) [CraftServer.class:git-Spigot-dcd1643-e60fc34]
	at net.minecraft.server.MinecraftServer.func_71243_i(MinecraftServer.java:476) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:431) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:388) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:327) [nz.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:600) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]`

**Comment by bbayu123** [comment]
Just to confirm what your "latest" means, do you have the latest BKCommonLib version, 1.14.4-v1?

**Comment by wanou067** [comment]
Yes, BKCommonLib-1.14.4-v1.jar

**Comment by bbayu123** [comment]
Ok, will have to check with developer to see whether TrainCarts is compatible with it.

@bergerkiller CatServer src https://github.com/CatServer/CatServer-Pro

**Comment by wanou067** [comment]
ok thanks you for your help

**Comment by bergerkiller** [comment]
Cat server is something completely new to me. There was forge support but when mcpc+ died that support has not been continued. I know too little about CatServer to tell whether I can support it, since I do need pretty deep ties with net.minecraft.server. MCPC+ offered a remapper to interface with, is such a thing available?

I do find it interesting as this could potentially allow traincarts to run in forge.

**Comment by bbayu123** [comment]
![image](https://user-images.githubusercontent.com/26726381/66230997-8fdd6180-e724-11e9-99fc-01258d5fb64a.png)
This is in the CatServer src code, does this help? @bergerkiller

**Comment by bergerkiller** [comment]
There is this: https://github.com/CatServer/CatServer-Pro/tree/master/src/main/java/catserver/server/remapper

So there might be options at the very least. I wish there was more history to this project, or some previous project that was forked and continued. I'd probably have to ask some of the authors how to use it.

**Comment by bergerkiller** [comment]
So unfortunately the remap portion of BKCommonLib has been completely dismantled. The only thing that works is remapping class paths. The method and field name remapper is only used by deprecated old classes like SafeField and SafeMethod. But, with a little effort, I may be able to correct that.

**Comment by bbayu123** [comment]
Since priority is low, will close this until further notice.

**Comment by bergerkiller** [comment]
Put in a vote for CatServer support on the Traincarts discord server for you. ( https://discord.gg/q9gutsN )
