### ISSUE TITLE
java.lang.NullPointerException: null

### ISSUE THREAD

**Issue by RavenHamster** [bergerhealer/TrainCarts#321]
##### Spigot version: PaperMC 234 (MC:1.14.4)

<hr>

#### Problem or bug:
I get a big Java error in the console sometimes when I sit down in a minecart.

`[12:44:49 FATAL]: Error executing task on Server
java.lang.NullPointerException: null
        at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1998) ~[patched_1.14.4.jar:git-Paper-234]
        at net.minecraft.server.v1_14_R1.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:51) ~[patched_1.14.4.jar:git-Paper-234]
        at net.minecraft.server.v1_14_R1.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:6) ~[patched_1.14.4.jar:git-Paper-234]
        at net.minecraft.server.v1_14_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.14.4.jar:git-Paper-234]
        at net.minecraft.server.v1_14_R1.TickTask.run(SourceFile:18) ~[patched_1.14.4.jar:git-Paper-234]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.14.4.jar:git-Paper-234]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.14.4.jar:git-Paper-234]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.14.4.jar:git-Paper-234]
        at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:1029) ~[patched_1.14.4.jar:git-Paper-234]
        at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:1022) ~[patched_1.14.4.jar:git-Paper-234]
        at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.14.4.jar:git-Paper-234]
        at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1006) ~[patched_1.14.4.jar:git-Paper-234]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:929) ~[patched_1.14.4.jar:git-Paper-234]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]`

#### Expected behaviour:
Well, I expect it not to be there. I should just be able to sit down in the minecart.

#### Steps to reproduce:
To my knowledge, it comes when you try to sit in the minecart. (EDIT: It only works if the user is not allowed to sit in the minecart. If playerenter is no for example or maybe the player is sitting in a minecart with playerexit no and tries to sit in another minecart!)

**Comment by bergerkiller** [comment]
Can you check whether or not this error still happens with the newest dev builds?

https://ci.mg-dev.eu/job/BKCommonLib/659/
https://ci.mg-dev.eu/job/TrainCarts/555/

**Comment by RavenHamster** [comment]
> Can you check whether or not this error still happens with the newest dev builds?
> 
> https://ci.mg-dev.eu/job/BKCommonLib/659/
> https://ci.mg-dev.eu/job/TrainCarts/555/

Hello! I did what you asked and the problem is still there.

**Comment by bergerkiller** [comment]
I can reproduce this, though it is weird, because the error comes from within the server itself. I'll see what I can do

**Comment by bergerkiller** [comment]
I think I fixed this issue on paperspigot. https://github.com/bergerhealer/BKCommonLib/commit/99a34fcc2a8508abd1f3adf35c3b9bf58e2a671b

Try it out: https://ci.mg-dev.eu/job/BKCommonLib/660/

**Comment by RavenHamster** [comment]
> I think I fixed this issue on paperspigot. [bergerhealer/BKCommonLib@99a34fc](https://github.com/bergerhealer/BKCommonLib/commit/99a34fcc2a8508abd1f3adf35c3b9bf58e2a671b)
> 
> Try it out: https://ci.mg-dev.eu/job/BKCommonLib/660/

Worked! Thank you so very much. Keep up the good work, I love all your plugins!
