### ISSUE TITLE
getting entity already tracked error

### ISSUE THREAD

**Issue by dauthiatull** [bergerhealer/TrainCarts#323]
##### Spigot version:1.14.4

<hr>

#### Problem or bug: sometimes getting entity already tracked error after shutting down server and restarting it. I cant reliably cause this so I have no idea what or when its going to happen but I can fix it by removing the trains.groupdata file from the folder and restarting the server. 

here is the error 
********
[11:44:48] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.server.v1_14_R1.ReportedException: Exception ticking world
        at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1081) ~[spigot-1.14.4.jar:git-Spigot-56f8471-eafd742]
        at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:393) ~[spigot-1.14.4.jar:git-Spigot-56f8471-eafd742]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:970) ~[spigot-1.14.4.jar:git-Spigot-56f8471-eafd742]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:815) [spigot-1.14.4.jar:git-Spigot-56f8471-eafd742]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_231]
Caused by: java.lang.IllegalStateException: Entity is already tracked!
        at net.minecraft.server.v1_14_R1.PlayerChunkMap.addEntity(PlayerChunkMap.java:990) ~[spigot-1.14.4.jar:git-Spigot-56f8471-eafd742]
        at net.minecraft.server.v1_14_R1.ChunkProviderServer.addEntity(ChunkProviderServer.java:505) ~[spigot-1.14.4.jar:git-Spigot-56f8471-eafd742]
        at net.minecraft.server.v1_14_R1.WorldServer.registerEntity(WorldServer.java:1134) ~[spigot-1.14.4.jar:git-Spigot-56f8471-eafd742]
        at net.minecraft.server.v1_14_R1.WorldServer.doTick(WorldServer.java:397) ~[spigot-1.14.4.jar:git-Spigot-56f8471-eafd742]
        at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1068) ~[spigot-1.14.4.jar:git-Spigot-56f8471-eafd742]
        ... 4 more
[11:44:48] [Server thread/ERROR]:       Cause of unexpected exception was
java.lang.IllegalStateException: Entity is already tracked!
        at net.minecraft.server.v1_14_R1.PlayerChunkMap.addEntity(PlayerChunkMap.java:990) ~[spigot-1.14.4.jar:git-Spigot-56f8471-eafd742]
        at net.minecraft.server.v1_14_R1.ChunkProviderServer.addEntity(ChunkProviderServer.java:505) ~[spigot-1.14.4.jar:git-Spigot-56f8471-eafd742]
        at net.minecraft.server.v1_14_R1.WorldServer.registerEntity(WorldServer.java:1134) ~[spigot-1.14.4.jar:git-Spigot-56f8471-eafd742]
        at net.minecraft.server.v1_14_R1.WorldServer.doTick(WorldServer.java:397) ~[spigot-1.14.4.jar:git-Spigot-56f8471-eafd742]
        at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1068) ~[spigot-1.14.4.jar:git-Spigot-56f8471-eafd742]
        at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:393) ~[spigot-1.14.4.jar:git-Spigot-56f8471-eafd742]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:970) ~[spigot-1.14.4.jar:git-Spigot-56f8471-eafd742]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:815) [spigot-1.14.4.jar:git-Spigot-56f8471-eafd742]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_231]
[11:44:48] [Server thread/ERROR]: This crash report has been saved to: C:\Users\I9beast\AppData\Roaming\.minecraft\spigot\.\crash-reports\crash-2019-12-22_11.44.48-server.txt
[11:44:48] [Server thread/INFO]: Stopping server
[11:44:48] [Server thread/INFO]: [Train_Carts] Disabling Train_Carts v1.14.4-v2-SNAPSHOT
[11:44:48] [Server thread/INFO]: [BKCommonLib] Train_Carts disabled!
[11:44:48] [Server thread/INFO]: [My_Worlds] Disabling My_Worlds v1.14.4-v1
[11:44:48] [Server thread/INFO]: [BKCommonLib] My_Worlds disabled!
[11:44:48] [Server thread/INFO]: [BKCommonLib] Disabling BKCommonLib v1.14.4-v2-SNAPSHOT
[11:44:48] [Server thread/INFO]: [CraftBook] Disabling CraftBook v3.10.1-SNAPSHOT;4545-df4dcf6
[11:44:48] [Server thread/INFO]: [CraftBook] Saving persistent data to YAML!
[11:44:48] [Server thread/INFO]: [WorldGuard] Disabling WorldGuard v7.0.1;f2118aa
[11:44:48] [Server thread/INFO]: [WorldGuard] Shutting down executor and cancelling any pending tasks...
[11:44:48] [Server thread/INFO]: [ProtocolLib] Disabling ProtocolLib v4.5.0-SNAPSHOT
[11:44:48] [Server thread/INFO]: [EasyBackup] Disabling EasyBackup v3.2.7
[11:44:48] [Server thread/INFO]: [TreeGravity] Disabling TreeGravity v4.2.2
[11:44:48] [Server thread/INFO]: [TreeGravity] TreeGravity disabled
[11:44:48] [Server thread/INFO]: [WorldEdit] Disabling WorldEdit v7.0.1;61bc012
[11:44:48] [Server thread/INFO]: Unregistering com.sk89q.worldedit.bukkit.BukkitServerInterface from WorldEdit
[11:44:48] [Server thread/INFO]: [dynmap] Disabling dynmap v3.0-beta-5-218
[11:44:48] [Server thread/INFO]: [dynmap] Unloaded 11 components.
[11:44:48] [Server thread/INFO]: [dynmap] Stopping map renderer...
[11:44:49] [Server thread/INFO]: [dynmap] Saved 4 pending tile renders in world 'world'
[11:44:49] [Server thread/INFO]: [dynmap] Disabled
[11:44:49] [Server thread/INFO]: Saving players
[11:44:49] [Server thread/INFO]: Dauthiatull lost connection: Server closed
[11:44:49] [Server thread/INFO]: Dauthiatull left the game
[11:44:49] [Server thread/INFO]: Saving worlds
[11:44:49] [Server thread/INFO]: Saving chunks for level 'world'/minecraft:overworld
[11:44:50] [Server thread/INFO]: ThreadedAnvilChunkStorage (world): All chunks are saved
[11:44:50] [Server thread/INFO]: Saving chunks for level 'world_nether'/minecraft:the_nether
[11:44:51] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[11:44:51] [Server thread/INFO]: Saving chunks for level 'world_the_end'/minecraft:the_end
[11:44:51] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[11:44:51] [Server thread/INFO]: ThreadedAnvilChunkStorage (world): All chunks are saved
[11:44:51] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[11:44:51] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
>Press any key to continue . . .

*********

**Comment by bergerkiller** [comment]
Im still not 100% sure that bkcommonlib or traincarts has anything to do with this error. The error is that the same entity with the same id exists twice on the server. It might be that Paperspigot deals with this issue a bit better, as I remember them adding more recovery steps for situations like this

**Comment by dauthiatull** [comment]
I did not turn keep chunk loaded so I dont know what the problem is
btw this is the error shown in the client 
internal exception: java.lang.IllegalStateException: asynchronous player tracker update

**Comment by bergerkiller** [comment]
That's weird, I've done a search through the server source code but can find no mention of 'asynchronous player tracker update' anywhere. Maybe this is a paperspigot specific error? Anything about that in the server log? A stack trace could help.

Asynchronous access is a big clue, as it could point to another plugin or packet handler calling into server code, causing problems

**Comment by dauthiatull** [comment]
hmmm I removed the file again so I could log in. naturally all trains lost their info. I distroyed the 1 train I was using 3 storage and 1 cart. there should be no other carts on the map and yet /train list shows 0 trains and 27 carts. I dont know where the game thinks those 27 carts are but that could be the problem. phantom carts

btw Im using spigot not paperspigot

**Comment by bergerkiller** [comment]
Definitely looks like addEntity() is called from another thread, this is a bit of a problem

**Comment by dauthiatull** [comment]
maybe something to do with portals? remember I could not get carts to go through portals without using myworlds portal signs. even when they were empty and not part of a train. I belive you said it was a problem with travle agent missing

I dont think I have another portal mod installed. 

mod list
bkcommonlib
bstats
craftbook
dynmap
easybackup
my_worlds
pluginmetrics
protolib
train_carts
treegravity
worldedit
worldguard

I do have a mini map mod on the client that allows teleport but this problem started 2 weeks before installing that

**Comment by dauthiatull** [comment]
is ther a way to see where the missing carts are located? I would like to see where they are in relation to portals

**Comment by bergerkiller** [comment]
Programmatically yeah, but I dont think there is a command for that in traincarts or vanilla minecraft

Are you teleporting trains using the portal signs, or using actual portal mechanics?

**Comment by dauthiatull** [comment]
signs because vanilla doesnt work when traincarts is installed for some reason

**Comment by bergerkiller** [comment]
Im almost certain there's something broken in that teleportation then. I don't know how often this error occurs, but can you check whether not doing such teleports causes the error to never occur again? If it occurred really rarely then you don't have to test that

**Comment by dauthiatull** [comment]
ok did some testing to confirm
cloned the spigot folder so not to mess with my main 
removed traincarts
went to a vinallia portal. (no sign)
carts would go through portal but not appear in nether
removed my worlds
carts go through as expected but cant ride them or make trains. (expected behavior )
re added traincarts 
carts do not go through portals
cant ride portals 
big error in the console (I will post it if you want)

this is interesting
used train distroyall
train list says 0 trains
0 carts

placed 1 cart
list says 1 train 1 cart
pushed it through portal and it didnt go through. got the console error AND 
trainlist now shows 1 train 
5 carts

its cloning the carts instead of porting them. thats where the phantom carts are coming from
hope this helps

**Comment by dauthiatull** [comment]
also if I distroy the cart in survival the list shows 0 trains and 4 carts even though it should be 0

**Comment by bergerkiller** [comment]
Thanks! That will definitely help me, I'll look into this first thing tomorrow. Minecraft does clone entities when teleporting, so yes, you have killed your pet wolf when going through a portal. Something probably is going wrong in this logic right now.

Cloning the same entity multiple times is definitely a recipe for disaster when it comes to that error

**Comment by dauthiatull** [comment]
i also went to different portals and did the list command and got different numbers at each did a destroy all at all of them hopefully that kills whatever ghost minecart that was being cloned. currently I should only ever see 1 train and 4 carts since thats all I have out an any one time. havent even used carts for farms

**Comment by dauthiatull** [comment]
update 
even after making sure there were no other carts on the server I still got the error and had to delete the traingroup file to be able to log in. 

it may take more testing to confirm but is seems to happen most often when logging out/in when near or possibly facing a train above a station sign

**Comment by bergerkiller** [comment]
Are you alone on the server when this happens? Were you near to the position trains teleport from/to, if teleporting occurred?

**Comment by dauthiatull** [comment]
alone and no trains were teleporting at the time I shut down the server after I log out. I then start the server and then login  next to the train which is sitting at the station but not moving . can be 20 ish blocks from a portal or be out of render of a portal. doesnt matter. 

I did just find out that its the train thats being cloned
I name the train t1 for the destinations signs
after the last crash i deleted the traingroup file and loged in
naturally I dad to break the carts since they were no longer a train
replaced the carts to make a new train
but when I tried to rename the train to t1 it says that name is already taken 
so its cloning the the train Im next to when I log out
the question is why
does the station sign (powered with a redstone torch) somehow try to overwrite the existing train thats sitting on it on login?

**Comment by dauthiatull** [comment]
did some testing

attempt 1
made 1 train
named it t1
push it onto station
loged out facing train
loged in....crashed
delete trains.groupdata
restart server
login 
break carts
make train 
name it t1 but name takin
break carts
/trains destroyall
make train 
name it t1; succsefull 
push it onto station
log out and stop server
restart and log in 
crash

attempt 2
made 1 train
named it t1
push it onto station
loged out facing train
loged in....crashed
delete trains.groupdata
restart server
login 

this time one of the carts were moving

break carts
make train 
name it t1 but name takin
break carts
/trains destroyall
make train 
name it t1; succsefull 
push it onto station
log out and stop server
restart and log in 
crash

attempt 3
made 1 train
named it t1

did not push it onto the station
log out and stop/ start server
login and no crash
push train onto station
log out and stop/start server
login 

crash
 seems to be something with the way stations work

I have station signs like this
[train]
station

on the side of the second block below the track with a redstone torch in front of it

if you want me to try something else let me know in detail. I im off for the holidays and have loads of time to help track this nasty down

**Comment by bergerkiller** [comment]
Thing you can test:

What happens if you destroy the station sign after the train 't1' is stopped on top of it? And then do the restart/login cycle? Does it crash your client then?

**Comment by dauthiatull** [comment]
did that
made train 
named t1
pushed onto station
broke station sign
restart server
crash

**Comment by dauthiatull** [comment]
I did find a work around which is to park trains off the station when shutting down the server

**Comment by dauthiatull** [comment]
I will do more tests if you like 
I wana kick this bugs ass LOL

**Comment by dauthiatull** [comment]
new test

tried logging out about63 ish blocks away with train out of view since its in a building and no crash

seems to only happen if I logout and restart server if im standing too close

**Comment by dauthiatull** [comment]
render issue maybe

**Comment by dauthiatull** [comment]
do minecarts naturally generate?

**Comment by bergerkiller** [comment]
Yes, they spawn in mineshafts

**Comment by dauthiatull** [comment]
doh that explains why when Im in other places without places carts that the train list command was showing carts lol

been trying to figure that out for 20 minutes.
I derped, nothing to see here, move along LOL

**Comment by bergerkiller** [comment]
Is there a possibility I can join your server to see this for myself? Can send me a message on discord or spigot forums

**Comment by bergerkiller** [comment]
So this turned out to be fixed in the later development builds, unsure what commit fixed it. Its important to mention this bugfix in next release changelog.
