### ISSUE TITLE
save error(?)

### ISSUE THREAD

**Issue by issac4892** [bergerhealer/TrainCarts#393]
## Info
Please provide the following information:

- BkCommonLib Version (`/train version`): 
- TrainCarts Version (`/train version`): 
- Server Type and Version (`/version`):
[월, 31. 8월 2020 18:57:47 KST INFO] Train_Carts: v1.16.1-v1 (build: 696)
[월, 31. 8월 2020 18:57:47 KST INFO] BKCommonLib: v1.16.1-v1 (build: 838)
[월, 31. 8월 2020 18:57:47 KST INFO] Server: git-TacoSpigot-"f8ba67d6" (MC: 1.12.2)
----
### Description
It seems to fail to save

### Expected behaviour
Save and no error or warn

### Actual behaviour
Error, making it hard to see the console

### Steps to reproduce
Open server, play, and traincart starts to save, and the bug(keep happens

### Additional Information
LOG
```
[월, 31. 8월 2020 18:48:26 KST ERROR] [BKCommonLib] [Configuration] An error occured while saving to file 'plugins/Train_Carts/TrainProperties.yml':
[월, 31. 8월 2020 18:48:26 KST WARN] java.nio.file.NoSuchFileException: /mnt/01D679212D0A4DE0/해피데이서버 버킷/plugins/Train_Carts/TrainProperties.yml.1598867305486.tmp -> plugins/Train_Carts/TrainProperties.yml
[월, 31. 8월 2020 18:48:26 KST WARN]     at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
[월, 31. 8월 2020 18:48:26 KST WARN]     at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
[월, 31. 8월 2020 18:48:26 KST WARN]     at sun.nio.fs.UnixCopyFile.move(UnixCopyFile.java:396)
[월, 31. 8월 2020 18:48:26 KST WARN]     at sun.nio.fs.UnixFileSystemProvider.move(UnixFileSystemProvider.java:262)
[월, 31. 8월 2020 18:48:26 KST WARN]     at java.nio.file.Files.move(Files.java:1395)
[월, 31. 8월 2020 18:48:26 KST WARN]     at com.bergerkiller.bukkit.common.io.AsyncTextWriter$1.move(AsyncTextWriter.java:160)
[월, 31. 8월 2020 18:48:26 KST WARN]     at com.bergerkiller.bukkit.common.io.AsyncTextWriter$1.apply(AsyncTextWriter.java:152)
[월, 31. 8월 2020 18:48:26 KST WARN]     at com.bergerkiller.bukkit.common.io.AsyncTextWriter$1.apply(AsyncTextWriter.java:142)
[월, 31. 8월 2020 18:48:26 KST WARN]     at java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:836)
[월, 31. 8월 2020 18:48:26 KST WARN]     at java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:811)
[월, 31. 8월 2020 18:48:26 KST WARN]     at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
[월, 31. 8월 2020 18:48:26 KST WARN]     at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1975)
[월, 31. 8월 2020 18:48:26 KST WARN]     at com.bergerkiller.bukkit.common.io.AsyncTextWriter$5.next(AsyncTextWriter.java:286)
[월, 31. 8월 2020 18:48:26 KST WARN]     at com.bergerkiller.bukkit.common.io.AsyncTextWriter$AsyncTestWriterStepWriter.completed(AsyncTextWriter.java:339)
[오후 6:48]
[월, 31. 8월 2020 18:48:26 KST WARN]     at com.bergerkiller.bukkit.common.io.AsyncTextWriter$AsyncTestWriterStepWriter.completed(AsyncTextWriter.java:298)
[월, 31. 8월 2020 18:48:26 KST WARN]     at sun.nio.ch.Invoker.invokeUnchecked(Invoker.java:126)
[월, 31. 8월 2020 18:48:26 KST WARN]     at sun.nio.ch.SimpleAsynchronousFileChannelImpl$3.run(SimpleAsynchronousFileChannelImpl.java:389)
[월, 31. 8월 2020 18:48:26 KST WARN]     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[월, 31. 8월 2020 18:48:26 KST WARN]     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[월, 31. 8월 2020 18:48:26 KST WARN]     at java.lang.Thread.run(Thread.java:748)
```

**Comment by bergerkiller** [comment]
Could this be because of the unicode characters in the file path?

**Comment by issac4892** [comment]
It didn't make any troubles when it was at windows, and we moved to ubuntu and the problem started.

**Comment by issac4892** [comment]
the folder is in ntfs

**Comment by bergerkiller** [comment]
Does 'TrainProperties.yml.1598867305486.tmp' exist in the folder where it tried to save?

**Comment by issac4892** [comment]
well.. we went back to windows and it came back ;)
