### ISSUE TITLE
Could not pass event MemberSeatExitEvent

### ISSUE THREAD

**Issue by ErythroCraft** [bergerhealer/TrainCarts#444]
## Info
Please provide the following information:

    [18:57:21] [Server thread/INFO]: Train_Carts: v1.18.2-v2-SNAPSHOT (build: 1100)
    [18:57:21] [Server thread/INFO]: BKCommonLib: v1.18.2-v2-SNAPSHOT (build: 1277)
    [18:57:21] [Server thread/INFO]: Server: 3482-Spigot-42b6152-e87f2e3 (MC: 1.18.2)

----
## Bug
    [18:31:05] [Server thread/ERROR]: Could not pass event MemberSeatExitEvent to Train_Carts v1.18.2-v2-SNAPSHOT
    org.bukkit.event.EventException: null
            at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-api-1.18.2-R0.1 SNAPSHOT.jar:?]
            at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-api-1.18.2-R0.1-SNAPSHOT.jar:?]
            at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-api-1.18.2-R0.1- SNAPSHOT.jar:?]
            at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-api-1.18.2-R0.1-SNAPSHOT.jar:?]
            at com.bergerkiller.bukkit.common.utils.CommonUtil.callEvent(CommonUtil.java:171) ~[?:?]
            at com.bergerkiller.bukkit.tc.TCSeatChangeListener.lambda$onVehicleExit$1(TCSeatChangeListener.java:360) ~[?:?]
            at 
    com.bergerkiller.bukkit.common.internal.CommonNextTickExecutor$ExecutorTask.run(CommonNextTickExecutor.java:164) ~ 
    [?:?]
            at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftTask.run(CraftTask.java:82) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3482-Spigot- 42b6152-e87f2e3]
            at org.bukkit.craftbukkit.v1_18_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:415) ~[spigot-1.18.2- R0.1-SNAPSHOT.jar:3482-Spigot-42b6152-e87f2e3]
            at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1285) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3482-Spigot-42b6152- e87f2e3]
            at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:429) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3482-Spigot-42b6152-e87f2e3]
            at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1237) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3482-Spigot-42b6152-e87f2e3]
            at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1047) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3482-Spigot-42b6152-e87f2e3]
            at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304) ~[spigot-1.18.2-R0.1-SNAPSHOT.jar:3482-Spigot-42b6152-e87f2e3]
            at java.lang.Thread.run(Thread.java:833) [?:?]

    Caused by: java.lang.NullPointerException: Cannot invoke "com.bergerkiller.bukkit.common.math.Matrix4x4.clone()" because the return value of "com.bergerkiller.bukkit.tc.attachments.control.CartAttachmentSeat.getTransform()" is null
            at com.bergerkiller.bukkit.tc.attachments.control.CartAttachmentSeat.getEjectPosition(CartAttachmentSeat.java:769) ~[?:?]
            at com.bergerkiller.bukkit.tc.TCSeatChangeListener.onMemberSeatExitHandleEjectOffset(TCSeatChangeListener.java:128) ~[?:?]
            at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
            at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
            at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
            at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
            at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-api-1.18.2-R0.1-SNAPSHOT.jar:?]      
    ... 14 more

### Description
I was doing nothing. Server console generates this bug self.

### Expected behaviour
    ------------------------
### Actual behaviour
What is TrainCarts doing instead?

### Steps to reproduce
    ------------------------

### Additional Information
    ------------------------

**Comment by bergerkiller** [comment]
Should be fixed if you update the jar to latest jenkins build of tc

**Comment by ErythroCraft** [comment]
Ok. I'll test it. Thanks.
