### ISSUE TITLE
Failed to restore 1 keep-chunks-loaded trains in time!

### ISSUE THREAD

**Issue by PatrickBronke** [bergerhealer/TrainCarts#449]
## Info
Please provide the following information:

- BkCommonLib Version (`1.19-v1`): 
- TrainCarts Version (`1.19-v2`): 
- Server Type and Version (`1.19`):

----
```
[21:12:34] [Server thread/ERROR]: [Train_Carts] Failed to restore 1 keep-chunks-loaded trains in time!
[21:12:34] [Server thread/ERROR]: [Train_Carts] Trains: train2
```

### Description
I'm trying to run a train from one station to another. The chunks must remain loaded so that the train does not stop. At some point the message described above appears in the console and the train simply stops on the track. Unfortunately, it never lasts that long. Sometimes the message comes in 1 hour, sometimes in 15 minutes. What can i do?

**Comment by bergerkiller** [comment]
What the message means is the following:

On startup, and whenever new worlds are loaded, it looks at all trains known to exist on that world that have keepchunksloaded true. It then starts loading all the chunks near these trains **asynchronously** and loads the trains in as the chunks load in.

The 'in time' is litterally: it will spend at most 10 minutes time loading all these chunks. If it actually takes longer than 10 minutes one or multiple of these things must be true:
- The server hardware is too slow / failing hard drive causing chunk loading to take too long
- Youre using Spigot rather than Paper, where chunk loading is significantly slower
- You have way too many trains on the world that keep chunks loaded
- You have so many trains that keep chunks loaded the server runs out of memory and everything slows down, including chunk loading
- There is a glitch in the server itself causing asynchronous chunk load tickets to not complete for some reason

**Comment by bergerkiller** [comment]
That said, a train that's already loaded, that you're inside of, should not stop. So that's a little weird. its still worth checking whether using Paper (if you arent already using it) fixes things

**Comment by PatrickBronke** [comment]
I using Paper. Now I got the next error:
[21:13:07 ERROR]: [Train_Carts] Failed to perform physics on train 'train4' at world_-34_64_818:
[21:13:07 ERROR]: [Train_Carts] null
java.util.ConcurrentModificationException: null
        at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1013) ~[?:?]
        at java.util.ArrayList$Itr.next(ArrayList.java:967) ~[?:?]
        at com.bergerkiller.bukkit.common.collections.List2DIterator.next(List2DIterator.java:53) ~[BKCommonLib-1.19-v1-1334.jar:?]
        at com.bergerkiller.bukkit.tc.controller.components.SignTracker.tryUpdateActiveSigns(SignTracker.java:157) ~[TrainCarts-1.19-v2-1141.jar:?]
        at com.bergerkiller.bukkit.tc.controller.components.SignTracker.updateActiveSigns(SignTracker.java:116) ~[TrainCarts-1.19-v2-1141.jar:?]
        at com.bergerkiller.bukkit.tc.controller.components.SignTrackerGroup.refresh(SignTrackerGroup.java:191) ~[TrainCarts-1.19-v2-1141.jar:?]
        at com.bergerkiller.bukkit.tc.controller.MinecartGroup.doPhysics_step(MinecartGroup.java:1563) ~[TrainCarts-1.19-v2-1141.jar:?]
        at com.bergerkiller.bukkit.tc.controller.MinecartGroup.doPhysics(MinecartGroup.java:1492) ~[TrainCarts-1.19-v2-1141.jar:?]
        at com.bergerkiller.bukkit.tc.controller.MinecartMember.onTick(MinecartMember.java:2304) ~[TrainCarts-1.19-v2-1141.jar:?]
        at com.bergerkiller.bukkit.common.internal.hooks.EntityHook.onTick(EntityHook.java:152) ~[BKCommonLib-1.19-v1-1334.jar:?]
        at com.bergerkiller.mountiplex.reflection.util.fast.GeneratedInvoker$mplgen13cdb4bc.invokeVA(Unknown Source) ~[?:?]
        at com.bergerkiller.mountiplex.reflection.ClassInterceptor$CallbackMethodInterceptor.invokeVA(ClassInterceptor.java:524) ~[BKCommonLib-1.19-v1-1334.jar:?]
        at com.bergerkiller.mountiplex.reflection.util.fast.Invoker.invoke(Invoker.java:29) ~[BKCommonLib-1.19-v1-1334.jar:?]
        at net.minecraft.world.entity.vehicle.EntityMinecartRideable$mplgen109e2493.k(Unknown Source) ~[?:?]
        at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:1155) ~[?:?]
        at net.minecraft.world.level.Level.guardEntityTick(Level.java:898) ~[?:?]
        at net.minecraft.server.level.ServerLevel.lambda$tick$6(ServerLevel.java:692) ~[?:?]
        at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:42) ~[paper-1.19.jar:git-Paper-61]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:672) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1551) ~[paper-1.19.jar:git-Paper-61]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:446) ~[paper-1.19.jar:git-Paper-61]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1414) ~[paper-1.19.jar:git-Paper-61]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1187) ~[paper-1.19.jar:git-Paper-61]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:302) ~[paper-1.19.jar:git-Paper-61]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by bbayu123** [comment]
Closing issue, stale, likely irrelevant in latest release. Please add a comment if you're still having this issue.
