### ISSUE TITLE
Cannot invoke "Object.getClass()" because "o" is null

### ISSUE THREAD

**Issue by Leonardus123** [bergerhealer/TrainCarts#469]
## Info
Please provide the following information:

- BkCommonLib Version 1.19.3-v1
- TrainCarts Version 1.19.3-v1
- Server Type and Version git-Purpur-1918 (MC: 1.19.3)

----
### Description
[13:58:00] [Server thread/INFO]: [Train_Carts] Loading server plugin Train_Carts v1.19.3-v1
[13:58:00] [Server thread/ERROR]: [Train_Carts] [Preloader] Failed to update class loader registry
java.lang.NullPointerException: Cannot invoke "Object.getClass()" because "o" is null
	at jdk.internal.reflect.UnsafeFieldAccessorImpl.ensureObj(UnsafeFieldAccessorImpl.java:57) ~[?:?]
	at jdk.internal.reflect.UnsafeQualifiedObjectFieldAccessorImpl.get(UnsafeQualifiedObjectFieldAccessorImpl.java:38) ~[?:?]
	at java.lang.reflect.Field.get(Field.java:425) ~[?:?]
	at com.bergerkiller.bukkit.tc.Preloader.setLoaderPluginField(Preloader.java:350) ~[TrainCarts-1.19.3-v1-1278.jar:?]
	at com.bergerkiller.bukkit.tc.Preloader.onLoad(Preloader.java:173) ~[TrainCarts-1.19.3-v1-1278.jar:?]
	at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59) ~[purpur-1.19.3.jar:git-Purpur-1918]
	at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18) ~[purpur-1.19.3.jar:git-Purpur-1918]
	at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:36) ~[purpur-1.19.3.jar:git-Purpur-1918]
	at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:37) ~[purpur-1.19.3.jar:git-Purpur-1918]
	at org.bukkit.craftbukkit.v1_19_R2.CraftServer.loadPlugins(CraftServer.java:443) ~[purpur-1.19.3.jar:git-Purpur-1918]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:309) ~[purpur-1.19.3.jar:git-Purpur-1918]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1117) ~[purpur-1.19.3.jar:git-Purpur-1918]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[purpur-1.19.3.jar:git-Purpur-1918]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[13:58:00] [Server thread/ERROR]: [Train_Carts] [Preloader] Failed to update class loader registry
java.lang.NullPointerException: Cannot invoke "Object.getClass()" because "o" is null
	at jdk.internal.reflect.UnsafeFieldAccessorImpl.ensureObj(UnsafeFieldAccessorImpl.java:57) ~[?:?]
	at jdk.internal.reflect.UnsafeQualifiedObjectFieldAccessorImpl.get(UnsafeQualifiedObjectFieldAccessorImpl.java:38) ~[?:?]
	at java.lang.reflect.Field.get(Field.java:425) ~[?:?]
	at com.bergerkiller.bukkit.tc.Preloader.setLoaderPluginField(Preloader.java:350) ~[TrainCarts-1.19.3-v1-1278.jar:?]
	at com.bergerkiller.bukkit.tc.Preloader.swapPluginFieldEverywhere(Preloader.java:283) ~[TrainCarts-1.19.3-v1-1278.jar:?]
	at com.bergerkiller.bukkit.tc.Preloader.onLoad(Preloader.java:188) ~[TrainCarts-1.19.3-v1-1278.jar:?]
	at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59) ~[purpur-1.19.3.jar:git-Purpur-1918]
	at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18) ~[purpur-1.19.3.jar:git-Purpur-1918]
	at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:36) ~[purpur-1.19.3.jar:git-Purpur-1918]
	at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:37) ~[purpur-1.19.3.jar:git-Purpur-1918]
	at org.bukkit.craftbukkit.v1_19_R2.CraftServer.loadPlugins(CraftServer.java:443) ~[purpur-1.19.3.jar:git-Purpur-1918]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:309) ~[purpur-1.19.3.jar:git-Purpur-1918]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1117) ~[purpur-1.19.3.jar:git-Purpur-1918]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[purpur-1.19.3.jar:git-Purpur-1918]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[13:58:00] [Server thread/ERROR]: [Train_Carts] [Preloader] Failed to fully register the plugin into the server
java.lang.IllegalStateException: Preloader does not exist in plugins list
	at com.bergerkiller.bukkit.tc.Preloader.swapPluginFieldEverywhere(Preloader.java:296) ~[TrainCarts-1.19.3-v1-1278.jar:?]
	at com.bergerkiller.bukkit.tc.Preloader.onLoad(Preloader.java:188) ~[TrainCarts-1.19.3-v1-1278.jar:?]
	at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59) ~[purpur-1.19.3.jar:git-Purpur-1918]
	at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18) ~[purpur-1.19.3.jar:git-Purpur-1918]
	at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:36) ~[purpur-1.19.3.jar:git-Purpur-1918]
	at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:37) ~[purpur-1.19.3.jar:git-Purpur-1918]
	at org.bukkit.craftbukkit.v1_19_R2.CraftServer.loadPlugins(CraftServer.java:443) ~[purpur-1.19.3.jar:git-Purpur-1918]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:309) ~[purpur-1.19.3.jar:git-Purpur-1918]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1117) ~[purpur-1.19.3.jar:git-Purpur-1918]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[purpur-1.19.3.jar:git-Purpur-1918]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

### Additional Information
- Start parameter: 
ExecStart=/usr/lib/jvm/java-17-amazon-corretto/bin/java -Xms10G -Xmx10G --add-modules=jdk.incubator.vector -jar purpur.jar --nogui

- Add plugins: 
ajStartCommands	2.0.3
Bell Tower	1.2.6
Big Doors	0.1.8.43
BKCommonLib	1.19.3-v1
BSL Shader	8.2.02
Chunky 	1.3.52
ChunkyBorder 	1.1.42
Citizens2	2.0.30-b2936
Citizens Sentinel	2.7.2-b504
CitizensText	1.20
Dynmap	3.5-beta-2
Dynmap-WorldGuard	1.4 beta 1
LightPerms	2.1.3
MCA Sselector	2.1
Multiverse-Core	4.3.1
Multiverse-NetherPortals	4.2.2
Multiverse-Portals	4.2.1
Multiverse-Sign-Porter	4 2 0
OptiFine	1.19.3 HD U I2 pre5
Purpur	1.19.3 1918
Shopkeepers	2.16.4
Spark	1.10.29
Spellbound Weapons Data Pack	4.0.1e
Splatus Datapack Resources	12
The Menagerie Moons	Dec 23rd, 2021
TrainCarts	1.19.3-v1
ViaBackwards	4.5.1
ViaVersion	4.5.1
VoidGen	2.2.1
WorldEdit	7.2.13
WorldGuard	7.0.8 beta 1

**Comment by bergerkiller** [comment]
Oh no not here too.

Paper changed the plugin loader. Download dev builds from https://ci.mg-dev.eu

**Comment by bergerkiller** [comment]
I've uploaded a new update to spigot and modrinth
