### ISSUE TITLE
Signs not working in 1.19.4

### ISSUE THREAD

**Issue by GewoneJongen** [bergerhealer/TrainCarts#475]
## Info
Please provide the following information:

- BkCommonLib Version (`/train version`): v1.19.4-v1 (build: 1371)
- TrainCarts Version (`/train version`): v1.19.4-v1 (build 1547)
- Server Type and Version (`/version`): 3760-spigot7d7b241-1f2dd8e (MC: 1.19.4)

----
### Description
When i want to create a station sign, nothing happens. I typed this on the sign:

-----------
[!train]
station
-----------

And other types of signs are also not working.

### Expected behaviour
In older versions it does create a station, and the trains do stop.

### Actual behaviour
The sign does nothing. And the train does not stop at the sign

### Steps to reproduce
1. Place the sign under the rails
2. Type: **[!train]** on the first line
3. Type **station** on the second line

### Additional Information
The server console gives a error message saying:
[Server thread/WARN]: Initializing Legacy Material Support. Unless you have legacy plugins and/or data this is a bug!

And also:
```
[Server thread/ERROR]: Could not pass event BlockPlaceEvent to Train_Carts v1.19.4-v1
261 | org.bukkit.event.EventException: null
262 | at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-api-1.19.4-R0.1-SNAPSHOT.jar:?]
263 | at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-api-1.19.4-R0.1-SNAPSHOT.jar:?]
264 | at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[spigot-api-1.19.4-R0.1-SNAPSHOT.jar:?]
265 | at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[spigot-api-1.19.4-R0.1-SNAPSHOT.jar:?]
266 | at org.bukkit.craftbukkit.v1_19_R3.event.CraftEventFactory.callBlockPlaceEvent(CraftEventFactory.java:416) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3760-Spigot-7d7b241-1f2dd8e]
267 | at net.minecraft.world.item.ItemStack.useOn(ItemStack.java:352) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3760-Spigot-7d7b241-1f2dd8e]
268 | at net.minecraft.server.level.PlayerInteractManager.a(PlayerInteractManager.java:556) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3760-Spigot-7d7b241-1f2dd8e]
269 | at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1637) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3760-Spigot-7d7b241-1f2dd8e]
270 | at net.minecraft.network.protocol.game.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3760-Spigot-7d7b241-1f2dd8e]
271 | at net.minecraft.network.protocol.game.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3760-Spigot-7d7b241-1f2dd8e]
272 | at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:31) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3760-Spigot-7d7b241-1f2dd8e]
273 | at net.minecraft.server.TickTask.run(SourceFile:18) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3760-Spigot-7d7b241-1f2dd8e]
274 | at net.minecraft.util.thread.IAsyncTaskHandler.d(SourceFile:156) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3760-Spigot-7d7b241-1f2dd8e]
275 | at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(SourceFile:23) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3760-Spigot-7d7b241-1f2dd8e]
276 | at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1154) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3760-Spigot-7d7b241-1f2dd8e]
277 | at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:1) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3760-Spigot-7d7b241-1f2dd8e]
278 | at net.minecraft.util.thread.IAsyncTaskHandler.x(SourceFile:130) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3760-Spigot-7d7b241-1f2dd8e]
279 | at net.minecraft.server.MinecraftServer.bi(MinecraftServer.java:1133) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3760-Spigot-7d7b241-1f2dd8e]
280 | at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1126) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3760-Spigot-7d7b241-1f2dd8e]
281 | at net.minecraft.util.thread.IAsyncTaskHandler.c(SourceFile:139) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3760-Spigot-7d7b241-1f2dd8e]
282 | at net.minecraft.server.MinecraftServer.i_(MinecraftServer.java:1110) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3760-Spigot-7d7b241-1f2dd8e]
283 | at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1021) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3760-Spigot-7d7b241-1f2dd8e]
284 | at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3760-Spigot-7d7b241-1f2dd8e]
285 | at java.lang.Thread.run(Unknown Source) ~[?:?]
286 | Caused by: java.lang.NullPointerException: Cannot invoke "org.bukkit.craftbukkit.v1_19_R3.block.sign.CraftSignSide.getLines()" because "this.front" is null
287 | at org.bukkit.craftbukkit.v1_19_R3.block.CraftSign.getLines(CraftSign.java:28) ~[spigot-1.19.4-R0.1-SNAPSHOT.jar:3760-Spigot-7d7b241-1f2dd8e]
288 | at com.bergerkiller.bukkit.tc.controller.global.SignController.onBlockPlaceSignCheck(SignController.java:305) ~[?:?]
289 | at jdk.internal.reflect.GeneratedMethodAccessor40.invoke(Unknown Source) ~[?:?]
290 | at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
291 | at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
292 | at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-api-1.19.4-R0.1-SNAPSHOT.jar:?]
293 | ... 23 more
```

**Comment by bbayu123** [comment]
Update BKCommonLib to build 1563. This is already fixed.
