### ISSUE TITLE
Failed to perform physics

### ISSUE THREAD

**Issue by amalon** [bergerhealer/TrainCarts#491]
## Info
Please provide the following information:

- BkCommonLib Version (`/train version`): v1.20.4-v1 (build: 1663)
- TrainCarts Version (`/train version`):  v1.20.4-v1 (build: 1518)
- Server Type and Version (`/version`): git-Paper-65 (MC: 1.20.1)

----
### Description
I'm regularly getting trains misbehaving, getting split up at a particular junction. Something I've noticed is that on server startup I often see this sort of message:
```
[20:10:33 ERROR]: [Train_Carts] Failed to perform physics on train 'train_circle3' at club_170_62_-98:                
[20:10:33 ERROR]: [Train_Carts] Index 0 out of bounds for length 0            
java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0                
        at com.bergerkiller.bukkit.tc.controller.components.RailPath.getStartPosition(RailPath.java:90) ~[TrainCarts-1.20.4-v1-1518.jar:?]                                                                                                  
        at com.bergerkiller.bukkit.tc.controller.components.ObstacleTracker.hardEnterNewMutexZoneIfInside(ObstacleTracker.java:259) ~[TrainCarts-1.20.4-v1-1518.jar:?]                                                                      
        at com.bergerkiller.bukkit.tc.controller.components.ObstacleTracker.update(ObstacleTracker.java:95) ~[TrainCarts-1.20.4-v1-1518.jar:?]                                                                                              
        at com.bergerkiller.bukkit.tc.controller.MinecartGroup.doPhysics_step(MinecartGroup.java:2026) ~[TrainCarts-1.20.4-v1-1518.jar:?]                                                                                                   
        at com.bergerkiller.bukkit.tc.controller.MinecartGroup.doPhysics(MinecartGroup.java:1853) ~[TrainCarts-1.20.4-v1-1518.jar:?]                                                                                                        
        at com.bergerkiller.bukkit.tc.controller.MinecartGroupStore.doFixedTick(MinecartGroupStore.java:40) ~[TrainCarts-1.20.4-v1-1518.jar:?]                                                                                              
        at com.bergerkiller.bukkit.tc.controller.global.TrainUpdateController$TrainUpdateTask.run(TrainUpdateController.java:225) ~[TrainCarts-1.20.4-v1-1518.jar:?]                                                                        
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.1.jar:git-Paper-65]                                                                                                                             at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480) ~[paper-1.20.1.jar:git-Paper-65]                                                                                                   at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1480) ~[paper-1.20.1.jar:git-Paper-65]                                                                                                                    
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:447) ~[paper-1.20.1.jar:git-Paper-65]                                                                                                           
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1394) ~[paper-1.20.1.jar:git-Paper-65]                                                                                                                      
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1171) ~[paper-1.20.1.jar:git-Paper-65]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.1.jar:git-Paper-65]                                                                                                                    
        at java.lang.Thread.run(Thread.java:1623) ~[?:?]                                                                                                                                             
```

Around here I often find trains queued up, and when I investigate it looks like trains have gone through an spmutex without seeing it, i.e. /train status doesn't say entering or entered the mutex, and then got stuck facing another train coming from the other way (for which /train status says entered mutex).

It often seems to work for quite a while when the server is up, and then go wrong when it shuts down and comes back up again. Anyway, I don't know if the above back trace is any help. Happy to try and figure out more details if not.

Thanks

**Comment by bergerkiller** [comment]
For some reason one of the path elements is empty, or zero-length. Might be a strange tc-coasters node that isnt properly connected perhaps? This at least fixes that error but it may not fix all problems

https://ci.mg-dev.eu/job/TrainCarts/1520/

**Comment by amalon** [comment]
Those coordinates are very near a junction that appears to span multiple TCCoasters CSV files. One of them has the junction and 3 links, another has one of the links as a root and links to the junction. Is it possibly a race between tcc loading and train physics?

I'll give that snapshot a go tomorrow and see if it helps.
Thanks again!

**Comment by bergerkiller** [comment]
Unlikely as tcc tracks are basically globally always available. Unlike vanilla track it doesnt lazy load any of it. But there might be some weird glitch that causes a zero-length path segment to sneak in somehow.

**Comment by amalon** [comment]
I haven't seen the failed to perform physics error any more, though trains are still splitting. I've found the debug option to log splits and get a fair few on server start, for reasons Next cart is derailed and End of rails reached before finding next cart. Looking at coordinates though (after trains moved on) doesn't show anything unusual, just at random bits of track)

**Comment by bergerkiller** [comment]
These messages also show detailed pathing information / coordinates which can help in figuring out <why> the path suddenly ends. The last position (exact position) is important. Can you stand at such a position, look all the way down, and make a screenshot? Then also include the full details logged

**Comment by bergerkiller** [comment]
This seems to be a bug in tc-coasters, because it doesnt find the coaster rail at { -806.5/63.9375/608.2989 } despite a rail clearly being there. Its also possibly a caching problem if it cached rail info at that position and tcc didnt invalidate that cache when loading up.

Ill make a build later today that makes traincarts completely invalidate the rail cache on startup to see if that already helps things along

**Comment by bergerkiller** [comment]
Let's first see if this resolves the problem. If not, Ill probably have to look at TCC's code

https://ci.mg-dev.eu/job/TrainCarts/1524/

**Comment by amalon** [comment]
Thanks, I updated traincarts to 1524. Unfortunately there doesn't seem to be any difference in behaviour. First time there were a few messages but no splits (not many trains), but I spawned a bunch of trains and on 2nd server restart several of them did get split up, including one which I think was right over a set of points.

**Comment by bergerkiller** [comment]
[TCCoasters-1.20.4-v2-SNAPSHOT-NO-CI.zip](https://github.com/bergerhealer/TrainCarts/files/13836013/TCCoasters-1.20.4-v2-SNAPSHOT-NO-CI.zip)
Can you try with this build of TCC? Added a track rebuild after initializing for a world to see if it helps any.

**Comment by amalon** [comment]
Thanks. The updated TCC definitely seems to have prevented the splitting. Trains left over the switcher reload where they were without any splitting messages in the log.

The way I was reproducing was by queuing trains up to the spmutex region you helped me fix before. The trains queue just past and over a switcher. I can reproduce a presumably separate issue where even though a train is in the spmutex region, the train(s) waiting immediately start moving into the spmutex on server start. Curiously in this case 2/4 trains say entered same region via different signs, and the other 1 says approaching even though all 3 are well inside it (I can open a separate issue for that if you like).

**Comment by bergerkiller** [comment]
Ah thats great! Of course I still havent found the real issue but now I know where to look. I might need you to test another build later with more specific fixes, but if I cant narrow it down, I can leave the current fix in place.

Reason I want a more specific fix is because the problem has to do with loading new coasters, and currently it might still be broken when csv files are loaded in for the first time.

**Comment by amalon** [comment]
Retesting is no problem, it was fairly easy to reproduce.

**Comment by bergerkiller** [comment]
Had another look on the github and I think what I fixed was actually the only problem there was. It just wasn't "building" the track data when loading a world, so by the time traincarts enables none of the rails were linked.

I need to adjust the fix a little bit but other than that, I think that was the main problem.

I thought I already did this somewhere but apparently not 😅

**Comment by bergerkiller** [comment]
https://ci.mg-dev.eu/job/TC%20Coasters/334/ this is a complete, proper fix

**Comment by amalon** [comment]
thanks, after a quick try, 334 seems as effective as the NOCI build at preventing the splitting
