### ISSUE TITLE
An error occurred while enabling in 1.21

### ISSUE THREAD

**Issue by mjl1010** [bergerhealer/TrainCarts#499]
## Info
Please provide the following information:

- BkCommonLib Version (`/train version`): v1.21-v1-SNAPSHOT-1750
- TrainCarts Version (`/train version`): v1.21-v1-SNAPSHOT-1575
- Server Type and Version (`/version`): Paper version 1.21-37-master@dd49fba (2024-06-24T02:08:49Z) (Implementing API version 1.21-R0.1-SNAPSHOT)

----
## Bug
```
[22:47:09] [Server thread/INFO]: [Train_Carts] Enabling Train_Carts v1.21-v1-SNAPSHOT
[22:47:11] [Server thread/ERROR]: [Train_Carts] An error occurred while enabling, the plugin will be disabled:
java.lang.ExceptionInInitializerError: null
	at BKCommonLib-1.21-v1-SNAPSHOT-1750.jar/com.bergerkiller.bukkit.common.dep.cloud.bukkit.internal.MinecraftArgumentTypes$ArgumentTypeGetterImpl.lambda$new$0(MinecraftArgumentTypes.java:85) ~[BKCommonLib-1.21-v1-SNAPSHOT-1750.jar:?]
	at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:181) ~[guava-32.1.2-jre.jar:?]
	at BKCommonLib-1.21-v1-SNAPSHOT-1750.jar/com.bergerkiller.bukkit.common.dep.cloud.bukkit.internal.MinecraftArgumentTypes$ArgumentTypeGetterImpl.getClassByKey(MinecraftArgumentTypes.java:98) ~[BKCommonLib-1.21-v1-SNAPSHOT-1750.jar:?]
	at BKCommonLib-1.21-v1-SNAPSHOT-1750.jar/com.bergerkiller.bukkit.common.dep.cloud.bukkit.internal.MinecraftArgumentTypes.getClassByKey(MinecraftArgumentTypes.java:70) ~[BKCommonLib-1.21-v1-SNAPSHOT-1750.jar:?]
	at BKCommonLib-1.21-v1-SNAPSHOT-1750.jar/com.bergerkiller.bukkit.common.dep.cloud.bukkit.internal.BukkitBrigadierMapper.registerUUID(BukkitBrigadierMapper.java:132) ~[BKCommonLib-1.21-v1-SNAPSHOT-1750.jar:?]
	at BKCommonLib-1.21-v1-SNAPSHOT-1750.jar/com.bergerkiller.bukkit.common.dep.cloud.bukkit.internal.BukkitBrigadierMapper.registerBuiltInMappings(BukkitBrigadierMapper.java:82) ~[BKCommonLib-1.21-v1-SNAPSHOT-1750.jar:?]
	at BKCommonLib-1.21-v1-SNAPSHOT-1750.jar/com.bergerkiller.bukkit.common.dep.cloud.paper.ModernPaperBrigadier.<init>(ModernPaperBrigadier.java:118) ~[BKCommonLib-1.21-v1-SNAPSHOT-1750.jar:?]
	at BKCommonLib-1.21-v1-SNAPSHOT-1750.jar/com.bergerkiller.bukkit.common.dep.cloud.paper.LegacyPaperCommandManager.registerBrigadier(LegacyPaperCommandManager.java:174) ~[BKCommonLib-1.21-v1-SNAPSHOT-1750.jar:?]
	at BKCommonLib-1.21-v1-SNAPSHOT-1750.jar/com.bergerkiller.bukkit.common.dep.cloud.paper.LegacyPaperCommandManager.registerBrigadier(LegacyPaperCommandManager.java:141) ~[BKCommonLib-1.21-v1-SNAPSHOT-1750.jar:?]
	at BKCommonLib-1.21-v1-SNAPSHOT-1750.jar/com.bergerkiller.bukkit.common.cloud.CloudSimpleHandler.enable(CloudSimpleHandler.java:134) ~[BKCommonLib-1.21-v1-SNAPSHOT-1750.jar:?]
	at TrainCarts-1.21-v1-SNAPSHOT-1575.jar/com.bergerkiller.bukkit.tc.commands.Commands.enable(Commands.java:104) ~[TrainCarts-1.21-v1-SNAPSHOT-1575.jar:?]
	at TrainCarts-1.21-v1-SNAPSHOT-1575.jar/com.bergerkiller.bukkit.tc.TrainCarts.enable(TrainCarts.java:750) ~[TrainCarts-1.21-v1-SNAPSHOT-1575.jar:?]
	at BKCommonLib-1.21-v1-SNAPSHOT-1750.jar/com.bergerkiller.bukkit.common.PluginBase.onEnable(PluginBase.java:861) ~[BKCommonLib-1.21-v1-SNAPSHOT-1750.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.21.jar:1.21-37-dd49fba]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.21.jar:1.21-37-dd49fba]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:629) ~[paper-1.21.jar:1.21-37-dd49fba]
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:578) ~[paper-1.21.jar:1.21-37-dd49fba]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:690) ~[paper-1.21.jar:1.21-37-dd49fba]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:452) ~[paper-1.21.jar:1.21-37-dd49fba]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:327) ~[paper-1.21.jar:1.21-37-dd49fba]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1157) ~[paper-1.21.jar:1.21-37-dd49fba]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.jar:1.21-37-dd49fba]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.RuntimeException: java.lang.NoSuchMethodException: net.minecraft.resources.ResourceLocation.<init>(java.lang.String)
	at BKCommonLib-1.21-v1-SNAPSHOT-1750.jar/com.bergerkiller.bukkit.common.dep.cloud.bukkit.internal.CraftBukkitReflection.needConstructor(CraftBukkitReflection.java:202) ~[BKCommonLib-1.21-v1-SNAPSHOT-1750.jar:?]
	at BKCommonLib-1.21-v1-SNAPSHOT-1750.jar/com.bergerkiller.bukkit.common.dep.cloud.bukkit.internal.RegistryReflection.<clinit>(RegistryReflection.java:54) ~[BKCommonLib-1.21-v1-SNAPSHOT-1750.jar:?]
	... 25 more
Caused by: java.lang.NoSuchMethodException: net.minecraft.resources.ResourceLocation.<init>(java.lang.String)
	at java.base/java.lang.Class.getConstructor0(Class.java:3761) ~[?:?]
	at java.base/java.lang.Class.getDeclaredConstructor(Class.java:2930) ~[?:?]
	at BKCommonLib-1.21-v1-SNAPSHOT-1750.jar/com.bergerkiller.bukkit.common.dep.cloud.bukkit.internal.CraftBukkitReflection.needConstructor(CraftBukkitReflection.java:200) ~[BKCommonLib-1.21-v1-SNAPSHOT-1750.jar:?]
	at BKCommonLib-1.21-v1-SNAPSHOT-1750.jar/com.bergerkiller.bukkit.common.dep.cloud.bukkit.internal.RegistryReflection.<clinit>(RegistryReflection.java:54) ~[BKCommonLib-1.21-v1-SNAPSHOT-1750.jar:?]
	... 25 more
[22:47:11] [Server thread/INFO]: [Train_Carts] Disabling Train_Carts v1.21-v1-SNAPSHOT
```

### Description
It just doesn't start.

### Expected behaviour
Let it start properly and be able to carry trains! Thanks a lot.

### Actual behaviour
It just doesn't start.

### Steps to reproduce
Start a server with Paper 1.21 with this plugins: BKCommonLib, CommandHook, ChestShop, CMILib, dynmap, Elevator, Essentials, EssentialsChat, EssentialsSpawn, GSit, *iConomy, ItemEdit, *MySQLAPI, NBTAPI, NoPlugins, NoSpawnerChange, NoteBlockAPI, *PermissionsEx, ProtocolLib, Residence, SignLink, SimpleClans, SkinsRestorer, Train_Carts, UltimateTimber, Vault, WorldEdit and ZeroTickStopper.

### Additional Information
It just links to: [https://github.com/bergerhealer/BKCommonLib/issues/169](https://github.com/bergerhealer/BKCommonLib/issues/169)

**Comment by bergerkiller** [comment]
Can you try with https://ci.mg-dev.eu/job/BKCommonLib/1751/ ?

**Comment by mjl1010** [comment]
```
[23:36:41 INFO]: [Train_Carts] Enabling Train_Carts v1.21-v1-SNAPSHOT
[23:36:44 ERROR]: [Train_Carts] An error occurred while enabling, the plugin will be disabled:
java.lang.IllegalArgumentException: WATER isn't an item
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:143) ~[guava-32.1.2-jre.jar:?]
        at org.bukkit.inventory.ItemStack.of(ItemStack.java:58) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:138) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:117) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.inventory.ItemStack.<init>(ItemStack.java:104) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at BKCommonLib-1.21-v1-SNAPSHOT-1752.jar/com.bergerkiller.bukkit.common.utils.RecipeUtil.getFurnaceResult(RecipeUtil.java:92) ~[BKCommonLib-1.21-v1-SNAPSHOT-1752.jar:?]
        at BKCommonLib-1.21-v1-SNAPSHOT-1752.jar/com.bergerkiller.bukkit.common.utils.RecipeUtil.isHeatableItem(RecipeUtil.java:84) ~[BKCommonLib-1.21-v1-SNAPSHOT-1752.jar:?]
        at BKCommonLib-1.21-v1-SNAPSHOT-1752.jar/com.bergerkiller.bukkit.common.utils.MaterialUtil$1.get(MaterialUtil.java:377) ~[BKCommonLib-1.21-v1-SNAPSHOT-1752.jar:?]
        at BKCommonLib-1.21-v1-SNAPSHOT-1752.jar/com.bergerkiller.bukkit.common.utils.MaterialUtil$1.get(MaterialUtil.java:374) ~[BKCommonLib-1.21-v1-SNAPSHOT-1752.jar:?]
        at BKCommonLib-1.21-v1-SNAPSHOT-1752.jar/com.bergerkiller.bukkit.common.MaterialBooleanProperty.getMaterials(MaterialBooleanProperty.java:29) ~[BKCommonLib-1.21-v1-SNAPSHOT-1752.jar:?]
        at BKCommonLib-1.21-v1-SNAPSHOT-1752.jar/com.bergerkiller.bukkit.common.MaterialBooleanProperty.toString(MaterialBooleanProperty.java:40) ~[BKCommonLib-1.21-v1-SNAPSHOT-1752.jar:?]
        at TrainCarts-1.21-v1-SNAPSHOT-1575.jar/com.bergerkiller.bukkit.tc.TCConfig.load(TCConfig.java:550) ~[TrainCarts-1.21-v1-SNAPSHOT-1575.jar:?]
        at TrainCarts-1.21-v1-SNAPSHOT-1575.jar/com.bergerkiller.bukkit.tc.TrainCarts.loadConfig(TrainCarts.java:664) ~[TrainCarts-1.21-v1-SNAPSHOT-1575.jar:?]
        at TrainCarts-1.21-v1-SNAPSHOT-1575.jar/com.bergerkiller.bukkit.tc.TrainCarts.enable(TrainCarts.java:769) ~[TrainCarts-1.21-v1-SNAPSHOT-1575.jar:?]
        at BKCommonLib-1.21-v1-SNAPSHOT-1752.jar/com.bergerkiller.bukkit.common.PluginBase.onEnable(PluginBase.java:861) ~[BKCommonLib-1.21-v1-SNAPSHOT-1752.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.21.jar:1.21-37-dd49fba]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.21.jar:1.21-37-dd49fba]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:629) ~[paper-1.21.jar:1.21-37-dd49fba]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:578) ~[paper-1.21.jar:1.21-37-dd49fba]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:690) ~[paper-1.21.jar:1.21-37-dd49fba]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:452) ~[paper-1.21.jar:1.21-37-dd49fba]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:327) ~[paper-1.21.jar:1.21-37-dd49fba]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1157) ~[paper-1.21.jar:1.21-37-dd49fba]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.jar:1.21-37-dd49fba]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
[23:36:44 INFO]: [Train_Carts] Disabling Train_Carts v1.21-v1-SNAPSHOT
```
No more errors of BKCommonLib :)

**Comment by bergerkiller** [comment]
Looks like paper added a change to disallow 'illegal' items, somehow I didnt see this error though. Will have to fix some stuff in bkcommonlib to check for this with an isItem() api they added in material.

**Comment by bergerkiller** [comment]
give it a try https://ci.mg-dev.eu/job/BKCommonLib/1753/

**Comment by mjl1010** [comment]
It works! Thank you very much!
![imagen](https://github.com/bergerhealer/TrainCarts/assets/6048575/91eb388e-3feb-4f43-86ae-f4c65f524589)
