### ISSUE TITLE
Error on startup (Can not set java.util.List)

### ISSUE THREAD

**Issue by MrPufferFish** [bergerhealer/TrainCarts#62]
##### Spigot version: 1.9.2-R0.1-SNAPSHOT

The error below occour on startup.

<hr>
[18:12:45] [Server thread/INFO]: [Train_Carts] Enabling Train_Carts v1.75-SNAPSHOT
[18:12:45] [Server thread/INFO]: [Train_Carts] 0 Trains have been loaded in 0 worlds. (0 Minecarts)
[18:12:45] [Server thread/WARN]: java.lang.IllegalArgumentException: Can not set java.util.List field net.minecraft.server.v1_9_R1.EntityTrackerEntry.w to net.minecraft.server.v1_9_R1.EntityMinecartRideable$$EnhancerByCGLIB$$913d68f
[18:12:45] [Server thread/WARN]: 	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167)
[18:12:45] [Server thread/WARN]: 	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171)
[18:12:45] [Server thread/WARN]: 	at sun.reflect.UnsafeObjectFieldAccessorImpl.set(UnsafeObjectFieldAccessorImpl.java:81)
[18:12:45] [Server thread/WARN]: 	at java.lang.reflect.Field.set(Field.java:764)
[18:12:45] [Server thread/WARN]: 	at com.bergerkiller.bukkit.common.reflection.SafeField.set(SafeField.java:129)
[18:12:45] [Server thread/WARN]: 	at com.bergerkiller.bukkit.common.reflection.TranslatorFieldAccessor.setInternal(TranslatorFieldAccessor.java:57)
[18:12:45] [Server thread/WARN]: 	at com.bergerkiller.bukkit.common.reflection.TranslatorFieldAccessor.set(TranslatorFieldAccessor.java:67)
[18:12:45] [Server thread/WARN]: 	at com.bergerkiller.bukkit.common.entity.CommonEntity.replaceEntity(CommonEntity.java:294)
[18:12:45] [Server thread/WARN]: 	at com.bergerkiller.bukkit.common.entity.CommonEntity.prepareHook(CommonEntity.java:236)
[18:12:45] [Server thread/WARN]: 	at com.bergerkiller.bukkit.common.entity.CommonEntity.setController(CommonEntity.java:354)
[18:12:45] [Server thread/WARN]: 	at com.bergerkiller.bukkit.tc.controller.MinecartMemberStore.convert(MinecartMemberStore.java:115)
[18:12:45] [Server thread/WARN]: 	at com.bergerkiller.bukkit.tc.controller.MinecartMemberStore.convertAll(MinecartMemberStore.java:57)
[18:12:45] [Server thread/WARN]: 	at com.bergerkiller.bukkit.tc.TrainCarts.enable(TrainCarts.java:516)
[18:12:45] [Server thread/WARN]: 	at com.bergerkiller.bukkit.common.PluginBase.onEnable(PluginBase.java:756)
[18:12:45] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292)
[18:12:45] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)
[18:12:45] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[18:12:45] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.loadPlugin(CraftServer.java:361)
[18:12:45] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.enablePlugins(CraftServer.java:321)
[18:12:45] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R1.MinecraftServer.t(MinecraftServer.java:411)
[18:12:45] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R1.MinecraftServer.l(MinecraftServer.java:376)
[18:12:45] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R1.MinecraftServer.a(MinecraftServer.java:331)
[18:12:45] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R1.DedicatedServer.init(DedicatedServer.java:269)
[18:12:45] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:527)
[18:12:45] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[18:12:45] [Server thread/INFO]: [Train_Carts] 0 detector rail regions loaded covering 0 blocks
[18:12:45] [Server thread/INFO]: [Train_Carts] Restoring trains and loading nearby chunks...

**Comment by harm27** [comment]
Traincarts doesn't support spigot 1.0 yet.
