### ISSUE TITLE
1.9 branch startup woes

### ISSUE THREAD

**Issue by RyanHecht** [bergerhealer/TrainCarts#75]
##### Spigot version: 1.9.2

<hr>
First off, let me say thank you for the recent frequent updates to the 1.9 branch. I'm glad we're getting closer and closer to a working product. Keep up the great work! :)
#### Problem or bug: 
Less than five minutes after startup, when only BKCommonLib and TrainCarts are loaded, the server crashes with this error (It does NOT happen when BKCommonLib is installed, but not TrainCarts)
>  Encountered an unexpected exception
java.lang.RuntimeException: Error generating crash report
        at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:783) ~[spigot222.jar:git-Spigot-e000104-4cb3258]
        at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) ~[spigot222.jar:git-Spigot-e000104-4cb3258]
        at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) ~[spigot222.jar:git-Spigot-e000104-4cb3258]
        at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [spigot222.jar:git-Spigot-e000104-4cb3258]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_77]
Caused by: java.lang.NoClassDefFoundError: Could not initialize class net.minecraft.server.v1_9_R1.CrashReport
        at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:781) ~[spigot222.jar:git-Spigot-e000104-4cb3258]
        ... 4 more
[23:19:31 ERROR]:       Cause of unexpected exception was
java.lang.NoClassDefFoundError: Could not initialize class net.minecraft.server.v1_9_R1.CrashReport
        at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:781) ~[spigot222.jar:git-Spigot-e000104-4cb3258]
        at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) ~[spigot222.jar:git-Spigot-e000104-4cb3258]
        at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) ~[spigot222.jar:git-Spigot-e000104-4cb3258]
        at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [spigot222.jar:git-Spigot-e000104-4cb3258]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_77]

On a related note: in one instance, in an attempt to save my world before the server crashed, I ran /save-all. This was the output: 

> [22:10:28] [Server thread/INFO]: An unknown error occurred while attempting to perform this command
[22:10:28] [Server thread/WARN]: Unknown CommandBlock failed to handle command
java.lang.NoClassDefFoundError: Could not initialize class net.minecraft.server.v1_9_R1.CrashReport
	at net.minecraft.server.v1_9_R1.Entity.e(Entity.java:1352) ~[spigot222.jar:git-Spigot-e000104-4cb3258]
	at com.bergerkiller.bukkit.common.entity.nms.NMSEntityHookImpl.d(NMSEntityHookImpl.java:101) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_77]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_77]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_77]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_77]
	at com.bergerkiller.bukkit.common.reflection.gen.ProxyCallbackMethod.invoke(ProxyCallbackMethod.java:19) ~[?:?]
	at com.bergerkiller.bukkit.common.reflection.ClassBuilder$CallbackMethodInterceptor.intercept(ClassBuilder.java:225) ~[?:?]
	at net.minecraft.server.v1_9_R1.EntityMinecartChest$$EnhancerByCGLIB$$b650eddc.d(<generated>) ~[?:?]
	at net.minecraft.server.v1_9_R1.ChunkRegionLoader.a(ChunkRegionLoader.java:262) ~[spigot222.jar:git-Spigot-e000104-4cb3258]
	at net.minecraft.server.v1_9_R1.ChunkRegionLoader.a(ChunkRegionLoader.java:130) ~[spigot222.jar:git-Spigot-e000104-4cb3258]
	at net.minecraft.server.v1_9_R1.ChunkProviderServer.saveChunk(ChunkProviderServer.java:244) ~[spigot222.jar:git-Spigot-e000104-4cb3258]
	at net.minecraft.server.v1_9_R1.ChunkProviderServer.a(ChunkProviderServer.java:267) ~[spigot222.jar:git-Spigot-e000104-4cb3258]
	at net.minecraft.server.v1_9_R1.WorldServer.save(WorldServer.java:1014) ~[spigot222.jar:git-Spigot-e000104-4cb3258]
	at net.minecraft.server.v1_9_R1.CommandSaveAll.execute(SourceFile:36) ~[spigot222.jar:git-Spigot-e000104-4cb3258]
	at org.bukkit.craftbukkit.v1_9_R1.command.VanillaCommandWrapper.dispatchVanillaCommand(VanillaCommandWrapper.java:108) [spigot222.jar:git-Spigot-e000104-4cb3258]
	at org.bukkit.craftbukkit.v1_9_R1.command.VanillaCommandWrapper.execute(VanillaCommandWrapper.java:43) [spigot222.jar:git-Spigot-e000104-4cb3258]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot222.jar:git-Spigot-e000104-4cb3258]
	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.dispatchCommand(CraftServer.java:645) [spigot222.jar:git-Spigot-e000104-4cb3258]
	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.dispatchServerCommand(CraftServer.java:631) [spigot222.jar:git-Spigot-e000104-4cb3258]
	at net.minecraft.server.v1_9_R1.DedicatedServer.aL(DedicatedServer.java:438) [spigot222.jar:git-Spigot-e000104-4cb3258]
	at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:401) [spigot222.jar:git-Spigot-e000104-4cb3258]
	at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) [spigot222.jar:git-Spigot-e000104-4cb3258]
	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [spigot222.jar:git-Spigot-e000104-4cb3258]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_77]
[22:10:49] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.RuntimeException: Error generating crash report
	at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:783) ~[spigot222.jar:git-Spigot-e000104-4cb3258]
	at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) ~[spigot222.jar:git-Spigot-e000104-4cb3258]
	at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) ~[spigot222.jar:git-Spigot-e000104-4cb3258]
	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [spigot222.jar:git-Spigot-e000104-4cb3258]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_77]
Caused by: java.lang.NoClassDefFoundError: Could not initialize class net.minecraft.server.v1_9_R1.CrashReport
	at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:781) ~[spigot222.jar:git-Spigot-e000104-4cb3258]
	... 4 more
[22:10:49] [Server thread/ERROR]: 	Cause of unexpected exception was
java.lang.NoClassDefFoundError: Could not initialize class net.minecraft.server.v1_9_R1.CrashReport
	at net.minecraft.server.v1_9_R1.MinecraftServer.D(MinecraftServer.java:781) ~[spigot222.jar:git-Spigot-e000104-4cb3258]
	at net.minecraft.server.v1_9_R1.DedicatedServer.D(DedicatedServer.java:400) ~[spigot222.jar:git-Spigot-e000104-4cb3258]
	at net.minecraft.server.v1_9_R1.MinecraftServer.C(MinecraftServer.java:660) ~[spigot222.jar:git-Spigot-e000104-4cb3258]
	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:559) [spigot222.jar:git-Spigot-e000104-4cb3258]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_77]

**Comment by no-lifer** [comment]
@mg-1999 @FriwiDev this is te samen error as https://github.com/bergerhealer/BKCommonLib/issues/24
I believe?

**Comment by mg-1999** [comment]
This is a funny issue. It's giving errors because it can't make a crash
report that displays errors.

Op vr 20 mei 2016 10:43 schreef no-lifer <notifications@github.com>:

> @mg-1999 <https://github.com/mg-1999> @FriwiDev
> <https://github.com/FriwiDev> this is te samen error as
> bergerhealer/BKCommonLib#24
> <https://github.com/bergerhealer/BKCommonLib/issues/24>
> I believe?
>
> —
> You are receiving this because you were mentioned.
>
>
> Reply to this email directly or view it on GitHub
> <https://github.com/bergerhealer/TrainCarts/issues/75#issuecomment-220549434>
>
-- 

Met vriendelijk groeten,

Matthijs Giezenberg

**Comment by no-lifer** [comment]
Sadly that is True if you type stop you Will get a error that he can't log the error

**Comment by RyanHecht** [comment]
I thought it was pretty funny too haha

**Comment by RyanHecht** [comment]
If it's related to BKCommonLib#24, does that mean it's fixed in your latest pull request? @mg-1999

**Comment by mg-1999** [comment]
I haven't noticed this on my local dev server, but I didn't gave it a lot of testing either. So I don't really know if its fixed :)

**Comment by mg-1999** [comment]
I saw this error too, but its related to https://github.com/bergerhealer/BKCommonLib/issues/24 so just closing this for now
