### ISSUE TITLE
Existing trains are not loaded after server restart

### ISSUE THREAD

**Issue by kpaulisse** [bergerhealer/TrainCarts#8]
Almost certainly has to do with this exception. I'll probably look at it later.

```
[17:12:46 INFO]: [Train_Carts] Restoring trains and loading nearby chunks...
[17:12:46 WARN]: java.lang.IllegalArgumentException: Can not set final [Ljava.lang.String; field org.bukkit.craftbukkit.v1_8_R3.block.CraftSign.lines to [Lnet.minecraft.server.v1_8_R3.IChatBaseComponent;
[17:12:46 WARN]:        at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:164)
[17:12:46 WARN]:        at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:168)
[17:12:46 WARN]:        at sun.reflect.UnsafeQualifiedObjectFieldAccessorImpl.set(UnsafeQualifiedObjectFieldAccessorImpl.java:83)
[17:12:46 WARN]:        at java.lang.reflect.Field.set(Field.java:741)
[17:12:46 WARN]:        at com.bergerkiller.bukkit.common.reflection.SafeField.set(SafeField.java:129)
[17:12:46 WARN]:        at com.bergerkiller.bukkit.common.reflection.classes.BlockStateRef$1.apply(BlockStateRef.java:49)
[17:12:46 WARN]:        at com.bergerkiller.bukkit.common.reflection.classes.BlockStateRef$TileInstantiator.newInstance(BlockStateRef.java:167)
[17:12:46 WARN]:        at com.bergerkiller.bukkit.common.reflection.classes.BlockStateRef$TileInstantiator.newInstance(BlockStateRef.java:151)
[17:12:46 WARN]:        at com.bergerkiller.bukkit.common.reflection.classes.BlockStateRef.toBlockState(BlockStateRef.java:120)
[17:12:46 WARN]:        at com.bergerkiller.bukkit.common.conversion.type.WrapperConverter$5.convertSpecial(WrapperConverter.java:123)
[17:12:46 WARN]:        at com.bergerkiller.bukkit.common.conversion.type.WrapperConverter$5.convertSpecial(WrapperConverter.java:118)
[17:12:46 WARN]:        at com.bergerkiller.bukkit.common.conversion.BasicConverter.convert(BasicConverter.java:44)
[17:12:46 WARN]:        at com.bergerkiller.bukkit.common.conversion.BasicConverter.convert(BasicConverter.java:50)
[17:12:46 WARN]:        at com.bergerkiller.bukkit.common.conversion.util.ConvertingIterator.next(ConvertingIterator.java:29)
[17:12:46 WARN]:        at com.bergerkiller.bukkit.tc.RedstoneTracker.onChunkLoad(RedstoneTracker.java:34)
[17:12:46 WARN]:        at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
[17:12:46 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[17:12:46 WARN]:        at java.lang.reflect.Method.invoke(Method.java:606)
[17:12:46 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306)
[17:12:46 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[17:12:46 WARN]:        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
[17:12:46 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
[17:12:46 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:59)
[17:12:46 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:1)
[17:12:46 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:337)
[17:12:46 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:295)
[17:12:46 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:16)
[17:12:46 WARN]:        at net.minecraft.server.v1_8_R3.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:115)
[17:12:46 WARN]:        at com.bergerkiller.bukkit.common.internal.ChunkProviderServerHook.getChunkAt(ChunkProviderServerHook.java:113)
[17:12:46 WARN]:        at net.minecraft.server.v1_8_R3.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:97)
[17:12:46 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftWorld.getChunkAt(CraftWorld.java:125)
[17:12:46 WARN]:        at com.bergerkiller.bukkit.tc.storage.OfflineGroupManager.checkChunks(OfflineGroupManager.java:139)
[17:12:46 WARN]:        at com.bergerkiller.bukkit.tc.storage.OfflineGroupManager.refreshGroups(OfflineGroupManager.java:453)
[17:12:46 WARN]:        at com.bergerkiller.bukkit.tc.storage.OfflineGroupManager.refresh(OfflineGroupManager.java:108)
[17:12:46 WARN]:        at com.bergerkiller.bukkit.tc.storage.OfflineGroupManager.refresh(OfflineGroupManager.java:97)
[17:12:46 WARN]:        at com.bergerkiller.bukkit.tc.TrainCarts.enable(TrainCarts.java:533)
[17:12:46 WARN]:        at com.bergerkiller.bukkit.common.PluginBase.onEnable(PluginBase.java:756)
[17:12:46 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
[17:12:46 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)
[17:12:46 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[17:12:46 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:356)
[17:12:46 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:316)
[17:12:46 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:418)
[17:12:46 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:382)
[17:12:46 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:337)
[17:12:46 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:256)
[17:12:46 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:528)
[17:12:46 WARN]:        at java.lang.Thread.run(Thread.java:745)
```

**Comment by kpaulisse** [comment]
I can confirm the above patch fixes this problem. If you merge that PR you can close this issue.
